//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDXPCDaemon.h"

#import "SDAirDropAlertManager-Protocol.h"
#import "SDAirDropTransferManagerProtocol-Protocol.h"

@class NSArray, NSMutableDictionary, NSObject, NSString;
@protocol SDAirDropAlertManagerDelegate;

__attribute__((visibility("hidden")))
@interface SDAirDropTransferManager : SDXPCDaemon <SDAirDropTransferManagerProtocol, SDAirDropAlertManager>
{
    NSObject<SDAirDropAlertManagerDelegate> *delegate;	// 8 = 0x8
    NSObject<SDAirDropAlertManagerDelegate> *_classroomDelegate;	// 16 = 0x10
    NSMutableDictionary *_transferIdentifierToTransfer;	// 24 = 0x18
    NSMutableDictionary *_transferIdentifierToHandler;	// 32 = 0x20
    NSArray *_kvoObservingKeys;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100085950
@property(retain) NSArray *kvoObservingKeys; // @synthesize kvoObservingKeys=_kvoObservingKeys;
@property(retain) NSMutableDictionary *transferIdentifierToHandler; // @synthesize transferIdentifierToHandler=_transferIdentifierToHandler;
@property(retain) NSMutableDictionary *transferIdentifierToTransfer; // @synthesize transferIdentifierToTransfer=_transferIdentifierToTransfer;
@property(nonatomic) __weak NSObject<SDAirDropAlertManagerDelegate> *classroomDelegate; // @synthesize classroomDelegate=_classroomDelegate;
@property(nonatomic) __weak NSObject<SDAirDropAlertManagerDelegate> *delegate; // @synthesize delegate;
- (id)itemTypesForTransfer:(id)arg1;	// IMP=0x00000001000852b8
- (void)loadAllPersistedTransfers;	// IMP=0x0000000100084f5c
- (void)cleanUpURL:(id)arg1;	// IMP=0x0000000100084de4
- (id)transferURLForTransfer:(id)arg1;	// IMP=0x0000000100084cfc
- (id)persistedTransfersBaseURL;	// IMP=0x0000000100084ca4
- (void)setTransferState:(unsigned long long)arg1 forTransfer:(id)arg2 shouldNotify:(_Bool)arg3 shouldCleanup:(_Bool)arg4;	// IMP=0x0000000100084b40
- (void)setTransferState:(unsigned long long)arg1 forTransfer:(id)arg2 shouldNotify:(_Bool)arg3;	// IMP=0x0000000100084b30
- (void)failTransfer:(id)arg1 withState:(unsigned long long)arg2 failureReason:(unsigned long long)arg3;	// IMP=0x0000000100084978
- (void)handlerFailedForTransfer:(id)arg1;	// IMP=0x0000000100084768
- (void)setHandler:(id)arg1 forTransfer:(id)arg2;	// IMP=0x0000000100084440
- (id)determineHandlerForTransfer:(id)arg1;	// IMP=0x0000000100084004
- (void)connectionInvalidated:(id)arg1;	// IMP=0x0000000100083f20
- (void)connectionEstablished:(id)arg1;	// IMP=0x0000000100083c88
- (_Bool)shouldAcceptNewConnection:(id)arg1;	// IMP=0x0000000100083c80
- (id)remoteObjectInterface;	// IMP=0x0000000100083c64
- (id)exportedInterface;	// IMP=0x0000000100083c48
- (id)machServiceName;	// IMP=0x0000000100083c3c
- (void)transfer:(id)arg1 actionTriggeredForAction:(id)arg2;	// IMP=0x0000000100083b18
- (void)transferUserResponseUpdated:(id)arg1;	// IMP=0x00000001000835f0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100083490
- (void)finishedEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100083384
- (void)errorEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100083250
- (void)cancelEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100083144
- (void)progressEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100083020
- (void)askEventForRecordID:(id)arg1 withResults:(id)arg2;	// IMP=0x0000000100082be4
- (void)cleanUpTransfer:(id)arg1;	// IMP=0x0000000100082ac0
- (void)removeTransfer:(id)arg1 shouldCleanup:(_Bool)arg2;	// IMP=0x000000010008288c
- (void)notifyObserversOfRemovedTransfer:(id)arg1;	// IMP=0x00000001000827d8
- (void)notifyObserversOfUpdatedTransfer:(id)arg1;	// IMP=0x0000000100082730
- (void)_enumerateRemoteObjectProxiesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100082724
- (void)_remoteObjectProxyForConnection:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100082718
- (void)invalidate;	// IMP=0x00000001000826e4
- (void)activate;	// IMP=0x00000001000826b0
- (id)init;	// IMP=0x000000010008255c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

