//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, TCCDAccessObject, TCCDIdentity;

@interface TCCDAccessRecord : NSObject
{
    TCCDIdentity *_subjectIdentity;	// 8 = 0x8
    TCCDAccessObject *_accessObject;	// 16 = 0x10
    unsigned long long _authorizationValue;	// 24 = 0x18
    unsigned long long _authorizationReason;	// 32 = 0x20
    unsigned long long _authorizationVersion;	// 40 = 0x28
    unsigned long long _flags;	// 48 = 0x30
    NSDate *_lastModifiedDate;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000010002b50c
@property(retain) NSDate *lastModifiedDate; // @synthesize lastModifiedDate=_lastModifiedDate;
@property unsigned long long flags; // @synthesize flags=_flags;
@property unsigned long long authorizationVersion; // @synthesize authorizationVersion=_authorizationVersion;
@property unsigned long long authorizationReason; // @synthesize authorizationReason=_authorizationReason;
@property unsigned long long authorizationValue; // @synthesize authorizationValue=_authorizationValue;
@property(retain) TCCDAccessObject *accessObject; // @synthesize accessObject=_accessObject;
@property(retain) TCCDIdentity *subjectIdentity; // @synthesize subjectIdentity=_subjectIdentity;
- (id)description;	// IMP=0x000000010002b43c
- (id)descriptionDictionary;	// IMP=0x000000010002affc
- (id)_dateFormatter;	// IMP=0x000000010002aef0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010002adbc
- (id)initWithSubject:(id)arg1 object:(id)arg2 authorizationValue:(unsigned long long)arg3 authorizationReason:(unsigned long long)arg4 authorizationVersion:(unsigned long long)arg5 lastModified:(id)arg6 flags:(unsigned long long)arg7;	// IMP=0x000000010002ac78

@end

