//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString, NSUUID;

@interface CSAudioRecordDeviceInfo : NSObject <NSCopying, NSSecureCoding>
{
    _Bool _isRemoteDevice;	// 8 = 0x8
    NSString *_route;	// 16 = 0x10
    NSUUID *_remoteDeviceUID;	// 24 = 0x18
    NSString *_remoteDeviceProductIdentifier;	// 32 = 0x20
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010007fc88
- (void).cxx_destruct;	// IMP=0x000000010007ffd4
@property(readonly, copy, nonatomic) NSString *remoteDeviceProductIdentifier; // @synthesize remoteDeviceProductIdentifier=_remoteDeviceProductIdentifier;
@property(readonly, copy, nonatomic) NSUUID *remoteDeviceUID; // @synthesize remoteDeviceUID=_remoteDeviceUID;
@property(readonly, nonatomic) _Bool isRemoteDevice; // @synthesize isRemoteDevice=_isRemoteDevice;
@property(readonly, copy, nonatomic) NSString *route; // @synthesize route=_route;
- (id)initWithAVVCRecordDeviceInfo:(id)arg1;	// IMP=0x000000010007fec0
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010007fd58
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010007fc90
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010007fc84
- (id)description;	// IMP=0x000000010007fbe0
- (id)xpcObject;	// IMP=0x000000010007faa8
- (id)initWithXPCObject:(id)arg1;	// IMP=0x000000010007f8e8
- (id)initWithRoute:(id)arg1 isRemoteDevice:(_Bool)arg2 remoteDeviceUID:(id)arg3 remoteDeviceProductIdentifier:(id)arg4;	// IMP=0x000000010007f7e4

@end

