//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CSAudioStreamProvidingDelegate-Protocol.h"
#import "CSXPCConnectionDelegate-Protocol.h"

@class CSAcousticSLProxy, CSAudioRecordContext, CSAudioStream, CSXPCConnection, NSDictionary, NSString;
@protocol CSAudioStreamProviding, CSTriggerInfoProviding;

@interface CSAudioStreamProvidingProxy : NSObject <CSXPCConnectionDelegate, CSAudioStreamProvidingDelegate>
{
    id <CSAudioStreamProviding> _audioStreamProviding;	// 8 = 0x8
    id <CSTriggerInfoProviding> _triggerInfoProviding;	// 16 = 0x10
    CSXPCConnection *_xpcConnection;	// 24 = 0x18
    unsigned long long _streamClientType;	// 32 = 0x20
    CSAudioStream *_audioStream;	// 40 = 0x28
    NSDictionary *_lastVoiceTriggerInfo;	// 48 = 0x30
    NSDictionary *_lastRTSTriggerInfo;	// 56 = 0x38
    CSAudioRecordContext *_recordContext;	// 64 = 0x40
    NSString *_recordEventUUID;	// 72 = 0x48
    CSAcousticSLProxy *_acousticAnalyzer;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x000000010000f258
@property(retain, nonatomic) CSAcousticSLProxy *acousticAnalyzer; // @synthesize acousticAnalyzer=_acousticAnalyzer;
@property(retain, nonatomic) NSString *recordEventUUID; // @synthesize recordEventUUID=_recordEventUUID;
@property(retain, nonatomic) CSAudioRecordContext *recordContext; // @synthesize recordContext=_recordContext;
@property(copy) NSDictionary *lastRTSTriggerInfo; // @synthesize lastRTSTriggerInfo=_lastRTSTriggerInfo;
@property(copy) NSDictionary *lastVoiceTriggerInfo; // @synthesize lastVoiceTriggerInfo=_lastVoiceTriggerInfo;
@property(retain, nonatomic) CSAudioStream *audioStream; // @synthesize audioStream=_audioStream;
@property(nonatomic) unsigned long long streamClientType; // @synthesize streamClientType=_streamClientType;
@property(nonatomic) __weak CSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
@property(nonatomic) __weak id <CSTriggerInfoProviding> triggerInfoProviding; // @synthesize triggerInfoProviding=_triggerInfoProviding;
@property(nonatomic, setter=setAudioStreamProvidingForProxy:) __weak id <CSAudioStreamProviding> audioStreamProviding; // @synthesize audioStreamProviding=_audioStreamProviding;
- (void)_setAllowMixableAudioWhileRecording:(_Bool)arg1;	// IMP=0x000000010000f01c
- (void)_sendDelegateMessageToClient:(id)arg1;	// IMP=0x000000010000ef28
- (void)audioStreamProvider:(id)arg1 didHardwareConfigurationChange:(long long)arg2;	// IMP=0x000000010000edec
- (void)audioStreamProvider:(id)arg1 audioChunkForTVAvailable:(id)arg2;	// IMP=0x000000010000ecdc
- (void)audioStreamProvider:(id)arg1 audioBufferAvailable:(id)arg2;	// IMP=0x000000010000ebb8
- (void)audioStreamProvider:(id)arg1 didStopStreamUnexpectly:(long long)arg2;	// IMP=0x000000010000e9a8
- (void)_handlePlaybackRouteMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000e860
- (void)_handleIsNarrowband:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000e72c
- (void)_handleRecordSettings:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000e5d4
- (void)_handleAudioDeviceInfo:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000e47c
- (void)_handleRecordDeviceInfo:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000e324
- (void)_handleRecordRouteMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000e1dc
- (void)_handleIsRecordingMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000e0a8
- (void)_handleVoiceTriggerInfoMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000db44
- (void)_handleAcousticSLResultMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000d984
- (void)_handleStopAudioStreamMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000d598
- (void)_handleStartAudioStreamMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000cdb0
- (void)_handleAudioStreamPrepareMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000ca64
- (void)_handleAudioStreamRequestMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000c7a8
- (void)_handleSetCurrentConextMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000c534
- (void)handleXPCMessage:(id)arg1 messageBody:(id)arg2 client:(id)arg3;	// IMP=0x000000010000c398
- (void)CSXPCConnectionReceivedClientError:(id)arg1 clientError:(id)arg2 client:(id)arg3;	// IMP=0x000000010000c034
- (void)_sendReply:(id)arg1 client:(id)arg2 result:(_Bool)arg3 error:(id)arg4;	// IMP=0x000000010000bf44
- (void)setInitialContext:(id)arg1;	// IMP=0x000000010000bf30
- (id)initWithXPCConnection:(id)arg1;	// IMP=0x000000010000bd64

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

