//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CSAudioInjectionEngine.h"

#import "CSAudioConverterDelegate-Protocol.h"
#import "CSAudioInjectionEngineDelegate-Protocol.h"

@class CSAudioConverter, CSAudioInjectionDevice, NSObject, NSString, NSUUID;
@protocol CSAudioInjectionEngineDelegate, OS_dispatch_queue;

@interface CSAudioInjectionTvRemoteEngine : CSAudioInjectionEngine <CSAudioInjectionEngineDelegate, CSAudioConverterDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    id <CSAudioInjectionEngineDelegate> _delegate;	// 16 = 0x10
    NSUUID *_uuid;	// 24 = 0x18
    CSAudioInjectionDevice *_connectedDevice;	// 32 = 0x20
    CSAudioConverter *_opusEncoder;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x000000010008b00c
@property(retain, nonatomic) CSAudioConverter *opusEncoder; // @synthesize opusEncoder=_opusEncoder;
@property(nonatomic) __weak CSAudioInjectionDevice *connectedDevice; // @synthesize connectedDevice=_connectedDevice;
@property(retain, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) __weak id <CSAudioInjectionEngineDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)audioConverterDidConvertPackets:(id)arg1 packets:(id)arg2 durationInSec:(float)arg3 timestamp:(unsigned long long)arg4 arrivalTimestampToAudioRecorder:(unsigned long long)arg5;	// IMP=0x000000010008ae1c
- (void)audioEngineAudioChunkForTvAvailable:(id)arg1 audioChunk:(id)arg2;	// IMP=0x000000010008ae18
- (void)audioEngineBufferAvailable:(id)arg1 audioStreamHandleId:(unsigned long long)arg2 buffer:(id)arg3 remoteVAD:(id)arg4 atTime:(unsigned long long)arg5;	// IMP=0x000000010008adf4
- (void)audioEngineDidStopRecord:(id)arg1 audioStreamHandleId:(unsigned long long)arg2 reason:(unsigned long long)arg3;	// IMP=0x000000010008ad44
- (void)audioEngineDidStartRecord:(id)arg1 audioStreamHandleId:(unsigned long long)arg2 successfully:(_Bool)arg3 error:(id)arg4;	// IMP=0x000000010008ac94
- (void)stopAudioStream;	// IMP=0x000000010008ac60
- (void)startAudioStreamWithOption:(id)arg1;	// IMP=0x000000010008ac2c
- (_Bool)isRecording;	// IMP=0x000000010008abf8
- (_Bool)injectAudio:(id)arg1 withScaleFactor:(float)arg2 playbackStarted:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010008abc4
- (_Bool)injectAudio:(id)arg1;	// IMP=0x000000010008ab90
- (void)stop;	// IMP=0x000000010008ab5c
- (void)start;	// IMP=0x000000010008ab28
- (void)attachDevice:(id)arg1;	// IMP=0x000000010008aaa4
- (_Bool)alwaysOnVoiceTriggerEnabled;	// IMP=0x000000010008aa9c
- (void)setAlwaysOnVoiceTriggerEnabled:(_Bool)arg1;	// IMP=0x000000010008aa98
- (_Bool)isAlwaysOnVoiceTriggerAvailable;	// IMP=0x000000010008aa90
- (id)initWithStreamHandleId:(unsigned long long)arg1;	// IMP=0x000000010008a9a4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

