//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CSConnectionServiceDelegate-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class NSMutableArray, NSString, NSXPCInterface, NSXPCListener;
@protocol OS_dispatch_queue;

@interface CSConnectionListener : NSObject <NSXPCListenerDelegate, CSConnectionServiceDelegate>
{
    NSXPCListener *_listener;	// 8 = 0x8
    NSXPCInterface *_exportedInterface;	// 16 = 0x10
    NSXPCInterface *_remoteInterface;	// 24 = 0x18
    id _proxyObject;	// 32 = 0x20
    NSMutableArray *_clientConnections;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_queue;	// 48 = 0x30
    NSString *_machServiceName;	// 56 = 0x38
}

+ (id)createSmartSiriVolumeListener;	// IMP=0x00000001000638d8
- (void).cxx_destruct;	// IMP=0x00000001000bef48
@property(retain, nonatomic) NSString *machServiceName; // @synthesize machServiceName=_machServiceName;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableArray *clientConnections; // @synthesize clientConnections=_clientConnections;
- (void)resumeConnection;	// IMP=0x00000001000beea0
- (void)notifyClientsWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000beb2c
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00000001000be010
- (void)dealloc;	// IMP=0x00000001000bdf34
- (id)initWithMachService:(id)arg1 withServiceInterface:(id)arg2 withServiceObject:(id)arg3 withDelegateInterface:(id)arg4;	// IMP=0x00000001000bdc8c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

