//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, _EARSyncSpeechRecognizer;

@interface CSSyncKeywordAnalyzerQuasar : NSObject
{
    NSMutableArray *_previousUtteranceTokens;	// 8 = 0x8
    NSArray *_lastReportedRecogResults;	// 16 = 0x10
    NSArray *_triggerTokenList;	// 24 = 0x18
    _EARSyncSpeechRecognizer *_syncRecognizer;	// 32 = 0x20
    _Bool _useKeywordSpotting;	// 40 = 0x28
    double _triggerConfidence;	// 48 = 0x30
    unsigned long long _activeChannel;	// 56 = 0x38
    NSDictionary *_ctcKwdToPhraseIdMap;	// 64 = 0x40
}

+ (void)dumpEARSpeechRecognitionResults:(id)arg1;	// IMP=0x0000000100002d10
- (void).cxx_destruct;	// IMP=0x000000010000348c
@property(retain, nonatomic) NSDictionary *ctcKwdToPhraseIdMap; // @synthesize ctcKwdToPhraseIdMap=_ctcKwdToPhraseIdMap;
@property(nonatomic) unsigned long long activeChannel; // @synthesize activeChannel=_activeChannel;
@property(nonatomic) double triggerConfidence; // @synthesize triggerConfidence=_triggerConfidence;
- (double)_getConfidence:(id)arg1;	// IMP=0x00000001000031f0
- (void)_calculateTriggerConfidence:(id)arg1;	// IMP=0x0000000100003004
@property(readonly, nonatomic) NSDictionary *phraseIdScores;
- (void)processAudioChunk:(id)arg1;	// IMP=0x000000010000269c
- (void)flushAudio;	// IMP=0x0000000100002524
- (void)resetWithLanguage:(id)arg1 withFarField:(unsigned char)arg2 withAudioSource:(id)arg3;	// IMP=0x0000000100002390
- (id)initWithConfigPath:(id)arg1 triggerTokens:(id)arg2 useKeywordSpotting:(_Bool)arg3;	// IMP=0x0000000100001fd8

@end

