//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSData, NSString;

@interface CSVoiceTriggerRTModel : NSObject <NSSecureCoding, NSCopying>
{
    NSData *_modelData;	// 8 = 0x8
    NSString *_modelLocale;	// 16 = 0x10
    NSString *_modelHash;	// 24 = 0x18
    NSData *_digest;	// 32 = 0x20
    NSData *_signature;	// 40 = 0x28
    NSData *_certificate;	// 48 = 0x30
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010003bf44
- (void).cxx_destruct;	// IMP=0x000000010003c8e8
@property(readonly, nonatomic) NSData *certificate; // @synthesize certificate=_certificate;
@property(readonly, nonatomic) NSData *signature; // @synthesize signature=_signature;
@property(readonly, nonatomic) NSData *digest; // @synthesize digest=_digest;
@property(readonly, nonatomic) NSString *modelHash; // @synthesize modelHash=_modelHash;
@property(readonly, nonatomic) NSString *modelLocale; // @synthesize modelLocale=_modelLocale;
@property(readonly, nonatomic) NSData *modelData; // @synthesize modelData=_modelData;
- (id)description;	// IMP=0x000000010003c734
- (id)builtInRTModelDictionary;	// IMP=0x000000010003c5fc
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010003c51c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010003c410
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010003c204
- (id)initWithData:(id)arg1 hash:(id)arg2 locale:(id)arg3;	// IMP=0x000000010003c134
- (id)initWithHash:(id)arg1 locale:(id)arg2;	// IMP=0x000000010003c090
- (id)initWithData:(id)arg1 hash:(id)arg2 locale:(id)arg3 digest:(id)arg4 signature:(id)arg5 certificate:(id)arg6;	// IMP=0x000000010003bf4c

@end

