//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol IDSAPNSAckTrackerDelegate;

@interface IDSAPNSAckTracker : NSObject
{
    NSString *_guid;	// 8 = 0x8
    id <IDSAPNSAckTrackerDelegate> _delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010028c5dc
@property(retain, nonatomic) id <IDSAPNSAckTrackerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)addBlockToAggregatableMessage:(id)arg1 trackingSet:(id)arg2;	// IMP=0x000000010028c16c
- (void)addBlockToAggregateMessage:(id)arg1;	// IMP=0x000000010028bedc
- (void)trackMessages:(id)arg1;	// IMP=0x000000010028bc04
- (id)initWithGUID:(id)arg1;	// IMP=0x000000010028bb30

@end

