//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMSystemMonitorListener-Protocol.h"

@class NSMutableArray, NSMutableDictionary;
@protocol FTPasswordManager, IDSAppleIDRegistrationCenterMessageDelivery;

@interface IDSAppleIDRegistrationCenter : NSObject <IMSystemMonitorListener>
{
    NSMutableDictionary *_queues;	// 8 = 0x8
    NSMutableArray *_handlers;	// 16 = 0x10
    id <IDSAppleIDRegistrationCenterMessageDelivery> _messageDelivery;	// 24 = 0x18
    id <FTPasswordManager> _passwordManager;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x00000001005883c8
- (void).cxx_destruct;	// IMP=0x000000010058fac4
- (void)removeListener:(id)arg1;	// IMP=0x000000010058fa40
- (void)addListener:(id)arg1;	// IMP=0x000000010058f990
- (void)cancelActionsForRegistrationInfo:(id)arg1;	// IMP=0x000000010058f8d0
- (_Bool)authenticateRegistration:(id)arg1;	// IMP=0x000000010058f788
- (_Bool)authenticateRegistration:(id)arg1 requireSilentAuth:(_Bool)arg2;	// IMP=0x000000010058f628
- (_Bool)authenticateRegistration:(id)arg1 forceNewToken:(_Bool)arg2;	// IMP=0x000000010058f4c8
- (_Bool)authenticateRegistration:(id)arg1 forceNewToken:(_Bool)arg2 requireSilentAuth:(_Bool)arg3;	// IMP=0x000000010058f354
- (_Bool)authenticateRegistration:(id)arg1 forceRenewal:(_Bool)arg2 requireSilentAuth:(_Bool)arg3;	// IMP=0x000000010058f1d8
- (_Bool)validateRegion:(id)arg1 phoneNumber:(id)arg2 forRegistration:(id)arg3;	// IMP=0x000000010058f034
- (_Bool)queryInitialInvitationContextForRegistration:(id)arg1;	// IMP=0x000000010058eef4
- (_Bool)_queryInitialInvitationContextForRegistration:(id)arg1;	// IMP=0x000000010058ea40
- (_Bool)_validateRegionID:(id)arg1 phoneNumber:(id)arg2 registration:(id)arg3;	// IMP=0x000000010058e518
- (_Bool)_registrationNeedsAuthentication:(id)arg1;	// IMP=0x000000010058e3f4
- (_Bool)_registrationIsAuthenticating:(id)arg1;	// IMP=0x000000010058e340
- (_Bool)_sendAuthenticationRequest:(id)arg1 forceNew:(_Bool)arg2 forceRenewal:(_Bool)arg3 failIfNotSilent:(_Bool)arg4;	// IMP=0x000000010058dd0c
- (_Bool)_sendAuthenticationRequest:(id)arg1 forceNew:(_Bool)arg2 failIfNotSilent:(_Bool)arg3;	// IMP=0x000000010058dc60
- (_Bool)_sendAuthenticationRequest:(id)arg1 forceNew:(_Bool)arg2;	// IMP=0x000000010058dbc8
- (void)_fetchTokenForRegistrationInfo:(id)arg1 failIfNotSilent:(_Bool)arg2 failureBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010058d268
- (void)_renewTokenForRegistrationInfo:(id)arg1 forceRenewal:(_Bool)arg2 failIfNotSilent:(_Bool)arg3;	// IMP=0x000000010058c95c
- (void)_noteSuccessfulToken:(id)arg1 profileID:(id)arg2 selfID:(id)arg3 forRegistrationInfo:(id)arg4 wasFetched:(_Bool)arg5;	// IMP=0x000000010058c3e0
- (void)_processRegionValidationMessage:(id)arg1 deliveredWithError:(id)arg2 resultCode:(long long)arg3 resultDictionary:(id)arg4;	// IMP=0x000000010058bfe8
- (void)_processDefaultInvitationContextMessage:(id)arg1 deliveredWithError:(id)arg2 resultCode:(long long)arg3 resultDictionary:(id)arg4;	// IMP=0x000000010058bc4c
- (void)_postUserNotificationWithTitle:(id)arg1 message:(id)arg2 identifier:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010058b9f8
- (void)_notifyAuthenticationSuccess:(id)arg1;	// IMP=0x000000010058b470
- (void)_notifyAuthenticationFailure:(id)arg1 responseCode:(long long)arg2 registrationError:(long long)arg3 error:(id)arg4 info:(id)arg5;	// IMP=0x000000010058aa50
- (void)_notifyAuthenticating:(id)arg1;	// IMP=0x000000010058a6b4
- (void)_notifyRegionValidationFailure:(id)arg1 responseCode:(long long)arg2 registrationError:(long long)arg3 error:(id)arg4 info:(id)arg5;	// IMP=0x0000000100589e58
- (void)_notifyRegionValidationSuccess:(id)arg1 regionID:(id)arg2 phoneNumber:(id)arg3 context:(id)arg4 verified:(_Bool)arg5;	// IMP=0x0000000100589840
- (void)_notifyInitialRegionQuerySuccess:(id)arg1;	// IMP=0x0000000100589494
- (void)_removeMessageForRegistration:(id)arg1 fromQueueForKey:(id)arg2;	// IMP=0x00000001005891b4
- (_Bool)_haveQueuedMessageForRegistration:(id)arg1 inQueueForKey:(id)arg2;	// IMP=0x0000000100588ebc
- (void)_serviceQueueForKey:(id)arg1;	// IMP=0x0000000100588afc
- (void)_setQueue:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001005889d4
- (id)_queueForKey:(id)arg1;	// IMP=0x0000000100588878
- (void)dealloc;	// IMP=0x00000001005887a0
- (id)init;	// IMP=0x00000001005886b4
- (id)initWithMessageDelivery:(id)arg1 passwordManager:(id)arg2;	// IMP=0x000000010058855c

@end

