//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol IDSDaemonMIGQueryInterfaceDelegate, IDSXPCConnectionProtocol;

@interface IDSDaemonMIGQueryInterface : NSObject
{
    id <IDSXPCConnectionProtocol> _server;	// 8 = 0x8
    id _delegate;	// 16 = 0x10
    _Bool _shuttingDown;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010049c604
- (void).cxx_destruct;	// IMP=0x000000010049e200
@property __weak id <IDSDaemonMIGQueryInterfaceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)denyIncomingGrantRequests;	// IMP=0x000000010049e140
- (void)acceptIncomingGrantRequests;	// IMP=0x000000010049e03c
- (void)__setupServer;	// IMP=0x000000010049c798

@end

