//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDSKeychainWrapper;

@interface IDSKeychainKeyElectionStore : NSObject
{
    IDSKeychainWrapper *_keychainWrapper;	// 8 = 0x8
}

+ (_Bool)isItemNotFoundError:(id)arg1;	// IMP=0x000000010013121c
- (void).cxx_destruct;	// IMP=0x0000000100132f50
@property(readonly, nonatomic) IDSKeychainWrapper *keychainWrapper; // @synthesize keychainWrapper=_keychainWrapper;
- (id)_fullClusterFromData:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100132d3c
- (id)_keychainEntryForCluster:(id)arg1;	// IMP=0x0000000100132b38
- (_Bool)removeFullClusterWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010013285c
- (void)_storeData:(id)arg1 forIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100132624
- (void)storeFullCluster:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100131e74
- (id)fetchFullClusterWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100131580
- (id)initWithKeychainWrapper:(id)arg1;	// IMP=0x00000001001314ac
- (id)identifierForFullCluster:(id)arg1;	// IMP=0x0000000100131290

@end

