//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;
@protocol IDSMultiplexerTransport;

@protocol IDSMultiplexerTransportClientConnection <NSObject>
@property(nonatomic) unsigned long long context;
@property(nonatomic) unsigned int portsSignature;
@property(retain, nonatomic) NSArray *hostComponents;
@property(retain, nonatomic) id remoteIdentifier;
@property(retain, nonatomic) id localIdentifier;
@property(readonly, nonatomic) _Bool invalidated;
@property(retain, nonatomic) id <IDSMultiplexerTransport> transport;
- (void)invalidate;
- (void)startReadOnTransportThread;
- (void)writePacketBuffer:(CDStruct_78c9ccae *)arg1;
- (void)setPacketBufferReadHandler:(_Bool (^)(struct *))arg1;
@end

