//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NWNetworkAgent-Protocol.h"

@class NSString, NSUUID, NWNetworkAgentRegistration;

@interface IDSNexusAgent : NSObject <NWNetworkAgent>
{
    NWNetworkAgentRegistration *_registration;	// 8 = 0x8
    _Bool active;	// 16 = 0x10
    NSUUID *agentUUID;	// 24 = 0x18
}

+ (id)agentFromData:(id)arg1;	// IMP=0x00000001000568f4
+ (id)agentType;	// IMP=0x00000001000568d4
+ (id)agentDomain;	// IMP=0x000000010005685c
- (void).cxx_destruct;	// IMP=0x0000000100057984
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active;
@property(copy, nonatomic) NSUUID *agentUUID; // @synthesize agentUUID;
- (void)unassertAgentWithOptions:(id)arg1;	// IMP=0x00000001000576b4
- (_Bool)assertAgentWithOptions:(id)arg1;	// IMP=0x000000010005748c
- (_Bool)startAgentWithOptions:(id)arg1;	// IMP=0x0000000100057264
- (void)closeNexusWithOptions:(id)arg1;	// IMP=0x0000000100057004
- (_Bool)requestNexusWithOptions:(id)arg1;	// IMP=0x0000000100056c4c
@property(nonatomic, getter=isNexusProvider) _Bool nexusProvider;
@property(nonatomic, getter=isNetworkProvider) _Bool networkProvider;
@property(nonatomic, getter=isSpecificUseOnly) _Bool specificUseOnly;
@property(nonatomic, getter=isUserActivated) _Bool userActivated;
@property(nonatomic, getter=isKernelActivated) _Bool kernelActivated;
@property(nonatomic, getter=isVoluntary) _Bool voluntary;
@property(copy, nonatomic) NSString *agentDescription;
- (id)copyAgentData;	// IMP=0x0000000100056958

// Remaining properties
@property(nonatomic) _Bool requiresAssert;
@property(nonatomic) _Bool supportsBrowseRequests;
@property(nonatomic) _Bool supportsListenRequests;
@property(nonatomic) _Bool supportsResolveRequests;
@property(nonatomic) _Bool updateClientsImmediately;

@end

