//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData, NSString;

@interface IDSProtoKeyTransparencyTrustedServiceSignature : PBCodable <NSCopying>
{
    NSString *_serviceIdentifier;	// 8 = 0x8
    NSData *_signature;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010014f36c
@property(retain, nonatomic) NSData *signature; // @synthesize signature=_signature;
@property(retain, nonatomic) NSString *serviceIdentifier; // @synthesize serviceIdentifier=_serviceIdentifier;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010014f204
- (unsigned long long)hash;	// IMP=0x000000010014f194
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010014f01c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010014ef0c
- (void)copyTo:(id)arg1;	// IMP=0x000000010014ee64
- (void)writeTo:(id)arg1;	// IMP=0x000000010014edc4
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010014ed5c
- (id)dictionaryRepresentation;	// IMP=0x000000010014e830
- (id)description;	// IMP=0x000000010014e75c
@property(readonly, nonatomic) _Bool hasSignature;
@property(readonly, nonatomic) _Bool hasServiceIdentifier;

@end

