//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDSKVStore;

@interface IDSPublicIdentityCache : NSObject
{
    IDSKVStore *_kvStore;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0000000100015f28
- (void).cxx_destruct;	// IMP=0x00000001000173cc
- (void)deleteCache;	// IMP=0x0000000100017398
- (_Bool)cleanupWithError:(id *)arg1;	// IMP=0x0000000100016f30
- (id)identityForToken:(id)arg1 uri:(id)arg2 service:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100016a84
- (_Bool)addIdentity:(id)arg1 forToken:(id)arg2 uri:(id)arg3 service:(id)arg4 error:(id *)arg5;	// IMP=0x00000001000166f0
- (id)identityDataForToken:(id)arg1 uri:(id)arg2 service:(id)arg3 error:(id *)arg4;	// IMP=0x00000001000165d0
- (_Bool)addIdentityData:(id)arg1 forToken:(id)arg2 uri:(id)arg3 service:(id)arg4 error:(id *)arg5;	// IMP=0x0000000100016488
- (id)keyForToken:(id)arg1 uri:(id)arg2 service:(id)arg3;	// IMP=0x000000010001636c
- (id)initWithPath:(id)arg1;	// IMP=0x0000000100016268
- (id)init;	// IMP=0x00000001000160bc

@end

