//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol IDSPairedDevicePersister;

@interface IDSPairedDeviceRepository : NSObject
{
    NSMutableDictionary *_pairedDevices;	// 8 = 0x8
    struct os_unfair_lock_s _pairedDevicesLock;	// 16 = 0x10
    id <IDSPairedDevicePersister> _persister;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001005b4a90
- (void)_accessPairedDevicesInCriticalSectionWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001005b4a1c
- (_Bool)_criticalPersistState;	// IMP=0x00000001005b497c
- (_Bool)_criticalPerformTransactionWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001005b48c4
- (_Bool)_performTransactionInCriticalSectionWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001005b4718
- (_Bool)shouldUseIPsecLinkForDefaultPairedDevice;	// IMP=0x00000001005b46b8
- (_Bool)_criticalUpdatePairedDeviceWithCBUUID:(id)arg1 iCloudURIs:(id)arg2 pushToken:(id)arg3;	// IMP=0x00000001005b4170
- (_Bool)updatePairedDeviceWithCBUUID:(id)arg1 iCloudURIs:(id)arg2 pushToken:(id)arg3;	// IMP=0x00000001005b3de0
- (_Bool)_criticalUpdatePairedDeviceWithCBUUID:(id)arg1 pairingType:(long long)arg2;	// IMP=0x00000001005b3ac0
- (_Bool)updatePairedDeviceWithCBUUID:(id)arg1 pairingType:(long long)arg2;	// IMP=0x00000001005b3764
- (_Bool)_criticalUpdatePairedDeviceWithCBUUID:(id)arg1 deviceUniqueID:(id)arg2 buildVersion:(id)arg3 productVersion:(id)arg4 productName:(id)arg5 pairingProtocolVersion:(unsigned int)arg6 minCompatibilityVersion:(unsigned int)arg7 maxCompatibilityVersion:(unsigned int)arg8 serviceMinCompatibilityVersion:(unsigned short)arg9;	// IMP=0x00000001005b298c
- (_Bool)updatePairedDeviceWithCBUUID:(id)arg1 deviceUniqueID:(id)arg2 buildVersion:(id)arg3 productVersion:(id)arg4 productName:(id)arg5 pairingProtocolVersion:(unsigned int)arg6 minCompatibilityVersion:(unsigned int)arg7 maxCompatibilityVersion:(unsigned int)arg8 serviceMinCompatibilityVersion:(unsigned short)arg9;	// IMP=0x00000001005b23b4
- (_Bool)_criticalUpdatePairedDeviceWithCBUUID:(id)arg1 supportIPsec:(_Bool)arg2;	// IMP=0x00000001005b2048
- (_Bool)updatePairedDeviceWithCBUUID:(id)arg1 supportIPsec:(_Bool)arg2;	// IMP=0x00000001005b1cf0
- (_Bool)_criticalUpdatePairedDeviceWithCBUUID:(id)arg1 deviceInfoPayload:(id)arg2;	// IMP=0x00000001005b1ab8
- (_Bool)updatePairedDeviceWithCBUUID:(id)arg1 deviceInfoPayload:(id)arg2;	// IMP=0x00000001005b1758
- (_Bool)_criticalPurgeSecuredEncryptionKeysForAllPairedDevices;	// IMP=0x00000001005b1550
- (_Bool)purgeSecuredEncryptionKeysForAllPairedDevices;	// IMP=0x00000001005b13b8
- (id)_criticalActivePairedDevice;	// IMP=0x00000001005b11fc
- (id)activePairedDevice;	// IMP=0x00000001005b1054
- (void)_criticalUpdatePairedDevice:(id)arg1 isActive:(_Bool)arg2;	// IMP=0x00000001005b0f98
- (long long)_criticalPerformPairedDeviceActivationWithCBUUID:(id)arg1;	// IMP=0x00000001005b0de0
- (void)_criticalPerformPairedDeviceDeactivation;	// IMP=0x00000001005b0b28
- (long long)_criticalActivatePairedDeviceWithCBUUID:(id)arg1;	// IMP=0x00000001005b0a34
- (void)deactivatePairedDevices;	// IMP=0x00000001005b0888
- (long long)activatePairedDeviceWithCBUUID:(id)arg1;	// IMP=0x00000001005b0584
- (_Bool)isEmpty;	// IMP=0x00000001005b0500
- (id)pairedDevicesWithIsPairingValue:(_Bool)arg1;	// IMP=0x00000001005b02e4
- (id)_criticalAllPairedDevices;	// IMP=0x00000001005b0254
- (id)allPairedDevicesWithType:(long long)arg1;	// IMP=0x00000001005aff34
- (id)allPairedDevices;	// IMP=0x00000001005afd8c
- (_Bool)_criticalRemovePairedDeviceWithCBUUID:(id)arg1;	// IMP=0x00000001005afbbc
- (_Bool)removePairedDeviceWithCBUUID:(id)arg1;	// IMP=0x00000001005af8b4
- (void)_criticalPutPairedDevice:(id)arg1;	// IMP=0x00000001005af640
- (_Bool)_addPairedDevice:(id)arg1;	// IMP=0x00000001005af338
- (_Bool)addPairedDeviceWithCBUUID:(id)arg1 pairingType:(long long)arg2;	// IMP=0x00000001005af190
- (id)_criticalPairedDeviceWithCBUUID:(id)arg1;	// IMP=0x00000001005af074
- (id)pairedDeviceWithCBUUID:(id)arg1;	// IMP=0x00000001005aec80
- (_Bool)containsPairedDeviceWithCBUUID:(id)arg1;	// IMP=0x00000001005aebdc
- (void)_criticalLoadPairedDeviceArray:(id)arg1;	// IMP=0x00000001005ae944
- (_Bool)loadPairedDevicesFromStorage;	// IMP=0x00000001005ae7d0
- (id)description;	// IMP=0x00000001005ae538
- (id)initWithPersister:(id)arg1;	// IMP=0x00000001005ae434

@end

