//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDSTemporaryPhoneUser;

@interface IDSTemporaryPhoneUserExpirationTimerInfo : NSObject
{
    IDSTemporaryPhoneUser *_user;	// 8 = 0x8
    long long _expirationPhase;	// 16 = 0x10
}

+ (long long)phaseForExpirationDate:(id)arg1;	// IMP=0x000000010012f908
- (void).cxx_destruct;	// IMP=0x000000010012f9d8
@property(readonly) long long expirationPhase; // @synthesize expirationPhase=_expirationPhase;
@property(readonly) IDSTemporaryPhoneUser *user; // @synthesize user=_user;
@property(readonly) double expirationInterval;
- (id)initWithUser:(id)arg1 expirationPhase:(long long)arg2;	// IMP=0x000000010012f6bc
- (id)initWithUser:(id)arg1;	// IMP=0x000000010012f5c8

@end

