//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleMediaServices/AMSTask.h>

@class NSDictionary, NSString;

@interface RequesterRemoteNotificationTask : AMSTask
{
    NSDictionary *_payload;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010000e88c
@property(readonly, nonatomic) NSDictionary *payload; // @synthesize payload=_payload;
- (id)_notifiyExtensionWithResult:(id)arg1;	// IMP=0x000000010000e630
- (id)_requestResultFromResult:(id)arg1 withError:(id *)arg2;	// IMP=0x000000010000e2a4
- (void)_presentRequest:(id)arg1;	// IMP=0x000000010000e290
- (id)_requestFromResult:(id)arg1 withError:(id *)arg2;	// IMP=0x000000010000dd94
- (id)_serverRequestWithError:(id *)arg1;	// IMP=0x000000010000d998
- (id)perform;	// IMP=0x000000010000d33c
@property(readonly, nonatomic) NSString *requestIdentifier;
@property(readonly, nonatomic) long long requestStatus;
- (id)initWithPayload:(id)arg1;	// IMP=0x000000010000d18c

@end

