//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GeoServices/GEOServiceRequestDefaultConfig.h>

@interface _GEOLocationShiftRequestConfig : GEOServiceRequestDefaultConfig
{
}

+ (id)standardConfig;	// IMP=0x000000010001b524
- (CDStruct_026435ec)dataRequestKindForRequest:(id)arg1 traits:(id)arg2;	// IMP=0x000000010001b5b0
- (unsigned long long)urlType;	// IMP=0x000000010001b5a8
- (id)serviceTypeNumber;	// IMP=0x000000010001b590

@end

