//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GeoServices/GEOServer.h>

#import "GEOTileLoaderInternalDelegate-Protocol.h"

@class NSMutableDictionary, NSString;

@interface GEOTileServer : GEOServer <GEOTileLoaderInternalDelegate>
{
    NSMutableDictionary *_pendingPeerToClientIdentifiers;	// 16 = 0x10
}

+ (_Bool)shouldStartImmediately;	// IMP=0x0000000100013c34
+ (id)identifier;	// IMP=0x0000000100013c28
- (void).cxx_destruct;	// IMP=0x0000000100036c50
- (void)tileLoader:(id)arg1 submittedTilesToNetwork:(id)arg2 forClient:(id)arg3;	// IMP=0x00000001000369ac
- (void)_receivedTile:(id)arg1 error:(id)arg2 info:(id)arg3 forKey:(const struct _GEOTileKey *)arg4 forPeer:(id)arg5;	// IMP=0x00000001000365c0
- (void)peerDidDisconnect:(id)arg1;	// IMP=0x00000001000362ac
- (void)peerDidConnect:(id)arg1;	// IMP=0x0000000100036214
- (void)endPreload:(id)arg1 fromPeer:(id)arg2;	// IMP=0x0000000100036150
- (void)beginPreload:(id)arg1 fromPeer:(id)arg2;	// IMP=0x0000000100036028
- (void)corrupt:(id)arg1 fromPeer:(id)arg2;	// IMP=0x0000000100035f10
- (void)_shrinkDB:(id)arg1 fromPeer:(id)arg2 synchronous:(_Bool)arg3;	// IMP=0x00000001000359f0
- (void)shrinkDBSync:(id)arg1 fromPeer:(id)arg2;	// IMP=0x00000001000359e0
- (void)shrinkDB:(id)arg1 fromPeer:(id)arg2;	// IMP=0x00000001000359d0
- (void)_canShrinkBySize:(id)arg1 fromPeer:(id)arg2 synchronous:(_Bool)arg3;	// IMP=0x00000001000357a4
- (void)canShrinkBySizeSync:(id)arg1 fromPeer:(id)arg2;	// IMP=0x0000000100035794
- (void)canShrinkBySize:(id)arg1 fromPeer:(id)arg2;	// IMP=0x0000000100035784
- (void)reprioritizeKey:(id)arg1 fromPeer:(id)arg2;	// IMP=0x00000001000355d4
- (void)cancel:(id)arg1 fromPeer:(id)arg2;	// IMP=0x00000001000351bc
- (void)loadTiles:(id)arg1 fromPeer:(id)arg2;	// IMP=0x0000000100032d60
- (void)_didDeleteExternalTileData:(id)arg1;	// IMP=0x0000000100032d50
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x0000000100032c04
- (id)init;	// IMP=0x0000000100032ab4
- (_Bool)handleIncomingMessage:(id)arg1 withObject:(id)arg2 fromPeer:(id)arg3;	// IMP=0x0000000100013c3c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

