//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface AccountAssistanceProgramMessage : SQLiteEntity
{
}

+ (id)_propertySettersForAssistanceProgramMessage;	// IMP=0x0000000100267ec0
+ (id)databaseTable;	// IMP=0x0000000100267eb4
+ (void)deleteAssistanceProgramMessagePID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x0000000100267e14
+ (id)_predicateForEventPID:(long long)arg1;	// IMP=0x0000000100267da0
+ (id)insertAssistanceProgramMessage:(id)arg1 forEventPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x0000000100267a08
+ (id)assistanceProgramMessagesWithEventPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00000001002677c4
- (id)assistanceProgramMessage;	// IMP=0x0000000100267c5c

@end

