//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface PassLocationSource : SQLiteEntity
{
}

+ (id)queryWithDatabase:(id)arg1 passPID:(unsigned long long)arg2 locationSourcePID:(unsigned long long)arg3;	// IMP=0x000000010029ea94
+ (id)queryWithDatabase:(id)arg1 locationSourcePID:(unsigned long long)arg2;	// IMP=0x000000010029e9cc
+ (id)queryWithDatabase:(id)arg1 passPID:(unsigned long long)arg2;	// IMP=0x000000010029e93c
+ (id)locationSourcePIDPredicate:(id)arg1;	// IMP=0x000000010029e91c
+ (id)passPIDPredicate:(unsigned long long)arg1;	// IMP=0x000000010029e8a8
+ (id)insertPassLocationSourceWithPass:(id)arg1 locationSource:(id)arg2 inDatabase:(id)arg3;	// IMP=0x000000010029e7e0
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x000000010029e648
+ (id)databaseTable;	// IMP=0x000000010029e63c
- (_Bool)deleteFromDatabase;	// IMP=0x000000010029ec28
- (id)initWithPassPID:(unsigned long long)arg1 locationSourcePID:(unsigned long long)arg2 inDatabase:(id)arg3;	// IMP=0x000000010029e6a0

@end

