//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface PaymentTransactionAuthentication : SQLiteEntity
{
}

+ (id)_predicateForPaymentTransactionPID:(long long)arg1;	// IMP=0x0000000100030998
+ (id)createIfNotExistInDatabase:(id)arg1 withPaymentTransactionPID:(long long)arg2;	// IMP=0x0000000100030438
+ (id)anyInDatabase:(id)arg1 withPaymentTransactionPID:(long long)arg2;	// IMP=0x00000001000303a8
+ (id)databaseTable;	// IMP=0x000000010003039c
- (_Bool)reset;	// IMP=0x0000000100030740
- (_Bool)updateAuthenticationComplete:(_Bool)arg1;	// IMP=0x00000001000306d8
- (_Bool)addDataCollectedAuthenticationMechanisms:(unsigned long long)arg1;	// IMP=0x0000000100030620
- (_Bool)addProcessedAuthenticationMechanisms:(unsigned long long)arg1;	// IMP=0x0000000100030568
- (_Bool)updateWithUserConfirmationData:(id)arg1;	// IMP=0x0000000100030554
- (_Bool)updateWithTransactionSignatureData:(id)arg1;	// IMP=0x0000000100030540
- (_Bool)updateWithPaymentPINData:(id)arg1;	// IMP=0x000000010003052c

@end

