//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface PDCloudStoreShareInvitationRequest : NSObject
{
    NSMutableArray *_completionHandlers;	// 8 = 0x8
    unsigned long long _type;	// 16 = 0x10
    NSString *_groupName;	// 24 = 0x18
    NSString *_suffix;	// 32 = 0x20
    long long _qualityOfService;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001000ef18c
@property(readonly, copy, nonatomic) NSArray *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
@property(nonatomic) long long qualityOfService; // @synthesize qualityOfService=_qualityOfService;
@property(copy, nonatomic) NSString *suffix; // @synthesize suffix=_suffix;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (_Bool)canCoalesceRequest:(id)arg1;	// IMP=0x00000001000ef10c
- (void)callCompletionsWithResponse:(id)arg1;	// IMP=0x00000001000eefbc
- (_Bool)coalesceWithRequest:(id)arg1;	// IMP=0x00000001000eeee8
- (id)initWithType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000eee28

@end

