//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PDCloudStoreContainerDelegate-Protocol.h"
#import "PDPushNotificationConsumer-Protocol.h"
#import "PDScheduledActivityClient-Protocol.h"
#import "PKCloudStoreCoordinatorDelegate-Protocol.h"
#import "PKSharingIDSManagerDelegate-Protocol.h"

@class NSHashTable, NSMutableArray, NSMutableOrderedSet, NSSet, NSString, PDApplePayCloudStoreContainer, PDCloudStoreShareInvitationRequest, PDPassCloudStoreContainer, PDPushNotificationManager, PKSharingIDSManager;

@interface PDCloudStoreNotificationCoordinator : NSObject <PDPushNotificationConsumer, PDCloudStoreContainerDelegate, PDScheduledActivityClient, PKSharingIDSManagerDelegate, PKCloudStoreCoordinatorDelegate>
{
    NSHashTable *_observers;	// 8 = 0x8
    PDPushNotificationManager *_pushNotificationManager;	// 16 = 0x10
    PKSharingIDSManager *_sharingIDSManger;	// 24 = 0x18
    struct os_unfair_lock_s _lock;	// 32 = 0x20
    PDPassCloudStoreContainer *_passContainer;	// 40 = 0x28
    PDApplePayCloudStoreContainer *_applePayContainer;	// 48 = 0x30
    NSSet *_pushTopics;	// 56 = 0x38
    NSMutableArray *_containers;	// 64 = 0x40
    PDCloudStoreShareInvitationRequest *_currentShareRequest;	// 72 = 0x48
    NSMutableOrderedSet *_shareRequests;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x000000010019853c
- (void)_unregisterForPushNotifications;	// IMP=0x0000000100198378
- (void)_registerForPushNotifications;	// IMP=0x00000001001982d8
- (id)_containerForItemType:(unsigned long long)arg1;	// IMP=0x000000010019826c
- (id)_errorWithCode:(long long)arg1 description:(id)arg2;	// IMP=0x000000010019815c
- (id)_containerWithIdentifier:(id)arg1;	// IMP=0x0000000100197f94
- (id)_containerWithZoneName:(id)arg1 scope:(long long)arg2;	// IMP=0x0000000100197c50
- (void)applyPushNotificationToken:(id)arg1;	// IMP=0x0000000100197b8c
- (void)_processCloudStorePushNotificationForContainer:(id)arg1 cloudStoreZone:(id)arg2 containerDatabse:(id)arg3;	// IMP=0x00000001001974f0
- (void)handlePushNotificationForTopic:(id)arg1 userInfo:(id)arg2;	// IMP=0x0000000100196f08
- (id)pushNotificationTopics;	// IMP=0x0000000100196f00
- (void)_unscheduleBackgroundContainerSetupActivities;	// IMP=0x0000000100196e50
- (_Bool)_shouldScheduleInitalCloudStoreContainerSetupBackgroundActivity;	// IMP=0x0000000100196df0
- (void)_scheduleFirstCloudStoreContainerSetupBackgroundActivityIfNeccessary;	// IMP=0x0000000100196cec
- (void)_recordAggdCloudStoreBackgroundContainerSetupResult:(_Bool)arg1 forCurrentBackgroundInterval:(unsigned long long)arg2;	// IMP=0x0000000100196c88
- (id)_backgroundActivityNameForBackgroundInterval:(unsigned long long)arg1;	// IMP=0x0000000100196c54
- (double)_nextTimeIntervalForBackgroundInterval:(unsigned long long)arg1;	// IMP=0x0000000100196bdc
- (void)_scheduleCloudStoreContainerSetupBackgroundActivityWithNextInterval:(unsigned long long)arg1;	// IMP=0x00000001001969ec
- (void)_performZoneShareIntegrityOperation;	// IMP=0x0000000100196794
- (void)_scheduleZoneShareIntegrityActivityForTimeInterval:(double)arg1;	// IMP=0x00000001001965bc
- (void)_syncTransactionsToCloudStoreOriginatedOnDevice:(unsigned long long)arg1;	// IMP=0x0000000100196330
- (void)scheduleTransactionDeviceDataSyncBackgroundActivityOriginatedOnDevice:(unsigned long long)arg1;	// IMP=0x0000000100196158
- (void)_performCloudStoreContainerInitalizationBackgroundActivityWithCurrentInterval:(unsigned long long)arg1 nextBackgroundInterval:(unsigned long long)arg2;	// IMP=0x0000000100196050
- (void)performScheduledActivityWithIdentifier:(id)arg1 activityCriteria:(id)arg2;	// IMP=0x0000000100195e48
- (void)noteAccountDeleted;	// IMP=0x0000000100195c78
- (void)noteCloudSyncPassesSwitchChanged;	// IMP=0x0000000100195990
- (void)resetApplePayManateeViewWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100195698
- (void)checkTLKsMissingWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001001953fc
- (void)didReceiveCloudStoreZoneInvitationStatus:(long long)arg1 forInvitation:(id)arg2 fromDestination:(id)arg3;	// IMP=0x0000000100194f50
- (void)removedFromCloudStoreZoneInvitation:(id)arg1 fromDestination:(id)arg2;	// IMP=0x0000000100194d00
- (void)didRequestCloudStoreZoneInvitationData:(id)arg1 fromDestination:(id)arg2;	// IMP=0x0000000100194b7c
- (void)didReceiveCloudStoreZoneInvitation:(id)arg1 invitationError:(id)arg2 fromDestination:(id)arg3;	// IMP=0x0000000100194838
- (void)unregisterObserver:(id)arg1;	// IMP=0x00000001001947dc
- (void)registerObserver:(id)arg1;	// IMP=0x0000000100194764
- (void)cloudStoreContainer:(id)arg1 requestsSyncTransactionsToCloudStoreOriginatedOnDevice:(unsigned long long)arg2;	// IMP=0x0000000100194624
- (void)cloudStoreContainer:(id)arg1 requestsZoneShareFromHandle:(id)arg2 zoneName:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00000001001943dc
- (void)cloudStoreContainer:(id)arg1 removeZoneShareInvitationForHandle:(id)arg2 zoneName:(id)arg3 qualitOfService:(long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00000001001941ac
- (void)cloudStoreContainer:(id)arg1 sendZoneShareInvitation:(id)arg2 recipientHandle:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100193f70
- (void)cloudStoreContainer:(id)arg1 sendZoneShareInvitationForHandle:(id)arg2 zoneName:(id)arg3 permission:(long long)arg4 qualitOfService:(long long)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x0000000100193bac
- (void)cloudStoreContainerShouldUnscheduleAllBackgroundActivities:(id)arg1;	// IMP=0x0000000100193b20
- (void)cloudStoreContainer:(id)arg1 didChangeContainerState:(unsigned long long)arg2;	// IMP=0x0000000100193ac4
- (void)cloudStoreContainer:(id)arg1 createdZoneWithName:(id)arg2 forContainerName:(id)arg3 scope:(long long)arg4;	// IMP=0x000000010019399c
- (void)recreateZone:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100193490
- (void)_shareRequest_bootstrapZoneRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001932cc
- (void)_shareRequest_requestKeysForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100193100
- (void)_shareRequest_shareForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100192e00
- (void)shareForZoneName:(id)arg1 containerName:(id)arg2 qualityOfService:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100192c1c
- (void)_shareRequest_declineInvitationForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001925a8
- (void)_declineInvitationForRecipientHandle:(id)arg1 zoneName:(id)arg2 containerName:(id)arg3 qualityOfService:(long long)arg4 shouldAlertRecipient:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x0000000100192370
- (void)declineInvitationForRecipientHandle:(id)arg1 zoneName:(id)arg2 containerName:(id)arg3 qualityOfService:(long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0000000100192290
- (void)_shareRequest_sendZoneShareInvitationWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100191fc8
- (void)_shareRequest_createShareInvitationForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100191cac
- (void)_shareRequest_validateRequestKeysWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100191658
- (void)_shareRequest_acceptShareInvitation:(id)arg1 qualityOfService:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001001913bc
- (void)_shareRequest_acceptShareInvitationWithRequestAndSendReponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100190ebc
- (void)_executeNextShareInvitationRequestIfPossible;	// IMP=0x00000001001905b4
- (void)_executeShareInvitationRequest:(id)arg1;	// IMP=0x00000001001902e0
- (void)itemOfItemType:(unsigned long long)arg1 recordName:(id)arg2 qualityOfService:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010019006c
- (void)removeAllItems:(unsigned long long)arg1 inZoneName:(id)arg2 containerName:(id)arg3 storeLocally:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010018fdf4
- (void)deleteZone:(id)arg1 containerName:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010018fba8
- (void)itemOfItemTypeFromAllZones:(unsigned long long)arg1 recordName:(id)arg2 qualityOfService:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010018f934
- (void)simulateCloudStorePushForContainerIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010018f638
- (void)resetContainerWithIdentifier:(id)arg1 zoneNames:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010018f45c
- (void)allItemsOfItemType:(unsigned long long)arg1 storeLocally:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010018f2f4
- (void)removeRecordWithRecordName:(id)arg1 zoneName:(id)arg2 containerName:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010018f064
- (void)removeItems:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010018edc0
- (void)updateCloudStoreWithLocalItemsWithConfigurations:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010018eac0
- (void)cloudStoreStatusWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010018e9a4
- (void)cloudStoreStatusForContainer:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010018e7ac
@property(retain, nonatomic) PDApplePayCloudStoreContainer *applePayContainer;
@property(retain, nonatomic) PDPassCloudStoreContainer *passContainer;
- (void)_initialCloudDatabaseSetupForContainer:(id)arg1 operationGroupNameSuffix:(id)arg2 shouldScheduleBackgroundActivity:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010018e034
- (void)_initialCloudDatabaseSetupForContainer:(id)arg1 operationGroupNameSuffix:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010018e020
- (void)setupCloudDatabaseForContainerName:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010018dfa0
- (id)initWithPushNotificationManager:(id)arg1 sharingIDSManger:(id)arg2;	// IMP=0x000000010018de1c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

