//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDCloudStoreShareInvitationRequest.h"

@class NSString;

@interface PDCloudStoreShareInvitationRequestGetShare : PDCloudStoreShareInvitationRequest
{
    NSString *_zoneName;	// 48 = 0x30
    NSString *_containerName;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001000f0b38
@property(readonly, copy, nonatomic) NSString *containerName; // @synthesize containerName=_containerName;
@property(readonly, copy, nonatomic) NSString *zoneName; // @synthesize zoneName=_zoneName;
- (id)description;	// IMP=0x00000001000f09ac
- (_Bool)canCoalesceRequest:(id)arg1;	// IMP=0x00000001000f08bc
- (id)initWithZoneName:(id)arg1 containerName:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000f07fc

@end

