//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PDAssertionObserver-Protocol.h"
#import "PDNFSecureXPCCarKeyEventObserver-Protocol.h"
#import "PDNFSecureXPCExpressTransactionEventObserver-Protocol.h"
#import "PDNFSecureXPCSecureElementEventObserver-Protocol.h"
#import "PDNotificationStreamConsumer-Protocol.h"
#import "PDScheduledActivityClient-Protocol.h"

@class NSDictionary, NSHashTable, NSSet, NSString, PDAppletSubcredentialManager, PDAssertionManager, PDDatabaseManager, PDNotificationStreamManager, PDRemoteInterfacePresenter, PKSecureElement;
@protocol OS_dispatch_queue;

@interface PDExpressPassManager : NSObject <PDNFSecureXPCSecureElementEventObserver, PDNFSecureXPCExpressTransactionEventObserver, PDNFSecureXPCCarKeyEventObserver, PDAssertionObserver, PDNotificationStreamConsumer, PDScheduledActivityClient>
{
    PDDatabaseManager *_databaseManager;	// 8 = 0x8
    PDAssertionManager *_assertionManager;	// 16 = 0x10
    PKSecureElement *_secureElement;	// 24 = 0x18
    PDRemoteInterfacePresenter *_remoteInterfacePresenter;	// 32 = 0x20
    PDNotificationStreamManager *_notificationStreamManager;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_accessQueue;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_replyQueue;	// 56 = 0x38
    _Bool _nfcRadioEnabled;	// 64 = 0x40
    _Bool _expressModesEnableable;	// 65 = 0x41
    _Bool _expressModesEnabled;	// 66 = 0x42
    _Bool _expressModesNeedUpdate;	// 67 = 0x43
    _Bool _contactlessInterfaceSuppressed;	// 68 = 0x44
    NSDictionary *_expressState;	// 72 = 0x48
    long long _outstandingExpressType;	// 80 = 0x50
    _Bool _outstandingExpressTypeProcessing;	// 88 = 0x58
    NSString *_outstandingExpressApplicationIdentifier;	// 96 = 0x60
    NSString *_outstandingPassUniqueIdentifier;	// 104 = 0x68
    NSSet *_outstandingExpressECP2TCIs;	// 112 = 0x70
    unsigned long long _lastReceivedExpressTransactionEvents;	// 120 = 0x78
    struct os_unfair_lock_s _observersLock;	// 128 = 0x80
    NSHashTable *_observers;	// 136 = 0x88
    PDAppletSubcredentialManager *_subcredentialManager;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x00000001000dd484
@property(retain, nonatomic) PDAppletSubcredentialManager *subcredentialManager; // @synthesize subcredentialManager=_subcredentialManager;
- (void)assertionManager:(id)arg1 didInvalidateAssertion:(id)arg2;	// IMP=0x00000001000dd3d8
- (void)assertionManager:(id)arg1 didAcquireAssertion:(id)arg2;	// IMP=0x00000001000dd340
- (void)_updateContactlessInterfaceSuppression:(id)arg1;	// IMP=0x00000001000dd1b0
- (_Bool)allowAcquisitionOfAssertionOfType:(unsigned long long)arg1;	// IMP=0x00000001000dd1a8
- (_Bool)interestedInAssertionOfType:(unsigned long long)arg1;	// IMP=0x00000001000dd188
- (void)handleNotificationWithName:(id)arg1 event:(id)arg2 forStream:(long long)arg3;	// IMP=0x00000001000dd174
- (id)createCurrentNotificationRegistrationState;	// IMP=0x00000001000dd16c
- (void)performScheduledActivityWithIdentifier:(id)arg1 activityCriteria:(id)arg2;	// IMP=0x00000001000dd168
- (void)_presentExpressRemoteAlert;	// IMP=0x00000001000dd040
- (void)receivedSecureExpressTransactionEvent:(id)arg1;	// IMP=0x00000001000dc440
- (void)carKeyDidUnlockWithAppletIdentifier:(id)arg1 keyIdentifier:(id)arg2;	// IMP=0x00000001000dc2bc
- (void)carKeyDidLockWithAppletIdentifier:(id)arg1 keyIdentifier:(id)arg2;	// IMP=0x00000001000dc138
- (void)secureElementRadioStateChanged;	// IMP=0x00000001000dc058
- (void)secureElementExpressConfigurationDidFail;	// IMP=0x00000001000dbfe0
- (void)secureElementDidRunScriptsFromTSM;	// IMP=0x00000001000dbf54
- (void)secureElementExpressConfigurationNeedsUpdate;	// IMP=0x00000001000dbec8
- (void)outstandingExpressTransactionStateWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000dbd7c
- (void)_accessObserversWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000dbb88
- (void)unregisterObserver:(id)arg1;	// IMP=0x00000001000dbb24
- (void)registerObserver:(id)arg1;	// IMP=0x00000001000dbac0
- (void)_adjustPasscodeLockoutTimerWithDelay:(double)arg1;	// IMP=0x00000001000db950
- (id)expressPassInformationWithAID:(id)arg1 keyIdentifier:(id)arg2;	// IMP=0x00000001000db708
- (void)_executeExpressMutationCompletions:(id)arg1;	// IMP=0x00000001000db104
- (void)_persistTargetExpressState:(id)arg1;	// IMP=0x00000001000daf50
- (void)_queueExpressMutationRequest:(id)arg1;	// IMP=0x00000001000daed0
- (void)resetExpressPasses;	// IMP=0x00000001000dadf4
- (void)removeExpressPassWithUniqueIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000dac2c
- (void)removeExpressPassesWithCardType:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000daa88
- (void)setExpressWithPassInformation:(id)arg1 credential:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000da55c
- (void)_conflictingExpressPassIdentifiersForPassInformation:(id)arg1 withState:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000da360
- (void)conflictingExpressPassIdentifiersForPassInformation:(id)arg1 withReferenceExpressState:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000da158
- (void)conflictingExpressPassIdentifiersForPassInformation:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000da080
- (void)expressPassesInformationWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000d9ea0
- (void)expressPassesInformationWithAutomaticSelectionTechnologyType:(long long)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d9a9c
- (void)expressPassesInformationWithCardType:(long long)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d9864
- (void)expressPassInformationWithPassUniqueIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d96cc
- (void)isPassExpressWithPassUniqueIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d9530
- (void)expressPassInformationForMode:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d9298
- (void)processPaymentApplicationsUpdateFromPriorPaymentApplications:(id)arg1 toPaymentApplications:(id)arg2 forPassUniqueIdentifier:(id)arg3;	// IMP=0x00000001000d89c0
- (void)sanitizeExpressPasses;	// IMP=0x00000001000d8934
- (void)stopExpressModes;	// IMP=0x00000001000d88c8
- (void)startExpressModes;	// IMP=0x00000001000d8844
- (id)initWithDatabaseManager:(id)arg1 assertionManager:(id)arg2 secureElement:(id)arg3 remoteInterfacePresenter:(id)arg4 notificationStreamManager:(id)arg5 isFirstUnlockedLaunchForBoot:(_Bool)arg6;	// IMP=0x00000001000d84e0
- (id)init;	// IMP=0x00000001000d84c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

