//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDGenericUserNotification.h"

#import "NSSecureCoding-Protocol.h"

@class NSDate;

@interface PDPassExpressModeEnabledUserNotification : PDGenericUserNotification <NSSecureCoding>
{
    unsigned long long _hideDisableAction;	// 120 = 0x78
    NSDate *_promoteEndDate;	// 128 = 0x80
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010015f478
- (void).cxx_destruct;	// IMP=0x000000010015f700
@property(readonly, nonatomic) NSDate *promoteEndDate; // @synthesize promoteEndDate=_promoteEndDate;
@property(readonly, nonatomic) unsigned long long hideDisableAction; // @synthesize hideDisableAction=_hideDisableAction;
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x000000010015f6a4
- (unsigned long long)notificationType;	// IMP=0x000000010015f660
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010015f588
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010015f480
- (_Bool)promotionActive;	// IMP=0x000000010015f408
- (id)initWithTitle:(id)arg1 message:(id)arg2 forPassUniqueIdentifier:(id)arg3;	// IMP=0x000000010015f3f4
- (id)initAsUnpromotedReplacementForNotification:(id)arg1;	// IMP=0x000000010015f288
- (id)initWithTitle:(id)arg1 message:(id)arg2 forPassUniqueIdentifier:(id)arg3 hideDisableAction:(unsigned long long)arg4 promoteDuration:(double)arg5;	// IMP=0x000000010015efa8

@end

