//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDWebServiceConnectionTask.h"

@class NSString;

@interface PDRegistrationTask : PDWebServiceConnectionTask
{
    NSString *_serialNumber;	// 16 = 0x10
    NSString *_authenticationToken;	// 24 = 0x18
    unsigned long long _requestedStatus;	// 32 = 0x20
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001001995e8
+ (id)_taskWithWebService:(id)arg1 serialNumber:(id)arg2 authToken:(id)arg3 requestedStatus:(unsigned long long)arg4;	// IMP=0x0000000100199458
+ (id)unregisterTaskWithWebService:(id)arg1 serialNumber:(id)arg2 authToken:(id)arg3;	// IMP=0x0000000100199448
+ (id)registerTaskWithWebService:(id)arg1 serialNumber:(id)arg2 authToken:(id)arg3;	// IMP=0x0000000100199438
- (void).cxx_destruct;	// IMP=0x000000010019a580
@property(nonatomic) unsigned long long requestedStatus; // @synthesize requestedStatus=_requestedStatus;
@property(retain, nonatomic) NSString *authenticationToken; // @synthesize authenticationToken=_authenticationToken;
@property(retain, nonatomic) NSString *serialNumber; // @synthesize serialNumber=_serialNumber;
- (_Bool)_matchesRegistrationTask:(id)arg1;	// IMP=0x000000010019a348
- (_Bool)_matchesPersonalizePassTask:(id)arg1;	// IMP=0x000000010019a178
- (long long)actionForActiveTask:(id)arg1;	// IMP=0x000000010019a08c
- (long long)actionForInactiveTask:(id)arg1;	// IMP=0x0000000100199fd8
- (_Bool)coalescesWithTaskSubclass:(Class)arg1;	// IMP=0x0000000100199f6c
- (id)description;	// IMP=0x0000000100199e00
- (void)handleError:(id)arg1;	// IMP=0x0000000100199dcc
- (void)handleResponse:(id)arg1 data:(id)arg2;	// IMP=0x0000000100199c6c
- (id)bodyDictionary;	// IMP=0x0000000100199bb4
- (id)headerFields;	// IMP=0x0000000100199b0c
- (id)endpointComponents;	// IMP=0x00000001001999c4
- (id)method;	// IMP=0x0000000100199990
- (_Bool)pertainsToPassTypeIdentifier:(id)arg1 serialNumber:(id)arg2;	// IMP=0x00000001001998ac
- (_Bool)isValid;	// IMP=0x00000001001997dc
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010019970c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001995f0
- (id)initWithWebService:(id)arg1 serialNumber:(id)arg2 authToken:(id)arg3 requestedStatus:(unsigned long long)arg4;	// IMP=0x00000001001994f8

@end

