//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface _TtC14amsengagementd12JSClientDemo : NSObject
{
}

@property(nonatomic, readonly) NSString *storeId;
@property(nonatomic, readonly) NSDictionary *options;
@property(nonatomic, readonly) _Bool inStoreDemoMode;
@property(nonatomic, readonly) long long deviceType;
- (id)init;	// IMP=0x000000010005db78

@end

