//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC14amsengagementd20NotificationObserver : NSObject
{
    MISSING_TYPE *queue;	// 8 = 0x8
}

+ (void)start;	// IMP=0x0000000100058130
- (void).cxx_destruct;	// IMP=0x000000010005a71c
- (void)handleNFCNotification:(id)arg1;	// IMP=0x000000010005a6e8
- (void)timezoneChanged;	// IMP=0x0000000100059994
- (id)init;	// IMP=0x0000000100058110

@end

