//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14amsengagementd16ActivitySchedule : _TtCs12_SwiftObject
{
    MISSING_TYPE *app;	// 0 = 0x0
    MISSING_TYPE *battery;	// 16 = 0x10
    MISSING_TYPE *dataClass;	// 17 = 0x11
    MISSING_TYPE *date;	// 1095786335 = 0x41505f5f
    MISSING_TYPE *dateIsAdaptive;	// 20306 = 0x4f52
    MISSING_TYPE *delay;	// 0 = 0x0
    MISSING_TYPE *events;	// 0 = 0x0
    MISSING_TYPE *identifier;	// 0 = 0x0
    MISSING_TYPE *grace;	// 0 = 0x0
    MISSING_TYPE *originalTimeZone;	// 0 = 0x0
    MISSING_TYPE *overwrite;	// 0 = 0x0
    MISSING_TYPE *type;	// 25 = 0x19
}

@end

