//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AMSHashable-Protocol.h"

@protocol AMSCloudDataRecordZoneIdentifier;

@protocol AMSCloudDataRecordZone <AMSHashable>
@property(readonly, nonatomic) id <AMSCloudDataRecordZoneIdentifier> identifier;
@property(readonly, nonatomic, getter=isDefaultRecordZone) _Bool defaultRecordZone;
@end

