//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface TASKNotifyAck : PBCodable <NSCopying>
{
}

- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100069060
- (unsigned long long)hash;	// IMP=0x0000000100069058
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100069004
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100068fcc
- (void)copyTo:(id)arg1;	// IMP=0x0000000100068fc8
- (void)writeTo:(id)arg1;	// IMP=0x0000000100068fc4
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100068fbc
- (id)dictionaryRepresentation;	// IMP=0x0000000100068e60
- (id)description;	// IMP=0x0000000100068dac

@end

