//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ADAnnouncementRequest.h"

@class NSString, UNNotification;

@interface ADAnnounceNotificationRequest : ADAnnouncementRequest
{
    UNNotification *_notification;	// 8 = 0x8
    NSString *_appID;	// 16 = 0x10
    long long _announcementType;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010004e0d0
@property(nonatomic) long long announcementType; // @synthesize announcementType=_announcementType;
@property(copy, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property(retain, nonatomic) UNNotification *notification; // @synthesize notification=_notification;
- (id)initWithNotification:(id)arg1 appID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010004df78

@end

