//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class ADRapportLink, AFPeerInfo, NSDictionary, NSString;

@protocol ADRapportLinkGenericMessageHandling
- (void)rapportLink:(ADRapportLink *)arg1 didReceiveMessage:(NSDictionary *)arg2 ofType:(NSString *)arg3 fromPeer:(AFPeerInfo *)arg4 completion:(void (^)(NSDictionary *, NSError *))arg5;
@end

