//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ADSession.h"

#import "ADSessionLocalConnectionDelegate-Protocol.h"

@class ADSessionLocalConnection, AFInstanceContext, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface ADSessionLocalServer : ADSession <ADSessionLocalConnectionDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    ADSessionLocalConnection *_serverConnection;	// 16 = 0x10
    struct __CFDictionary *_commandMap;	// 24 = 0x18
    _Bool _hasActiveRequest;	// 32 = 0x20
    double _requestStartTime;	// 40 = 0x28
    double _loadRetryStartTime;	// 48 = 0x30
    NSString *_sessionInitCommandId;	// 56 = 0x38
    AFInstanceContext *_instanceContext;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001002b2f84
- (void)_sendAssistantDataChangedSinceAnchor:(id)arg1 refId:(id)arg2;	// IMP=0x00000001002b2d54
- (void)siriConnection:(id)arg1 didEncounterError:(id)arg2;	// IMP=0x00000001002b2c30
- (void)siriConnectionDidClose:(id)arg1;	// IMP=0x00000001002b2b3c
- (void)siriConnection:(id)arg1 didReceiveAceObject:(id)arg2;	// IMP=0x00000001002b2a1c
- (void)siriConnection:(id)arg1 didOpenWithConnectionType:(id)arg2 delay:(double)arg3;	// IMP=0x00000001002b2908
- (void)siriConnection:(id)arg1 willStartWithConnectionType:(id)arg2;	// IMP=0x00000001002b28ac
- (_Bool)_shouldRetry;	// IMP=0x00000001002b2800
- (void)_sendLoadAssistant;	// IMP=0x00000001002b23a8
- (void)_sendServerCommands:(id)arg1;	// IMP=0x00000001002b2288
- (void)_sendServerCommand:(id)arg1;	// IMP=0x00000001002b1e00
- (void)sendCommand:(id)arg1;	// IMP=0x00000001002b1cec
- (void)_handleAceObject:(id)arg1;	// IMP=0x00000001002b1ae4
- (void)_saCommandIgnored:(id)arg1;	// IMP=0x00000001002b1ad4
- (void)_saSetConnectionHeader:(id)arg1;	// IMP=0x00000001002b1ad0
- (void)_saAssistantLoaded:(id)arg1;	// IMP=0x00000001002b1824
- (void)_saCommandFailed:(id)arg1;	// IMP=0x00000001002b1598
- (void)_assistantFailedForReason:(id)arg1 error:(id)arg2;	// IMP=0x00000001002b14b0
- (void)_saAssistantNotReady:(id)arg1;	// IMP=0x00000001002b11c0
- (_Bool)sessionIsActive;	// IMP=0x00000001002b116c
- (void)setHasActiveRequest:(_Bool)arg1;	// IMP=0x00000001002b0ffc
- (void)_resetServerConnectionSynchronously:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001002b0ed4
- (void)barrier:(CDUnknownBlockType)arg1;	// IMP=0x00000001002b0ebc
- (void)_startSession;	// IMP=0x00000001002b0db8
- (void)_startConnection;	// IMP=0x00000001002b0d00
- (_Bool)supportsSync;	// IMP=0x00000001002b0cf8
- (void)dealloc;	// IMP=0x00000001002b0c70
- (id)initOnQueue:(id)arg1 withAccount:(id)arg2 languageCode:(id)arg3 connectionMode:(id)arg4 sharedUserIdentifier:(id)arg5 loggingSharedUserIdentifier:(id)arg6 instanceContext:(id)arg7;	// IMP=0x00000001002b0a2c

@end

