//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AssistantServices/AFDeviceContext.h>

#import "NSMutableCopying-Protocol.h"

@interface AFDeviceContext (MutableCopy) <NSMutableCopying>
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100134be8
@end

