//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SAIntentGroupLaunchAppWithIntent.h>

@interface SAIntentGroupLaunchAppWithIntent (DeviceRouting)
- (id)ad_executionDeviceForDeviceContexts:(id)arg1 proximityMap:(id)arg2 localDeviceIsFollower:(_Bool)arg3;	// IMP=0x000000010005ff8c
- (_Bool)ad_requiresProximityInformation;	// IMP=0x000000010005ff3c
@end

