//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SASStartSpeechRequest.h>

@interface SASStartSpeechRequest (ADSAExtensions)
- (void)ad_setADRecordingInfo:(id)arg1;	// IMP=0x00000001002b7b3c
- (void)ad_setAFSpeechRequestOptions:(id)arg1;	// IMP=0x00000001002b7a5c
@end

