//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface OperationState : NSObject
{
    _Bool _operationCancelled;	// 8 = 0x8
    int _operationRefcount;	// 12 = 0xc
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000042c4
@property int operationRefcount; // @synthesize operationRefcount=_operationRefcount;
@property _Bool operationCancelled; // @synthesize operationCancelled=_operationCancelled;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)end;	// IMP=0x0000000100004164
- (_Bool)begin;	// IMP=0x000000010000401c
- (void)cancel;	// IMP=0x0000000100003f8c
- (_Bool)cancelled;	// IMP=0x0000000100003e60
- (id)init;	// IMP=0x0000000100003df8

@end

