//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UNUserNotificationCenterDelegate-Protocol.h"

@class NSString, UNUserNotificationCenter;
@protocol ANNotificationProviderDelegate;

@interface ANNotificationProvider : NSObject <UNUserNotificationCenterDelegate>
{
    id <ANNotificationProviderDelegate> _delegate;	// 8 = 0x8
    UNUserNotificationCenter *_notificationCenter;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100007128
@property(retain, nonatomic) UNUserNotificationCenter *notificationCenter; // @synthesize notificationCenter=_notificationCenter;
@property __weak id <ANNotificationProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100006f80
- (void)deliveredNotifications:(CDUnknownBlockType)arg1;	// IMP=0x0000000100006e2c
- (void)removeNotificationWithIdentifier:(id)arg1;	// IMP=0x0000000100006cb4
- (id)_notificationContent:(id)arg1;	// IMP=0x0000000100006ae4
- (void)postNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100006858
- (id)init;	// IMP=0x00000001000067bc
- (id)initForSectionWithID:(id)arg1;	// IMP=0x00000001000067b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

