//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMSession.h"

@class NEDNSSettings, NSArray, NSObject, NWMonitor;
@protocol OS_os_transaction;

@interface NESMDNSSettingsSession : NESMSession
{
    _Bool _configurationUpdatePending;	// 8 = 0x8
    NEDNSSettings *_settings;	// 16 = 0x10
    NSArray *_onDemandRules;	// 24 = 0x18
    NSArray *_exceptionDomains;	// 32 = 0x20
    NWMonitor *_dnsOnDemandMonitor;	// 40 = 0x28
    NSObject<OS_os_transaction> *_transaction;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010007cb8c
@property _Bool configurationUpdatePending; // @synthesize configurationUpdatePending=_configurationUpdatePending;
@property(retain) NSObject<OS_os_transaction> *transaction; // @synthesize transaction=_transaction;
@property(retain) NWMonitor *dnsOnDemandMonitor; // @synthesize dnsOnDemandMonitor=_dnsOnDemandMonitor;
@property(retain) NSArray *exceptionDomains; // @synthesize exceptionDomains=_exceptionDomains;
@property(retain) NSArray *onDemandRules; // @synthesize onDemandRules=_onDemandRules;
@property(retain) NEDNSSettings *settings; // @synthesize settings=_settings;
- (void)updatePolicies:(_Bool)arg1 agent:(_Bool)arg2;	// IMP=0x000000010007c774
- (void)dealloc;	// IMP=0x000000010007c718
- (void)uninstall;	// IMP=0x000000010007c5bc
- (void)install;	// IMP=0x000000010007c48c
- (void)handleNetworkDetectionNotification:(int)arg1;	// IMP=0x000000010007c2e8
- (_Bool)handleUpdateConfiguration:(id)arg1;	// IMP=0x000000010007c180
- (void)handleStopMessageWithReason:(int)arg1;	// IMP=0x000000010007c078
- (void)handleStartMessage:(id)arg1;	// IMP=0x000000010007bf84
- (void)installOrWaitForOnDemand;	// IMP=0x000000010007bee8
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010007b8bc
- (void)teardownOnDemandMonitor;	// IMP=0x000000010007b764
- (void)setupOnDemandMonitor;	// IMP=0x000000010007b464
- (id)copyNetworkDescriptionsForOnDemand;	// IMP=0x000000010007b058
- (_Bool)shouldBeIdleForStatus:(int)arg1;	// IMP=0x000000010007b03c
- (int)type;	// IMP=0x000000010007b034
- (id)initWithConfiguration:(id)arg1 andServer:(id)arg2;	// IMP=0x000000010007ad5c
- (void)updateOnDemandRulesForConfiguration:(id)arg1;	// IMP=0x000000010007ad58

@end

