//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP19appstorecomponentsd29JSClientOrderingObjectExports_-Protocol.h"

@interface _TtC19appstorecomponentsd22JSClientOrderingObject : NSObject <_TtP19appstorecomponentsd29JSClientOrderingObjectExports_>
{
}

- (void)visibilityForIAPs:(id)arg1:(id)arg2;	// IMP=0x00000001000297e4
- (void)orderedVisibleIAPs:(id)arg1:(id)arg2:(id)arg3:(id)arg4:(id)arg5;	// IMP=0x000000010002960c
- (id)init;	// IMP=0x00000001000295a4

@end

