//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class AWDCountersNetworkS, AWDCountersRadioS, AWDHeaderInfoS;

@interface AWDFlagstoneNetworkRadioMetrics : PBCodable <NSCopying>
{
    unsigned long long _timestamp;	// 8 = 0x8
    AWDHeaderInfoS *_header;	// 16 = 0x10
    AWDCountersNetworkS *_sCntrsNetwork;	// 24 = 0x18
    AWDCountersRadioS *_sCntrsRadio;	// 32 = 0x20
    CDStruct_b5306035 _has;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100077e3c
@property(retain, nonatomic) AWDCountersRadioS *sCntrsRadio; // @synthesize sCntrsRadio=_sCntrsRadio;
@property(retain, nonatomic) AWDCountersNetworkS *sCntrsNetwork; // @synthesize sCntrsNetwork=_sCntrsNetwork;
@property(retain, nonatomic) AWDHeaderInfoS *header; // @synthesize header=_header;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100077cc0
- (unsigned long long)hash;	// IMP=0x0000000100077c08
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100077adc
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000779d8
- (void)copyTo:(id)arg1;	// IMP=0x0000000100077920
- (void)writeTo:(id)arg1;	// IMP=0x0000000100077878
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100077870
- (id)dictionaryRepresentation;	// IMP=0x00000001000773bc
- (id)description;	// IMP=0x0000000100077308
@property(readonly, nonatomic) _Bool hasSCntrsRadio;
@property(readonly, nonatomic) _Bool hasSCntrsNetwork;
@property(readonly, nonatomic) _Bool hasHeader;
@property(nonatomic) _Bool hasTimestamp;

@end

