//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "INFamilyEventPushHandler.h"

@interface INChildTransferRequestPushHandler : INFamilyEventPushHandler
{
}

- (id)createActivationURLForPushEventWithDetails:(id)arg1;	// IMP=0x0000000100005f58
- (_Bool)isValidResponse:(id)arg1;	// IMP=0x0000000100005e64

@end

