/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, April 28, 2021 at 9:09:50 PM Mountain Standard Time
                       * Operating System: Version 14.5 (Build 18L204)
                       * Image Source: /usr/lib/libMobileGestaltExtensions.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol MobileGestaltHelper;
@class NSXPCConnection;

@interface MobileGestaltHelperProxy : NSObject {

	int _error;
	id<MobileGestaltHelper> _helper;
	NSXPCConnection* _connection;

}

@property (assign) int error;                                     //@synthesize error=_error - In the implementation block
@property (readonly) id<MobileGestaltHelper> helper;              //@synthesize helper=_helper - In the implementation block
@property (readonly) NSXPCConnection * connection;                //@synthesize connection=_connection - In the implementation block
+(id)proxy;
-(id)init;
-(void)dealloc;
-(void)invalidate;
-(int)error;
-(void)setError:(int)arg1 ;
-(NSXPCConnection *)connection;
-(id<MobileGestaltHelper>)helper;
-(BOOL)proxyRebuildCache;
@end

