//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ComponentControl.h"

#import "tGraphDataSource-Protocol.h"

@interface AudioAmpCC : ComponentControl <tGraphDataSource>
{
    float _targetPower;	// 128 = 0x80
    float _currentPower;	// 132 = 0x84
    float _maxAudioAmpPower;	// 136 = 0x88
}

- (struct __CFString *)copyFieldCurrentValueForIndex:(int)arg1;	// IMP=0x00000001000188b0
- (struct __CFString *)copyHeaderForIndex:(int)arg1;	// IMP=0x0000000100018800
- (int)numberOfFields;	// IMP=0x00000001000187c8
- (void)refreshTGraphTelemetry;	// IMP=0x00000001000186a8
- (void)defaultAction;	// IMP=0x00000001000184cc
- (id)initWithParams:(struct __CFDictionary *)arg1;	// IMP=0x00000001000183d8

@end

