//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CommonProduct.h"

@interface tmb5031c5e2c3e9dacdbb3933ec2bdc993 : CommonProduct
{
}

- (void)updateCoreAnalyticsInfo;	// IMP=0x000000010002c380
- (void)updateAggdInfo;	// IMP=0x000000010002c37c
- (id)newBacklightComponentController:(struct __CFDictionary *)arg1;	// IMP=0x000000010002c348
- (void)updateAllThermalLoad:(_Bool)arg1;	// IMP=0x000000010002c188

@end

