//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_PBWallpaperSceneView.h"

@interface _PBSuspensionSnapshotView : _PBWallpaperSceneView
{
    CDUnknownBlockType _snapshotLoadRequestBuilder;	// 48 = 0x30
}

+ (_Bool)isWallpaperRequired;	// IMP=0x000000010021a684
- (void).cxx_destruct;	// IMP=0x000000010021ac9c
@property(copy, nonatomic) CDUnknownBlockType snapshotLoadRequestBuilder; // @synthesize snapshotLoadRequestBuilder=_snapshotLoadRequestBuilder;
- (id)_newSnapshotView;	// IMP=0x000000010021a83c
- (void)didMoveToWindow;	// IMP=0x000000010021a6d4
- (id)contentViewToAnimateToOnInterfaceChange;	// IMP=0x000000010021a6a0

@end

