//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewLayout.h>

@class NSDictionary, NSIndexPath;

@interface PBAppSwitcherFullFocusLayout : UICollectionViewLayout
{
    NSIndexPath *_originIndexPath;	// 8 = 0x8
    NSDictionary *_computedAttributes;	// 16 = 0x10
    struct CGSize _focusableCellSize;	// 24 = 0x18
}

+ (Class)layoutAttributesClass;	// IMP=0x00000001000e84a8
- (void).cxx_destruct;	// IMP=0x00000001000e9090
@property(readonly, nonatomic) struct CGSize focusableCellSize; // @synthesize focusableCellSize=_focusableCellSize;
@property(copy, nonatomic) NSDictionary *computedAttributes; // @synthesize computedAttributes=_computedAttributes;
@property(copy, nonatomic) NSIndexPath *originIndexPath; // @synthesize originIndexPath=_originIndexPath;
- (void)prepareLayout;	// IMP=0x00000001000e8988
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000e8904
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x00000001000e88b8
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;	// IMP=0x00000001000e8718
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;	// IMP=0x00000001000e86b8
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x00000001000e868c
- (struct CGSize)collectionViewContentSize;	// IMP=0x00000001000e8578
- (id)init;	// IMP=0x00000001000e8398

@end

