//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ITIdleTimerStateServiceDelegate-Protocol.h"
#import "PBOpenAppTransitionerObserver-Protocol.h"
#import "PBPowerManagerObserver-Protocol.h"
#import "PBSceneManagerObserver-Protocol.h"

@class NSString;

@interface PBAttentionMonitor : NSObject <PBPowerManagerObserver, PBSceneManagerObserver, PBOpenAppTransitionerObserver, ITIdleTimerStateServiceDelegate>
{
}

+ (id)acquireIdleTimerAssertionWithConfiguration:(id)arg1 fromClient:(id)arg2 forReason:(id)arg3;	// IMP=0x0000000100019ca4
+ (void)appTransitioner:(id)arg1 willStartAnimationForAppTransition:(id)arg2;	// IMP=0x0000000100019a00
+ (void)sceneManager:(id)arg1 didChangeHiliteStateForScene:(id)arg2;	// IMP=0x000000010001979c
+ (void)sceneManager:(id)arg1 didChangeIdleTimerStateForScene:(id)arg2;	// IMP=0x0000000100019658
+ (void)sceneManager:(id)arg1 didChangeFocusFromScene:(id)arg2 toScene:(id)arg3;	// IMP=0x00000001000195a0
+ (void)powerManagerDidWakeSystem:(id)arg1;	// IMP=0x0000000100019188
+ (void)powerManager:(id)arg1 willWakeSystemWithReason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100019084
+ (void)powerManagerDidSleepSystem:(id)arg1;	// IMP=0x0000000100018fc4
+ (void)powerManager:(id)arg1 willSleepSystemWithReason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100018d6c
+ (_Bool)powerManagerAllowSystemToSleep:(id)arg1;	// IMP=0x0000000100018d18
+ (id)afterIdleInterval:(double)arg1 reason:(id)arg2 queue:(id)arg3 perform:(CDUnknownBlockType)arg4;	// IMP=0x0000000100018c3c
+ (id)afterIdleInterval:(double)arg1 reason:(id)arg2 queue:(id)arg3 perform:(CDUnknownBlockType)arg4 invalidationHandler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100018b38
+ (id)makeIdleAction:(double)arg1 reason:(id)arg2 queue:(id)arg3 perform:(CDUnknownBlockType)arg4 invalidationHandler:(CDUnknownBlockType)arg5;	// IMP=0x00000001000184a8
+ (_Bool)_isAttentionEventForVolume:(id)arg1;	// IMP=0x0000000100018390
+ (id)_activeApplicationScene;	// IMP=0x00000001000182b8
+ (_Bool)_focusedSceneHasHiliteModeEnabled;	// IMP=0x00000001000181f8
+ (_Bool)_focusedSceneWantsIdleDisabled;	// IMP=0x0000000100018138
+ (void)_temporarilySuppressWakeForHIDEvents;	// IMP=0x0000000100018044
+ (void)_noteConditionsMayHaveChanged:(id)arg1;	// IMP=0x0000000100017f1c
+ (void)_noteATimeoutChanged:(id)arg1;	// IMP=0x0000000100017db0
+ (unsigned long long)_countOutstandingHighPriorityIdleAssertions;	// IMP=0x0000000100017c2c
+ (_Bool)_assertionIsHighPriority:(id)arg1;	// IMP=0x0000000100017b98
+ (_Bool)_hasOutstandingIdleAssertionsThatPreventSleep;	// IMP=0x0000000100017b64
+ (_Bool)_hasOutstandingIdleAssertionsThatPreventScreenSaver;	// IMP=0x0000000100017b30
+ (_Bool)_hasOutstandingIdleAssertionsThatPreventCRD;	// IMP=0x0000000100017afc
+ (_Bool)_hasOutstandingIdleAssertionsThatPreventNowPlaying;	// IMP=0x0000000100017ac8
+ (_Bool)_hasOutstandingIdleAssertions;	// IMP=0x0000000100017a84
+ (void)resetAttention:(id)arg1;	// IMP=0x00000001000177b0
+ (void)__attentionRegained:(id)arg1;	// IMP=0x00000001000173d4
+ (void)__reactToSomethingChanged:(id)arg1;	// IMP=0x000000010001719c
+ (void)__whackAttentionAwareness;	// IMP=0x0000000100016ef4
+ (void)__setupAttentionAwarenessForSleep;	// IMP=0x0000000100016488
+ (void)__setupAttentionAwareness;	// IMP=0x0000000100015a80
+ (void)__configureStateMachineTimeOffsets;	// IMP=0x00000001000152bc
+ (void)initialize;	// IMP=0x0000000100013c64
- (id)acquireIdleTimerAssertionWithConfiguration:(id)arg1 fromClient:(id)arg2 forReason:(id)arg3;	// IMP=0x0000000100019b5c
- (void)appTransitioner:(id)arg1 willStartAnimationForAppTransition:(id)arg2;	// IMP=0x00000001000198e0
- (void)sceneManager:(id)arg1 didChangeHiliteStateForScene:(id)arg2;	// IMP=0x0000000100019480
- (void)sceneManager:(id)arg1 didChangeIdleTimerStateForScene:(id)arg2;	// IMP=0x0000000100019360
- (void)sceneManager:(id)arg1 didChangeFocusFromScene:(id)arg2 toScene:(id)arg3;	// IMP=0x0000000100019220

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

