//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults;

@interface PBKeyboardPreferenceObserver : NSObject
{
    NSUserDefaults *_uikitDefaults;	// 8 = 0x8
    long long _resolvedKeyboardStyle;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x000000010012e1a0
- (void).cxx_destruct;	// IMP=0x000000010012ec3c
@property(readonly, nonatomic) long long resolvedKeyboardStyle; // @synthesize resolvedKeyboardStyle=_resolvedKeyboardStyle;
@property(readonly, nonatomic) NSUserDefaults *uikitDefaults; // @synthesize uikitDefaults=_uikitDefaults;
- (void)_handlePreferredKeyboardUpdate;	// IMP=0x000000010012e5d0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010012e454
- (void)dealloc;	// IMP=0x000000010012e3e4
- (id)init;	// IMP=0x000000010012e29c

@end

