//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBInstanceDependable-Protocol.h"
#import "PBSystemOverlayControllerDelegate-Protocol.h"
#import "PBSystemOverlayUIProvider-Protocol.h"
#import "PBSystemUIManaging-Protocol.h"

@class NSString, PBSystemOverlayController;

@interface PBRestrictionPINManager : NSObject <PBSystemOverlayUIProvider, PBSystemOverlayControllerDelegate, PBSystemUIManaging, PBInstanceDependable>
{
    _Bool _shouldRestoreConferenceRoomDisplay;	// 8 = 0x8
    PBSystemOverlayController *_overlayController;	// 16 = 0x10
    CDUnknownBlockType _pinRestrictionResultBlock;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010002e450
+ (id)dependencyDescription;	// IMP=0x000000010002e2c4
- (void).cxx_destruct;	// IMP=0x000000010002f14c
@property(readonly, nonatomic) _Bool shouldRestoreConferenceRoomDisplay; // @synthesize shouldRestoreConferenceRoomDisplay=_shouldRestoreConferenceRoomDisplay;
@property(readonly, nonatomic) CDUnknownBlockType pinRestrictionResultBlock; // @synthesize pinRestrictionResultBlock=_pinRestrictionResultBlock;
@property(readonly, nonatomic) PBSystemOverlayController *overlayController; // @synthesize overlayController=_overlayController;
- (void)overlayController:(id)arg1 didCancelSession:(id)arg2 withContext:(id)arg3;	// IMP=0x000000010002f00c
- (void)overlayController:(id)arg1 didDismissSession:(id)arg2;	// IMP=0x000000010002ef50
- (void)overlayController:(id)arg1 willDismissSession:(id)arg2 withContext:(id)arg3;	// IMP=0x000000010002ed9c
- (void)prepareUIForSystemOverlayPresentationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010002ea40
- (_Bool)dismiss;	// IMP=0x000000010002e928
- (void)presentWithResultBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010002e7e4
@property(readonly, nonatomic, getter=isPresenting) _Bool presenting;
- (id)init;	// IMP=0x000000010002e54c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

