//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBSRestrictionServiceInterface-Protocol.h"

@class NSString, PBSystemServiceConnection;

@interface PBRestrictionService : NSObject <PBSRestrictionServiceInterface>
{
    PBSystemServiceConnection *_remoteConnection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000dce04
@property(readonly, nonatomic) __weak PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (id)_getDefaultServiceRequestWithResultHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000dccf4
- (void)validatePIN:(id)arg1 withResult:(CDUnknownBlockType)arg2;	// IMP=0x00000001000dc9d0
- (void)authorizeRestrictionsWithResult:(CDUnknownBlockType)arg1;	// IMP=0x00000001000dc91c
- (void)restrictionsEnabledWithResult:(CDUnknownBlockType)arg1;	// IMP=0x00000001000dc868
- (void)cancelRestrictionAuthorization:(id)arg1;	// IMP=0x00000001000dc7e4
- (void)validateRestrictionForSetting:(unsigned long long)arg1 allowInteraction:(_Bool)arg2 requestToken:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x00000001000dc6b0
- (void)validateRestrictionForContentType:(unsigned long long)arg1 withRating:(id)arg2 allowInteraction:(_Bool)arg3 requestToken:(id)arg4 withCompletion:(CDUnknownBlockType)arg5;	// IMP=0x00000001000dc538
- (void)invalidate;	// IMP=0x00000001000dc524
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x00000001000dc450
- (id)init;	// IMP=0x00000001000dc418

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

