//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBInstanceDependable-Protocol.h"
#import "PBOpenAppTransitionerObserver-Protocol.h"
#import "PBScreenSaverManagerObserver-Protocol.h"
#import "PBSystemOverlayControllerDelegate-Protocol.h"
#import "PBSystemOverlayUIProvider-Protocol.h"
#import "PBSystemUIManaging-Protocol.h"

@class NSHashTable, NSString, PBSystemOverlayController, UIViewController;

@interface PBRoutingUIManager : NSObject <PBSystemOverlayUIProvider, PBSystemOverlayControllerDelegate, PBScreenSaverManagerObserver, PBOpenAppTransitionerObserver, PBInstanceDependable, PBSystemUIManaging>
{
    NSHashTable *_pendingDismissalHandlers;	// 8 = 0x8
    UIViewController *_routingViewController;	// 16 = 0x10
    PBSystemOverlayController *_overlayController;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x0000000100214bec
+ (id)dependencyDescription;	// IMP=0x0000000100214a2c
- (void).cxx_destruct;	// IMP=0x0000000100215d4c
@property(readonly, nonatomic) PBSystemOverlayController *overlayController; // @synthesize overlayController=_overlayController;
@property(retain, nonatomic) UIViewController *routingViewController; // @synthesize routingViewController=_routingViewController;
@property(readonly, nonatomic) NSHashTable *pendingDismissalHandlers; // @synthesize pendingDismissalHandlers=_pendingDismissalHandlers;
- (void)screenSaverManagerDidPresentScreenSaver:(id)arg1;	// IMP=0x0000000100215bb0
- (void)overlayController:(id)arg1 didDismissSession:(id)arg2;	// IMP=0x0000000100215b04
- (void)overlayController:(id)arg1 didPresentSession:(id)arg2;	// IMP=0x0000000100215a58
- (void)appTransitioner:(id)arg1 willBeginAppTransition:(id)arg2;	// IMP=0x00000001002158d8
- (void)prepareUIForSystemOverlayPresentationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100215590
- (_Bool)dismissRoutingUI;	// IMP=0x0000000100215268
- (void)activateRoutingUIForReason:(unsigned long long)arg1 options:(id)arg2 dismissalHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001002150b8
@property(readonly, nonatomic, getter=isPresenting) _Bool presenting;
- (void)dealloc;	// IMP=0x0000000100215000
- (id)init;	// IMP=0x0000000100214ce8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

