//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MRAVBufferedInputStream, MRDExternalDeviceServerClientConnection, MRIDSOutputStream, NSDate, NSString;

@interface MRDIDSRemoteControlServiceConnection : NSObject
{
    _Bool _hasReceivedRemoteControlMessage;	// 8 = 0x8
    NSString *_destination;	// 16 = 0x10
    MRAVBufferedInputStream *_inputStream;	// 24 = 0x18
    MRIDSOutputStream *_outputStream;	// 32 = 0x20
    MRDExternalDeviceServerClientConnection *_connection;	// 40 = 0x28
    NSDate *_connectionAttemptDate;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100040fa4
@property(retain, nonatomic) NSDate *connectionAttemptDate; // @synthesize connectionAttemptDate=_connectionAttemptDate;
@property(nonatomic) _Bool hasReceivedRemoteControlMessage; // @synthesize hasReceivedRemoteControlMessage=_hasReceivedRemoteControlMessage;
@property(retain, nonatomic) MRDExternalDeviceServerClientConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) MRIDSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain, nonatomic) MRAVBufferedInputStream *inputStream; // @synthesize inputStream=_inputStream;
@property(retain, nonatomic) NSString *destination; // @synthesize destination=_destination;

@end

