//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VOSOutputEventDispatching-Protocol.h"
#import "VOSOutputEventHandler-Protocol.h"

@class AXAccessQueue, AXAccessQueueTimer, AXDialectMap, AXIndexMap, AXMOutputManager, NSArray, NSDate, NSHashTable, NSLock, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, SCRCThreadKey, VOTOutputRequest, VOTOutputRequestRunner;
@protocol OS_dispatch_queue;

@interface VOTOutputManager : NSObject <VOSOutputEventHandler, VOSOutputEventDispatching>
{
    NSMutableArray *_queuedOutputRequests;	// 8 = 0x8
    NSMutableArray *_requestRunners;	// 16 = 0x10
    AXIndexMap *_components;	// 24 = 0x18
    VOTOutputRequest *_currentlyRunningUninterruptableRequest;	// 32 = 0x20
    NSMutableArray *_currentlyRunningRequests;	// 40 = 0x28
    unsigned int _numberOfRequestSinceLastUninterruptable;	// 48 = 0x30
    double _cachedRate;	// 56 = 0x38
    _Bool _shutdown;	// 64 = 0x40
    VOTOutputRequestRunner *_onHoldRunner;	// 72 = 0x48
    AXDialectMap *_supportedLanguageMap;	// 80 = 0x50
    struct VOTExternalRoutingInfo _currentExternalRoutingInfo;	// 88 = 0x58
    _Bool _externalRoutesAvailable;	// 104 = 0x68
    _Bool _externalRoutesContainHDMIRoute;	// 105 = 0x69
    _Bool _selectedRouteIsHDMI;	// 106 = 0x6a
    AXAccessQueueTimer *_inactivateAudioTimer;	// 112 = 0x70
    AXAccessQueue *_audioSessionQueue;	// 120 = 0x78
    NSMutableSet *_audioSessionUsers;	// 128 = 0x80
    SCRCThreadKey *_threadKey;	// 136 = 0x88
    NSHashTable *_outputManagerObservers;	// 144 = 0x90
    NSLock *_outputManagerObserversLock;	// 152 = 0x98
    AXMOutputManager *_axmOutputManager;	// 160 = 0xa0
    NSMutableDictionary *_vosEventHandlers;	// 168 = 0xa8
    NSMutableDictionary *_vosEventStartedHandlers;	// 176 = 0xb0
    struct os_unfair_lock_s _queueLock;	// 184 = 0xb8
    NSObject<OS_dispatch_queue> *_avAccessQueue;	// 192 = 0xc0
    _Bool _audioSessionActive;	// 200 = 0xc8
    CDUnknownBlockType _airTunesRouteIsAirPlayingTestingBlock;	// 208 = 0xd0
    NSDate *_dateToResumeRequests;	// 216 = 0xd8
    NSDate *_dateToResumeSounds;	// 224 = 0xe0
    NSString *_currentRouteName;	// 232 = 0xe8
}

+ (void)logSoundPlayed:(id)arg1;	// IMP=0x0000000100012ee0
+ (void)clearPreviousSoundsPlayed;	// IMP=0x0000000100012b44
+ (id)previousSoundsPlayed;	// IMP=0x0000000100012aec
+ (id)outputManager;	// IMP=0x000000010000ea50
+ (id)outputManagerIfExists;	// IMP=0x000000010000ea44
+ (void)initialize;	// IMP=0x000000010000e31c
- (void).cxx_destruct;	// IMP=0x0000000100013ac0
@property(readonly, nonatomic) _Bool audioSessionActive; // @synthesize audioSessionActive=_audioSessionActive;
@property(retain) NSString *currentRouteName; // @synthesize currentRouteName=_currentRouteName;
@property(retain, nonatomic) NSDate *dateToResumeSounds; // @synthesize dateToResumeSounds=_dateToResumeSounds;
@property(retain, nonatomic) NSDate *dateToResumeRequests; // @synthesize dateToResumeRequests=_dateToResumeRequests;
@property(copy, nonatomic) CDUnknownBlockType airTunesRouteIsAirPlayingTestingBlock; // @synthesize airTunesRouteIsAirPlayingTestingBlock=_airTunesRouteIsAirPlayingTestingBlock;
@property(readonly, nonatomic) AXAccessQueue *audioSessionQueue; // @synthesize audioSessionQueue=_audioSessionQueue;
- (void)_notifyObserversOutputManagerWillProcessNextRequest:(id)arg1;	// IMP=0x00000001000138e4
- (void)_notifyObserversOutputManagerDidFinishProcessingQueuedRequests;	// IMP=0x0000000100013780
- (void)removeAllOutputManagerObservers;	// IMP=0x0000000100013738
- (void)removeOutputManagerObserver:(id)arg1;	// IMP=0x00000001000136c0
- (void)addOutputManagerObserver:(id)arg1;	// IMP=0x0000000100013648
- (void)dispatcher:(id)arg1 handleEvent:(id)arg2 soundPack:(id)arg3 hapticPack:(id)arg4;	// IMP=0x0000000100013238
- (void)removeVOSEventStartedHandler:(id)arg1;	// IMP=0x0000000100013228
- (void)removeVOSEventFinishedHandler:(id)arg1;	// IMP=0x0000000100013218
- (void)addVOSEventStartedHandler:(CDUnknownBlockType)arg1 forIdentifier:(id)arg2;	// IMP=0x000000010001316c
- (void)addVOSEventFinishedHandler:(CDUnknownBlockType)arg1 forIdentifier:(id)arg2;	// IMP=0x00000001000130c0
- (void)sendEvent:(id)arg1;	// IMP=0x0000000100012ffc
- (_Bool)replacesCharacterAsPunctuation:(unsigned short)arg1;	// IMP=0x0000000100012fa8
- (void)playSoundFast:(id)arg1;	// IMP=0x0000000100012f98
- (void)playSoundFast:(id)arg1 startedBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100012ba4
- (void)playSoundFast:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100012b90
- (void)speakSimpleString:(id)arg1 braille:(_Bool)arg2 language:(id)arg3;	// IMP=0x0000000100012a28
- (void)speakSimpleString:(id)arg1;	// IMP=0x0000000100012a14
- (void)disableAudioSession:(id)arg1 userDelay:(double)arg2;	// IMP=0x0000000100012400
- (void)disableAudioSession:(id)arg1;	// IMP=0x00000001000123f0
- (void)removeAllAudioSessionEnablers;	// IMP=0x00000001000121dc
- (void)enableAudioSession:(id)arg1;	// IMP=0x0000000100011fc8
- (void)toggleAudioSessionActive:(_Bool)arg1;	// IMP=0x0000000100011e44
- (void)silenceOutputForTimeInterval:(double)arg1;	// IMP=0x0000000100011d60
- (void)_silenceRequestsForTimeInterval:(id)arg1;	// IMP=0x0000000100011ca4
- (void)_resumeCurrentRequest;	// IMP=0x0000000100011c48
- (void)resumeCurrentRequest;	// IMP=0x0000000100011bd0
- (void)_holdCurrentRequest;	// IMP=0x0000000100011b18
- (void)holdCurrentRequest;	// IMP=0x0000000100011af0
- (_Bool)isSpeaking;	// IMP=0x0000000100011aa4
- (_Bool)isPaused;	// IMP=0x0000000100011a58
- (void)stopSpeakingAtBoundary:(int)arg1 allRequests:(_Bool)arg2 sessionDeactivationDelay:(id)arg3;	// IMP=0x00000001000119d4
- (void)stopSpeakingAtBoundary:(int)arg1;	// IMP=0x00000001000119c0
- (void)continueSpeaking;	// IMP=0x0000000100011980
- (void)pauseSpeakingAtBoundary:(int)arg1;	// IMP=0x0000000100011938
- (void)setRate:(float)arg1;	// IMP=0x00000001000118e8
- (float)speechRate;	// IMP=0x00000001000118dc
- (void)resetSpeechRate;	// IMP=0x000000010001189c
- (float)defaultSpeechRate;	// IMP=0x00000001000117d4
- (float)speechRateForLanguage:(id)arg1;	// IMP=0x0000000100011584
- (void)setSpeechRate:(float)arg1 forLanguage:(id)arg2;	// IMP=0x0000000100011478
- (void)setVolume:(float)arg1;	// IMP=0x000000010001144c
- (void)_setVolume:(float)arg1;	// IMP=0x0000000100011194
- (void)updateAudioSessionProperties;	// IMP=0x0000000100011150
- (void)updateWithCurrentRoute;	// IMP=0x00000001000110c8
- (void)selectAudioRoute:(_Bool)arg1;	// IMP=0x0000000100010bac
- (void)selectLocalAudioRoute;	// IMP=0x0000000100010b9c
- (void)selectExternalAudioRoute;	// IMP=0x0000000100010b8c
- (_Bool)externalAudioRouteSelected;	// IMP=0x0000000100010788
- (_Bool)isRouteAirplayMirroring;	// IMP=0x0000000100010754
- (_Bool)selectedRouteIsHDMI;	// IMP=0x000000010001074c
- (_Bool)externalAudioRoutesContainHDMIRoute;	// IMP=0x0000000100010744
- (_Bool)externalAudioRoutesAvailable;	// IMP=0x000000010001073c
- (void)_updateExternalRoutesAvailable;	// IMP=0x000000010001048c
- (void)_updateActiveRoutes;	// IMP=0x0000000100010048
- (void)_activeRouteChanged:(id)arg1;	// IMP=0x000000010000ffe0
- (void)callStatusChanged;	// IMP=0x000000010000ff34
- (_Bool)isWirelessRoutePicked:(id)arg1;	// IMP=0x000000010000fec8
- (_Bool)isRouteWireless:(id)arg1;	// IMP=0x000000010000fe60
- (_Bool)isRoutePicked:(id)arg1;	// IMP=0x000000010000fd98
- (_Bool)isAirPodsRoute:(id)arg1;	// IMP=0x000000010000fd0c
- (_Bool)isCurrentRouteConsideredExternal:(id)arg1;	// IMP=0x000000010000fd04
- (_Bool)_isRouteExternalHDMIRoute:(id)arg1;	// IMP=0x000000010000fca0
- (_Bool)airTunesRouteIsAirPlaying;	// IMP=0x000000010000fbbc
- (id)speechComponent;	// IMP=0x000000010000fbac
- (double)volume;	// IMP=0x000000010000fb58
- (_Bool)isSystemMuted;	// IMP=0x000000010000fad0
- (void)toggleSystemMute;	// IMP=0x000000010000fa34
- (void)synchVolumeWithSystem;	// IMP=0x000000010000fa2c
- (void)_systemVolumeDidChange:(id)arg1;	// IMP=0x000000010000fa28
- (float)systemVolume;	// IMP=0x000000010000f9b4
- (void)setSystemVolume:(float)arg1;	// IMP=0x000000010000f924
- (id)componentForType:(int)arg1;	// IMP=0x000000010000f910
- (void)finishedOutputRequest:(id)arg1;	// IMP=0x000000010000f834
- (void)_dispatchNextQueuedRequest;	// IMP=0x000000010000f5a4
- (void)_handleProcessRequest:(id)arg1;	// IMP=0x000000010000f0a0
- (void)shutdown;	// IMP=0x000000010000f02c
- (void)_handleRequestFinished:(id)arg1;	// IMP=0x000000010000edb8
- (void)clearQueue;	// IMP=0x000000010000ed34
- (id)currentLanguageMap;	// IMP=0x000000010000ed2c
- (void)updateSupportedLanguageMap;	// IMP=0x000000010000ec58
- (void)handleEvent:(id)arg1;	// IMP=0x000000010000eb14
@property(readonly, nonatomic) NSArray *queuedRequests;
- (void)_voiceOverVolumeChanged:(id)arg1;	// IMP=0x000000010000eac8
- (void)dealloc;	// IMP=0x000000010000e994
- (id)init;	// IMP=0x000000010000e3a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

