//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BLBookInstallOperationProgressDelegate-Protocol.h"
#import "NSFetchedResultsControllerDelegate-Protocol.h"

@class BLDatabaseManager, BLMediaLibraryManager, NSArray, NSFetchedResultsController, NSMutableDictionary, NSOperationQueue, NSString;
@protocol BLBookInstallManagerProgressDelegate, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface BLBookInstallManager : NSObject <NSFetchedResultsControllerDelegate, BLBookInstallOperationProgressDelegate>
{
    id <BLBookInstallManagerProgressDelegate> _progressDelegate;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    BLDatabaseManager *_databaseManager;	// 24 = 0x18
    BLMediaLibraryManager *_mediaLibraryManager;	// 32 = 0x20
    NSFetchedResultsController *_frc;	// 40 = 0x28
    NSOperationQueue *_queue;	// 48 = 0x30
    NSMutableDictionary *_operationsByDownloadID;	// 56 = 0x38
    NSArray *_pendingInterruptedInstalls;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x000000010004a70c
@property(retain, nonatomic) NSArray *pendingInterruptedInstalls; // @synthesize pendingInterruptedInstalls=_pendingInterruptedInstalls;
@property(retain, nonatomic) NSMutableDictionary *operationsByDownloadID; // @synthesize operationsByDownloadID=_operationsByDownloadID;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSFetchedResultsController *frc; // @synthesize frc=_frc;
@property(nonatomic) __weak BLMediaLibraryManager *mediaLibraryManager; // @synthesize mediaLibraryManager=_mediaLibraryManager;
@property(nonatomic) __weak BLDatabaseManager *databaseManager; // @synthesize databaseManager=_databaseManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(nonatomic) __weak id <BLBookInstallManagerProgressDelegate> progressDelegate; // @synthesize progressDelegate=_progressDelegate;
- (void)dq_notifyServerOfDownloadCancelledForInstallOperation:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100049c90
- (void)dq_notifyServerOfDownloadCompleteForInstallOperation:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100049468
- (void)dq_completeOperationForDownloadID:(id)arg1;	// IMP=0x0000000100048c50
- (void)dq_failOperationForDownloadID:(id)arg1;	// IMP=0x0000000100048928
- (_Bool)_assetAlreadyStartedTheInstallationStage:(long long)arg1;	// IMP=0x0000000100048904
- (void)dq_dequeueOperationForDownloadID:(id)arg1 downloadState:(long long)arg2;	// IMP=0x000000010004861c
- (void)dq_enqueueInstall:(id)arg1;	// IMP=0x0000000100047fc8
- (void)mq_installDownloadInfo:(id)arg1;	// IMP=0x00000001000477c4
- (void)operation:(id)arg1 updatedProgress:(id)arg2 forInstall:(id)arg3;	// IMP=0x0000000100047614
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;	// IMP=0x0000000100047424
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x00000001000473b8
- (void)controllerWillChangeContent:(id)arg1;	// IMP=0x000000010004734c
- (void)restartInterruptedInstalls:(CDUnknownBlockType)arg1;	// IMP=0x0000000100047000
- (void)cancelInstallWithDownloadID:(id)arg1;	// IMP=0x0000000100046f34
- (void)start;	// IMP=0x0000000100046d80
- (void)dealloc;	// IMP=0x0000000100046d2c
- (id)initWithDatabaseManager:(id)arg1 mediaLibraryManager:(id)arg2;	// IMP=0x00000001000469b4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

