//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BLDownloadDataConsumer.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface BLFilesystemDownloadDataConsumer : BLDownloadDataConsumer
{
    long long _bytesWritten;	// 8 = 0x8
    int _fd;	// 16 = 0x10
    _Bool _hasConsumedData;	// 20 = 0x14
    NSArray *_hashes;	// 24 = 0x18
    struct CC_MD5state_st _md5Context;	// 32 = 0x20
    long long _numberOfBytesToHash;	// 128 = 0x80
    NSString *_path;	// 136 = 0x88
    unsigned long long _resumptionOffset;	// 144 = 0x90
    long long _verifiedBytes;	// 152 = 0x98
}

- (void).cxx_destruct;	// IMP=0x000000010006d994
- (unsigned long long)resumptionOffset;	// IMP=0x000000010006d984
- (_Bool)hasConsumedData;	// IMP=0x000000010006d974
- (void)_truncateToSize:(long long)arg1;	// IMP=0x000000010006d8f8
- (_Bool)_openFile;	// IMP=0x000000010006d684
- (_Bool)_hashAndWriteData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010006d45c
- (_Bool)_checkHashForByteCount:(long long)arg1;	// IMP=0x000000010006d238
- (void)truncate;	// IMP=0x000000010006d194
- (void)suspend;	// IMP=0x000000010006d0c0
- (void)reset;	// IMP=0x000000010006cfcc
- (_Bool)finish:(id *)arg1;	// IMP=0x000000010006cd6c
- (unsigned long long)diskUsage;	// IMP=0x000000010006cd5c
- (_Bool)consumeData:(id)arg1 error:(id *)arg2;	// IMP=0x000000010006cbb4
- (void)dealloc;	// IMP=0x000000010006cb5c
- (id)initWithPath:(id)arg1 MD5Hashes:(id)arg2 numberOfBytesToHash:(long long)arg3;	// IMP=0x000000010006ca44

@end

