//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BLOperation.h"

@class NSURLRequest;
@protocol BLUIHostServiceProtocol;

__attribute__((visibility("hidden")))
@interface BLLoadExternalDownloadManifestOperation : BLOperation
{
    NSURLRequest *_urlRequest;	// 80 = 0x50
    CDUnknownBlockType _downloadBlock;	// 88 = 0x58
    id <BLUIHostServiceProtocol> _uiHostProxy;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x000000010006b7e0
@property(retain, nonatomic) id <BLUIHostServiceProtocol> uiHostProxy; // @synthesize uiHostProxy=_uiHostProxy;
@property(copy, nonatomic) CDUnknownBlockType downloadBlock; // @synthesize downloadBlock=_downloadBlock;
- (_Bool)_runForPurchaseFormatWithURLRequest:(id)arg1 error:(id *)arg2;	// IMP=0x000000010006b4d4
- (void)run;	// IMP=0x000000010006b264
- (id)URLRequest;	// IMP=0x000000010006b214
- (id)initWithRequest:(id)arg1 uiHostProxy:(id)arg2 downloadBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010006b0e8

@end

