//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP13SiriInference25SiriInferenceXPCInterface_-Protocol.h"

@interface _TtC14siriinferenced20SiriInferenceService : NSObject <_TtP13SiriInference25SiriInferenceXPCInterface_>
{
}

- (id)init;	// IMP=0x0000000100007988
- (void)waitForBackgroundJobsToFinishWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010000790c
- (void)overrideDBForIntegrationTestsWithUrl:(id)arg1;	// IMP=0x0000000100007864
- (void)backfillSiriRemembersWithDatabasePath:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000077d4
- (void)saveToSiriRemembersWithInteraction:(id)arg1 databasePath:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100007724
- (void)logCoreAnalyticsMetricWithMetricsData:(id)arg1;	// IMP=0x00000001000076e4
- (void)searchSiriRemembersV0WithQuery:(id)arg1 type:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000075e8

@end

