//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BTBluetoothPairingSession, BTShareAudioService, CNContact, CUBluetoothDevice, NSString, SDStatusMonitor, SFClient, SFDevice, SFDeviceDiscovery, SFService, SFSession;
@protocol OS_dispatch_queue;

@interface BTShareAudioSessionDaemon : NSObject
{
    SFService *_bleNearbyActionAdvertiser;	// 8 = 0x8
    SFDeviceDiscovery *_bleNearbyInfoScanner;	// 16 = 0x10
    SFDeviceDiscovery *_bleProxPairingScanner;	// 24 = 0x18
    _Bool _configRequestReceived;	// 32 = 0x20
    CDUnknownBlockType _configResponseHandler;	// 40 = 0x28
    _Bool _connectRequestReceived;	// 48 = 0x30
    CDUnknownBlockType _connectResponseHandler;	// 56 = 0x38
    _Bool _confirmPermanent;	// 64 = 0x40
    int _confirmState;	// 68 = 0x44
    NSString *_guestDeviceAddress;	// 72 = 0x48
    NSString *_guestHeadphonesAddress;	// 80 = 0x50
    unsigned int _guestHeadphonesColorCode;	// 88 = 0x58
    int _guestHeadphonesConnectState;	// 92 = 0x5c
    NSString *_guestHeadphonesName;	// 96 = 0x60
    BTBluetoothPairingSession *_guestHeadphonesPairingSession;	// 104 = 0x68
    unsigned int _guestHeadphonesProductID;	// 112 = 0x70
    NSString *_guestHeadphonesRouteUID;	// 120 = 0x78
    int _guestHeadphonesInstructionsState;	// 128 = 0x80
    int _guestiOSConnectState;	// 132 = 0x84
    CNContact *_guestiOSContact;	// 136 = 0x88
    NSString *_guestiOSDeviceAddress;	// 144 = 0x90
    int _guestiOSPairSetupPublicState;	// 152 = 0x98
    SFSession *_guestiOSSession;	// 160 = 0xa0
    int _guestiOSShareAudioState;	// 168 = 0xa8
    int _guestiOSShareAudioConnectState;	// 172 = 0xac
    int _guestiOSWaitForRouteState;	// 176 = 0xb0
    _Bool _initialized;	// 180 = 0xb4
    _Bool _invalidateCalled;	// 181 = 0xb5
    _Bool _invalidateDone;	// 182 = 0xb6
    _Bool _observingPickableRoutes;	// 183 = 0xb7
    SFClient *_preventProxCardsClient;	// 184 = 0xb8
    BTShareAudioService *_shareAudioService;	// 192 = 0xc0
    SFDevice *_triggeredDevice;	// 200 = 0xc8
    SFDevice *_triggeredNeedsSetupDevice;	// 208 = 0xd0
    _Bool _triggerediOS;	// 216 = 0xd8
    _Bool _prefHeadphoneTrigger;	// 217 = 0xd9
    _Bool _prefiOSTrigger;	// 218 = 0xda
    int _prefOverrideColorCode;	// 220 = 0xdc
    int _prefOverrideProductID;	// 224 = 0xe0
    _Bool _prefRespectDeviceSupport;	// 228 = 0xe4
    int _prefRSSIThreshold;	// 232 = 0xe8
    int _mode;	// 236 = 0xec
    SFDevice *_darwinDevice;	// 240 = 0xf0
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 248 = 0xf8
    CDUnknownBlockType _progressHandler;	// 256 = 0x100
    SDStatusMonitor *_statusMonitor;	// 264 = 0x108
    CUBluetoothDevice *_wxDevice;	// 272 = 0x110
}

- (void).cxx_destruct;	// IMP=0x000000010004a9f4
@property(retain, nonatomic) CUBluetoothDevice *wxDevice; // @synthesize wxDevice=_wxDevice;
@property(retain, nonatomic) SDStatusMonitor *statusMonitor; // @synthesize statusMonitor=_statusMonitor;
@property(copy, nonatomic) CDUnknownBlockType progressHandler; // @synthesize progressHandler=_progressHandler;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(retain, nonatomic) SFDevice *darwinDevice; // @synthesize darwinDevice=_darwinDevice;
- (void)userConfirmed:(_Bool)arg1;	// IMP=0x000000010004a818
- (void)_reportProgressTriggeredDevice:(int)arg1;	// IMP=0x000000010004a62c
- (void)_reportProgress:(int)arg1 info:(id)arg2;	// IMP=0x000000010004a428
- (void)_reportProgress:(int)arg1;	// IMP=0x000000010004a240
- (void)_reportError:(id)arg1;	// IMP=0x000000010004a114
- (void)_pickableRoutesChanged;	// IMP=0x0000000100049ea0
- (void)_pickableRoutesChanged:(id)arg1;	// IMP=0x0000000100049dd0
- (void)_bleScannerProxPairingDeviceFound:(id)arg1;	// IMP=0x000000010004962c
- (void)_bleScannerNearbyInfoDeviceFound:(id)arg1;	// IMP=0x00000001000493f8
- (void)_cleanup;	// IMP=0x000000010004912c
- (int)_runFinish;	// IMP=0x0000000100048eac
- (int)_runWaitForGuestHeadphones;	// IMP=0x0000000100048d0c
- (int)_runConnectGuestHeadphones;	// IMP=0x0000000100048900
- (int)_runWaitForGuestHeadphonesPairingMode;	// IMP=0x00000001000488ec
- (int)_runShowHeadphonesPairingInstructions;	// IMP=0x0000000100048844
- (void)_runGuestiOSShareAudioConnectProcessResponse:(id)arg1 error:(id)arg2;	// IMP=0x0000000100048708
- (void)_runGuestiOSShareAudioConnectSendRequest;	// IMP=0x00000001000485e4
- (int)_runGuestiOSShareAudioConnect;	// IMP=0x0000000100048534
- (void)_runGuestiOSShareAudioProcessResponse:(id)arg1 error:(id)arg2;	// IMP=0x0000000100048094
- (void)_runGuestiOSShareAudioSendRequest;	// IMP=0x0000000100047c30
- (int)_runGuestiOSShareAudio;	// IMP=0x0000000100047b80
- (int)_runGuestiOSPairSetupPublic;	// IMP=0x00000001000478c0
- (int)_runGuestiOSConnect;	// IMP=0x00000001000471f8
- (int)_runConfirm;	// IMP=0x00000001000470ac
- (int)_runWaitForConnectRequest;	// IMP=0x0000000100047098
- (int)_runWaitForProxTrigger;	// IMP=0x0000000100047084
- (int)_runWaitForConfigRequestOrProxTrigger;	// IMP=0x0000000100047060
- (int)_runAdvertiser;	// IMP=0x0000000100046d34
- (void)_runShareAudioServiceConnectRequest:(id)arg1 responseHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100046c5c
- (void)_runShareAudioServiceConfigResponse:(CDUnknownBlockType)arg1;	// IMP=0x00000001000469a8
- (void)_runShareAudioServiceConfigRequest:(id)arg1 responseHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010004660c
- (int)_runShareAudioServiceStart;	// IMP=0x0000000100046330
- (int)_runScannerNearbyInfo;	// IMP=0x0000000100045f84
- (int)_runScannerProxPairing;	// IMP=0x0000000100045bc4
- (int)_runInit;	// IMP=0x00000001000459ec
- (void)_runStory6TV;	// IMP=0x0000000100045840
- (void)_runStory6iOS;	// IMP=0x0000000100045754
- (void)_runDefault;	// IMP=0x0000000100045568
- (void)_run;	// IMP=0x0000000100045534
- (void)_invalidate;	// IMP=0x0000000100045494
- (void)invalidate;	// IMP=0x00000001000453a0
- (void)activate;	// IMP=0x0000000100045288
- (id)init;	// IMP=0x0000000100045220

@end

