//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AXRuntime/AXElement.h>

#import "SCATElement-Protocol.h"
#import "SCATElementAutoscrolling-Protocol.h"

@class AXElementGroup, NSArray, NSNumber, NSString, SCATAuxiliaryElementManager;
@protocol SCATElementAutoscrolling;

@interface AXElement (UsefulLogging) <SCATElement, SCATElementAutoscrolling>
- (id)elemLog;	// IMP=0x000000010002d5e4
- (void)scatUpdateValue;	// IMP=0x000000010009e724
- (void)scatScrollToTop;	// IMP=0x000000010009e718
- (void)scatDecreaseAutoscrollSpeed;	// IMP=0x000000010009e70c
- (void)scatIncreaseAutoscrollSpeed;	// IMP=0x000000010009e700
@property(readonly, nonatomic) _Bool scatIsAutoscrolling;
- (void)scatPauseAutoscrolling;	// IMP=0x000000010009e6e8
- (void)scatAutoscrollInDirection:(unsigned long long)arg1;	// IMP=0x000000010009e6dc
@property(retain, nonatomic) id <SCATElementAutoscrolling> scatAutoscrollTarget;
@property(readonly, nonatomic) _Bool scatUpdatesMenu;
@property(readonly, nonatomic) _Bool scatBeginScanningFromSelfAfterActivation;
@property(readonly, nonatomic) _Bool scatIsOnScreen;
@property(readonly, nonatomic) _Bool scatHidesGroupCursorWhenFocused;
@property(readonly, nonatomic) SCATAuxiliaryElementManager *scatAuxiliaryElementManager;
@property(readonly, nonatomic) _Bool scatIsAuxiliaryElement;
@property(readonly, nonatomic) _Bool scatIsMemberOfGroup;
- (_Bool)scatPerformAction:(int)arg1 withValue:(id)arg2;	// IMP=0x000000010009e4d0
- (_Bool)scatPerformAction:(int)arg1;	// IMP=0x000000010009e4c4
@property(readonly, nonatomic) NSArray *scatDrops;
@property(readonly, nonatomic) NSArray *scatDrags;
@property(readonly, nonatomic) int scatPid;
@property(readonly, nonatomic) NSArray *scatCustomActions;
- (id)scatSupportedGestures;	// IMP=0x000000010009e488
- (_Bool)scatSupportsAction:(int)arg1;	// IMP=0x000000010009e380
- (_Bool)scatCanScrollInAtLeastOneDirection;	// IMP=0x000000010009e374
- (void)scatScrollToVisible;	// IMP=0x000000010009e368
@property(readonly, nonatomic) NSArray *scatAlternateKeys;
@property(readonly, nonatomic) _Bool scatCanShowAlternateKeys;
@property(readonly, nonatomic) _Bool scatIsKeyboardKey;
@property(nonatomic) _Bool scatAssistiveTechFocused;
@property(readonly, nonatomic) NSNumber *scatOverrideCursorTheme;
@property(readonly, nonatomic) NSString *scatSpeakableDescription;
@property(readonly, nonatomic) long long scatActivateBehavior;
@property(readonly, nonatomic) _Bool scatShouldActivateDirectly;
@property(readonly, nonatomic) _Bool scatShouldAllowDeferFocusToNativeFocusedElement;
@property(readonly, nonatomic) _Bool scatIndicatesOwnFocus;
@property(readonly, nonatomic) _Bool scatIsAXElement;
@property(readonly, nonatomic) _Bool scatIsValid;
@property(readonly, nonatomic) unsigned long long scatScanningBehaviorTraits;
@property(readonly, nonatomic) unsigned long long scatTraits;
@property(readonly, nonatomic) struct CGRect scatTextCursorFrame;
@property(readonly, nonatomic) struct CGPath *scatPath;
@property(readonly, nonatomic) _Bool scatPathIsInSceneReferenceSpace;
@property(readonly, nonatomic) struct CGPoint scatScreenPointForOperations;
@property(readonly, nonatomic) struct CGRect scatFrame;
@property(readonly, nonatomic) struct CGPoint scatCenterPoint;
- (id)scrollableElement;	// IMP=0x000000010009dab4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) struct CGRect frame; // @dynamic frame;
@property(readonly) unsigned long long hash;
@property(nonatomic) AXElementGroup *parentGroup; // @dynamic parentGroup;
@property(readonly) Class superclass;
@end

