//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSArray.h>

#import "SCATElementProvider-Protocol.h"

@class NSString;

@interface SCATStaticElementProvider : NSArray <SCATElementProvider>
{
    NSArray *_elements;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000aa724
@property(retain, nonatomic) NSArray *elements; // @synthesize elements=_elements;
- (_Bool)containsElement:(id)arg1;	// IMP=0x00000001000aa688
- (void)didFinishProvidingElements;	// IMP=0x00000001000aa684
- (void)willBeginProvidingElements;	// IMP=0x00000001000aa680
- (id)elementBefore:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x00000001000aa5e8
- (id)elementAfter:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x00000001000aa554
- (id)lastElementWithOptions:(int *)arg1;	// IMP=0x00000001000aa510
- (id)firstElementWithOptions:(int *)arg1;	// IMP=0x00000001000aa4c8
- (long long)numberOfElements;	// IMP=0x00000001000aa4bc
@property(readonly, nonatomic) _Bool providesElements;
- (id)objectAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000aa458
- (unsigned long long)count;	// IMP=0x00000001000aa40c
@property(readonly, copy) NSString *description;
- (id)initWithElements:(id)arg1;	// IMP=0x00000001000aa2ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

