//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CloudServicesError : NSObject
{
}

+ (id)errorForNSError:(id)arg1 path:(id)arg2 format:(id)arg3;	// IMP=0x0000000100054924
+ (id)errorWithDomain:(id)arg1 code:(long long)arg2 format:(id)arg3;	// IMP=0x0000000100054828
+ (id)errorWithCode:(long long)arg1 error:(id)arg2 URL:(id)arg3 format:(id)arg4;	// IMP=0x00000001000546e4
+ (id)errorWithCode:(long long)arg1 URL:(id)arg2 format:(id)arg3;	// IMP=0x00000001000545d0
+ (id)errorWithCode:(long long)arg1 error:(id)arg2 format:(id)arg3;	// IMP=0x00000001000544bc
+ (id)errorWithCode:(long long)arg1 format:(id)arg2;	// IMP=0x00000001000543d0
+ (id)sanitizedError:(id)arg1;	// IMP=0x00000001000542d0
+ (long long)codeForErrno:(long long)arg1;	// IMP=0x00000001000541f4
+ (long long)codeForNSError:(id)arg1;	// IMP=0x0000000100053fa8

@end

