//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class SecureBackupTermsInfo;

@interface StoredTermsInfo : PBCodable <NSCopying>
{
    unsigned long long _storageVersion;	// 8 = 0x8
    SecureBackupTermsInfo *_termsInfo;	// 16 = 0x10
    struct {
        unsigned int storageVersion:1;
    } _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010001bb34
@property(retain, nonatomic) SecureBackupTermsInfo *termsInfo; // @synthesize termsInfo=_termsInfo;
@property(nonatomic) unsigned long long storageVersion; // @synthesize storageVersion=_storageVersion;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010001ba70
- (unsigned long long)hash;	// IMP=0x000000010001ba0c
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010001b934
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010001b88c
- (void)copyTo:(id)arg1;	// IMP=0x000000010001b814
- (void)writeTo:(id)arg1;	// IMP=0x000000010001b7a4
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010001b79c
- (id)dictionaryRepresentation;	// IMP=0x000000010001b404
- (id)description;	// IMP=0x000000010001b350
@property(readonly, nonatomic) _Bool hasTermsInfo;
@property(nonatomic) _Bool hasStorageVersion;

@end

