//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCProfileServiceServer;
@protocol OS_dispatch_queue;

@interface MCBackgroundActivityManager : NSObject
{
    int _profileChangeNotificationToken;	// 8 = 0x8
    int _managedAppChangeNotificationToken;	// 12 = 0xc
    int _passcodeChangedNotificationToken;	// 16 = 0x10
    int _passcodePolicyChangedNotificationToken;	// 20 = 0x14
    MCProfileServiceServer *_server;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_workQueue;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010001b674
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(nonatomic) int passcodePolicyChangedNotificationToken; // @synthesize passcodePolicyChangedNotificationToken=_passcodePolicyChangedNotificationToken;
@property(nonatomic) int passcodeChangedNotificationToken; // @synthesize passcodeChangedNotificationToken=_passcodeChangedNotificationToken;
@property(nonatomic) int managedAppChangeNotificationToken; // @synthesize managedAppChangeNotificationToken=_managedAppChangeNotificationToken;
@property(nonatomic) int profileChangeNotificationToken; // @synthesize profileChangeNotificationToken=_profileChangeNotificationToken;
@property(nonatomic) __weak MCProfileServiceServer *server; // @synthesize server=_server;
- (void)_workQueueReschedule:(long long)arg1 startDate:(id)arg2 gracePeriod:(id)arg3 priority:(const char *)arg4 repeatingInterval:(id)arg5;	// IMP=0x000000010001b4f0
- (void)_rescheduleBackgroundActivity:(long long)arg1 startDate:(id)arg2 gracePeriod:(id)arg3 priority:(const char *)arg4 repeatingInterval:(id)arg5;	// IMP=0x000000010001b3a0
- (void)_workQueueReschedulePasscodeExpiryJob;	// IMP=0x000000010001b08c
- (void)reschedulePasscodeExpiryJob;	// IMP=0x000000010001b024
- (void)rescheduleManagedAppValidationJob:(id)arg1;	// IMP=0x000000010001b004
- (void)rescheduleManagedAppValidationJob;	// IMP=0x000000010001af98
- (void)rescheduleProfileJanitorJob;	// IMP=0x000000010001aef8
- (void)_handleXPCActivity:(long long)arg1 proposedStartDate:(id)arg2 normalizeStartDate:(_Bool)arg3 proposedGracePeriod:(id)arg4 proposedPriority:(const char *)arg5 repeatingInterval:(id)arg6 requireNetwork:(_Bool)arg7 requireUnlock:(_Bool)arg8;	// IMP=0x000000010001a6fc
- (id)_jobDescriptionForBackgroundActivityType:(long long)arg1;	// IMP=0x000000010001a690
- (const char *)_jobNameForBackgroundActivityType:(long long)arg1;	// IMP=0x000000010001a668
- (id)_nextManagedAppValidationDateWithOverride:(id)arg1;	// IMP=0x000000010001a5d0
- (id)_nextActivationLockCleanupDate;	// IMP=0x000000010001a550
- (id)_profileJanitorEarliestExpiryDate;	// IMP=0x000000010001a504
- (id)_nextRegularDate;	// IMP=0x000000010001a33c
- (void)activationLockBypassCodeWasStored:(id)arg1;	// IMP=0x000000010001a248
- (void)stop;	// IMP=0x000000010001a1ac
- (void)start;	// IMP=0x0000000100019ac0

@end

