//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ManagedConfiguration/MCInstallerReader.h>

#import "MCInteractionClientDelegate-Protocol.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

@interface MCInstaller : MCInstallerReader <MCInteractionClientDelegate>
{
    NSMutableArray *_queuedProfiles;	// 8 = 0x8
    NSMutableArray *_queuedProvisioningProfiles;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_purgatoryWorkerQueue;	// 24 = 0x18
    NSDictionary *_currentlyInstallingRestrictions;	// 32 = 0x20
    NSMutableDictionary *_setAsideAccountIdentifiersByPayloadClass;	// 40 = 0x28
    NSMutableDictionary *_setAsideDictionariesByPayloadClass;	// 48 = 0x30
}

+ (void)_enumerateProfilesWithCriteria:(CDUnknownBlockType)arg1 filterFlags:(int)arg2 block:(CDUnknownBlockType)arg3;	// IMP=0x00000001000504d8
+ (void)considerProfilesInstalledDuringBuddyForManagement;	// IMP=0x000000010004ff38
+ (id)_installationFailureErrorWithUnderlyingError:(id)arg1;	// IMP=0x000000010004fc84
+ (void)_setPathsSystemProfileStorageDirectory:(id)arg1 userProfileStorageDirectory:(id)arg2;	// IMP=0x000000010004fc14
+ (unsigned long long)targetDeviceTypeForCurrentDevice;	// IMP=0x000000010004b638
+ (id)notInstalledByMDMError;	// IMP=0x000000010004628c
+ (id)deviceIsSupervisedError;	// IMP=0x00000001000461dc
+ (id)deviceNotSupervisedError;	// IMP=0x000000010004612c
+ (id)sharedInstaller;	// IMP=0x0000000100042f58
- (void).cxx_destruct;	// IMP=0x0000000100050e90
@property(retain, nonatomic) NSMutableDictionary *setAsideDictionariesByPayloadClass; // @synthesize setAsideDictionariesByPayloadClass=_setAsideDictionariesByPayloadClass;
@property(retain, nonatomic) NSMutableDictionary *setAsideAccountIdentifiersByPayloadClass; // @synthesize setAsideAccountIdentifiersByPayloadClass=_setAsideAccountIdentifiersByPayloadClass;
- (id)peekProfileDataFromPurgatoryForDeviceType:(unsigned long long)arg1;	// IMP=0x0000000100050d74
- (void)_purgatoryWorkerQueue_resetProfilePurgatorySettingsAndPostProfileListChangedNotification:(_Bool)arg1;	// IMP=0x0000000100050d68
- (void)purgeProfileWithIdentifier:(id)arg1 FromPurgatoryForTargetDeviceType:(unsigned long long)arg2;	// IMP=0x0000000100050b70
- (void)purgeProfilesFromPurgatoryForTargetDeviceType:(unsigned long long)arg1;	// IMP=0x0000000100050958
- (_Bool)sendProfileData:(id)arg1 withIdentifier:(id)arg2 toPurgatoryForTargetDeviceType:(unsigned long long)arg3 outError:(id *)arg4;	// IMP=0x0000000100050704
- (id)_installedProfileWithIdentifier:(id)arg1 installationType:(long long)arg2;	// IMP=0x000000010004fd2c
- (void)recomputeProfileRestrictionsWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010004f358
- (void)_addProfileEventForProfile:(id)arg1 operation:(id)arg2 source:(id)arg3;	// IMP=0x000000010004f048
- (id)_profileEventsOnDisk;	// IMP=0x000000010004ef80
- (id)_senderIDFromProfile:(id)arg1;	// IMP=0x000000010004eec8
- (void)cleanUp;	// IMP=0x000000010004ea58
- (void)removeManagedProfilesIfNecessary;	// IMP=0x000000010004e950
- (void)removeUninstalledProfileWithIdentifier:(id)arg1 installationType:(long long)arg2 targetDeviceType:(unsigned long long)arg3;	// IMP=0x000000010004e918
- (void)removeProfileWithIdentifier:(id)arg1 installationType:(long long)arg2 options:(id)arg3 source:(id)arg4;	// IMP=0x000000010004e608
- (void)removeProfileWithIdentifier:(id)arg1 installationType:(long long)arg2 source:(id)arg3;	// IMP=0x000000010004e5f4
- (void)_cleanUpAfterRemovingProfileWithIdentifier:(id)arg1 installedForUser:(_Bool)arg2 profileHandler:(id)arg3 oldRestrictions:(id)arg4;	// IMP=0x000000010004e090
- (id)_reallyRemoveProfileWithIdentifier:(id)arg1 installationType:(long long)arg2 profileInstalled:(_Bool)arg3 targetDeviceType:(unsigned long long)arg4 options:(id)arg5 source:(id)arg6;	// IMP=0x000000010004d8cc
- (void)removeAllProfilesFromInstallationQueue;	// IMP=0x000000010004d884
- (id)_managingProfileIdentifierForProfileIdentifier:(id)arg1;	// IMP=0x000000010004d7b0
- (void)_removeOrphanedResourcesIncludingAccounts:(_Bool)arg1;	// IMP=0x000000010004cb54
- (_Bool)interactionClient:(id)arg1 didRequestPreflightUserInputResponses:(id)arg2 forPayloadIndex:(unsigned long long)arg3 outError:(id *)arg4;	// IMP=0x000000010004c95c
- (id)updateProfileWithIdentifier:(id)arg1 interactionClient:(id)arg2 installForSystem:(_Bool)arg3 source:(id)arg4 outError:(id *)arg5;	// IMP=0x000000010004c0ac
- (id)updateProfileWithIdentifier:(id)arg1 interactionClient:(id)arg2 source:(id)arg3 outError:(id *)arg4;	// IMP=0x000000010004c094
- (id)_profileNotEligibleErrorWithProfile:(id)arg1;	// IMP=0x000000010004bfd8
- (id)_watchInformationOutIsCellularSupported:(_Bool *)arg1;	// IMP=0x000000010004bfd0
- (id)_preflightProfileForInstallationOnWatch:(id)arg1;	// IMP=0x000000010004ba4c
- (id)_preflightProfileForInstallationOnHomePod:(id)arg1;	// IMP=0x000000010004b778
- (id)_errorUnacceptablePayload:(id)arg1;	// IMP=0x000000010004b6bc
- (_Bool)_overrideProfileValidation;	// IMP=0x000000010004b658
- (id)installProfileData:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 source:(id)arg4 outError:(id *)arg5;	// IMP=0x00000001000495a8
- (id)existingProfileContainingPayloadClass:(Class)arg1 inProfilesWithFilterFlags:(int)arg2 excludingProfileIdentifier:(id)arg3;	// IMP=0x00000001000493bc
- (id)existingProfileContainingPayloadClass:(Class)arg1 excludingProfileIdentifier:(id)arg2;	// IMP=0x00000001000493a8
- (_Bool)_showWarnings:(id)arg1 interactionClient:(id)arg2 outError:(id *)arg3;	// IMP=0x00000001000492d4
- (_Bool)_showWarningsForUpdatingProfile:(id)arg1 originalProfile:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x00000001000491d8
- (_Bool)_showWarningsForProfile:(id)arg1 interactionClient:(id)arg2 outError:(id *)arg3;	// IMP=0x0000000100049144
- (id)setAsideDictionariesForPayloadHandlerClass:(Class)arg1;	// IMP=0x00000001000490e0
- (void)addSetAsideDictionary:(id)arg1 forPayloadHandlerClass:(Class)arg2;	// IMP=0x0000000100049004
- (id)setAsideAccountIdentifiersForPayloadClass:(Class)arg1;	// IMP=0x0000000100048f60
- (void)addSetAsideAccountIdentifier:(id)arg1 forPayloadClass:(Class)arg2;	// IMP=0x0000000100048e4c
- (_Bool)deviceSupervisionRequiredForPayload:(id)arg1;	// IMP=0x0000000100048c94
- (id)_installProfileHandler:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 source:(id)arg4 outError:(id *)arg5;	// IMP=0x0000000100046324
- (id)_deviceLockedError;	// IMP=0x0000000100046094
- (id)_guardAgainstNoMDMPayloadWithNewProfile:(id)arg1 oldProfile:(id)arg2;	// IMP=0x0000000100045f1c
- (id)_validateMDMReplacementNewProfile:(id)arg1 oldProfile:(id)arg2 client:(id)arg3;	// IMP=0x0000000100045ae4
- (_Bool)_promptUserForMAIDSignIn:(id)arg1 personaID:(id)arg2 handler:(id)arg3 interactionClient:(id)arg4 outError:(id *)arg5;	// IMP=0x00000001000459e0
- (_Bool)_promptUserForComplianceWithRestrictions:(id)arg1 handler:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x00000001000451a8
- (id)_userCancelledErrorWithFriendlyName:(id)arg1;	// IMP=0x0000000100045110
- (id)_invalidInputError;	// IMP=0x0000000100045078
- (id)_installationHaltedTopLevelError;	// IMP=0x0000000100044f60
- (id)_uiProfileInstallationDisabledTopLevelError;	// IMP=0x0000000100044ec8
- (id)_targetDeviceMismatchError;	// IMP=0x0000000100044e30
- (id)_targetDeviceInvalidError;	// IMP=0x0000000100044d98
- (id)_targetDeviceArchivedError;	// IMP=0x0000000100044d00
- (id)_targetDeviceUnavailableError;	// IMP=0x0000000100044c68
- (id)_targetDeviceErrorWithUnderlyingError:(id)arg1;	// IMP=0x0000000100044bb8
- (id)_malformedPayloadErrorWithUnderlyingError:(id)arg1;	// IMP=0x0000000100044b08
- (id)_malformedPayloadErrorInternal:(_Bool)arg1;	// IMP=0x0000000100044a54
- (id)_queueProfileData:(id)arg1 profile:(id)arg2 forDevice:(unsigned long long)arg3;	// IMP=0x00000001000444f4
- (long long)_targetValidationStatusForProfile:(id)arg1;	// IMP=0x00000001000443d0
- (void)queueProfileDataForInstallation:(id)arg1 originalFileName:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100043978
- (id)popProvisioningProfileDataAtHeadOfInstallationQueue;	// IMP=0x00000001000438f8
- (_Bool)queueProvisioningProfileDataForInstallation:(id)arg1 outError:(id *)arg2;	// IMP=0x0000000100043794
- (id)_badProvisioningProfileError;	// IMP=0x00000001000436fc
- (id)popProfileDataAtHeadOfInstallationQueue;	// IMP=0x000000010004367c
- (id)pathToInstalledProfileByUUID:(id)arg1;	// IMP=0x00000001000432f4
- (id)pathToUninstalledProfileByIdentifier:(id)arg1 installationType:(long long)arg2 targetDeviceType:(unsigned long long)arg3;	// IMP=0x00000001000431fc
- (id)pathToInstalledProfileByIdentifier:(id)arg1 installationType:(long long)arg2;	// IMP=0x00000001000430dc
- (id)identifiersOfInstalledProfilesWithFilterFlags:(int)arg1;	// IMP=0x0000000100043078
- (id)init;	// IMP=0x0000000100042fc4

@end

