//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@class UIWebClip;

@interface MCNewWebClipPayloadHandler : MCNewPayloadHandler
{
    UIWebClip *_setAsideClip;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100029248
- (void)unsetAside;	// IMP=0x0000000100029184
- (void)setAside;	// IMP=0x000000010002901c
- (_Bool)isInstalled;	// IMP=0x0000000100028f2c
- (void)remove;	// IMP=0x0000000100028da0
- (id)_findInstalledClipWithIdentifier:(id)arg1;	// IMP=0x0000000100028c00
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0000000100028574
- (id)savedWebClipIdentifier;	// IMP=0x0000000100028490

@end

