//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCMXPCMessageWithIdentifierBase.h"

@interface MCMXPCMessageSetCodeSignMapping : MCMXPCMessageWithIdentifierBase
{
    id _info;	// 8 = 0x8
    id _options;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010007b52c
@property(readonly, nonatomic) id options; // @synthesize options=_options;
@property(readonly, nonatomic) id info; // @synthesize info=_info;
- (id)initWithXPCObject:(id)arg1 clientConnection:(id)arg2 error:(unsigned long long *)arg3;	// IMP=0x000000010007b418

@end

