//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC11FlusherUtil15FBFPeriodicTask : _TtCs12_SwiftObject
{
    MISSING_TYPE *fbfAssembly;	// 16 = 0x10
    MISSING_TYPE *activity;	// 32 = 0x20
    MISSING_TYPE *activityQueue;	// 40 = 0x28
    MISSING_TYPE *activityController;	// 48 = 0x30
    MISSING_TYPE *activityGroup;	// 56 = 0x38
    MISSING_TYPE *sisUploader;	// 64 = 0x40
}

@end

