//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CloudPhotoLibrary/CPLPlatformObject.h>

#import "CPLEngineSchedulerImplementation-Protocol.h"

@class CPLSyncSession, NSObject, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface CPLBaseScheduler : CPLPlatformObject <CPLEngineSchedulerImplementation>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSObject<OS_dispatch_source> *_timer;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_sequenceNumberQueue;	// 24 = 0x18
    unsigned long long _sequenceNumber;	// 32 = 0x20
    CPLSyncSession *_currentSession;	// 40 = 0x28
    CPLSyncSession *_scheduledSession;	// 48 = 0x30
    _Bool _inOpenCompletionHandler;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001000667a4
- (id)componentName;	// IMP=0x0000000100066798
- (void)unscheduleSyncSession:(id)arg1;	// IMP=0x000000010006660c
- (id)scheduleNextSyncSessionAtDate:(id)arg1;	// IMP=0x0000000100066218
- (void)closeAndDeactivate:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100066058
- (void)openWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100065ae4
- (void)noteSyncSession:(id)arg1 failedWithError:(id)arg2;	// IMP=0x0000000100065714
- (void)noteSyncSessionSucceeded:(id)arg1;	// IMP=0x00000001000655c8
- (void)noteServerHasChanges;	// IMP=0x00000001000655c4
- (void)noteClientNeedsToPull;	// IMP=0x00000001000655c0
- (void)noteScopeNeedsToPushToTransport;	// IMP=0x00000001000655bc
- (_Bool)shouldCoalesceServerChangesNotification;	// IMP=0x00000001000655b4
- (_Bool)shouldStartSyncSessionFromState:(unsigned long long)arg1;	// IMP=0x00000001000655ac
- (unsigned long long)_nextSequenceNumber;	// IMP=0x00000001000654ec
@property(readonly, nonatomic) CPLSyncSession *persistedInitialSyncSession;
- (id)initWithAbstractObject:(id)arg1;	// IMP=0x000000010006527c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

