//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol CPLBatterySaverWatcherDelegate, OS_dispatch_queue;

@interface CPLBatterySaverWatcher : NSObject
{
    _Bool _batterySaverMode;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    id <CPLBatterySaverWatcherDelegate> _delegate;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100017418
@property(readonly) __weak id <CPLBatterySaverWatcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_registerForBatterySaverMode;	// IMP=0x0000000100017398
- (void)_batterySaverModeTriggered;	// IMP=0x00000001000172e0
- (_Bool)_updateBatterSaverMode;	// IMP=0x0000000100017268
- (_Bool)inBatterySaverMode;	// IMP=0x0000000100017260
- (id)initWithDispatchQueue:(id)arg1 delegate:(id)arg2;	// IMP=0x00000001000171a0

@end

