//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CPLCloudKitFakeDynamicDerivatives : NSObject
{
}

+ (id)transformData:(id)arg1 fileType:(id)arg2 matchingResource:(id)arg3 error:(id *)arg4;	// IMP=0x000000010009086c
+ (_Bool)transformFromURL:(id)arg1 fileType:(id)arg2 toTargetURL:(id)arg3 matchingResource:(id)arg4 error:(id *)arg5;	// IMP=0x00000001000905a4
+ (_Bool)_transferImageFromSource:(struct CGImageSource *)arg1 toDestination:(struct CGImageDestination *)arg2 matchingResource:(id)arg3;	// IMP=0x0000000100090534
+ (id)_outputOptionsFromSource:(struct CGImageSource *)arg1 matchingResource:(id)arg2;	// IMP=0x000000010009034c
+ (id)_metadataWithoutOrientation:(id)arg1;	// IMP=0x000000010009025c
+ (unsigned long long)realResourceTypeForResource:(id)arg1;	// IMP=0x00000001000901a8
+ (_Bool)isFakeDerivative:(id)arg1;	// IMP=0x0000000100090110
+ (id)overriddenResourcesFromResources:(id)arg1;	// IMP=0x000000010008fe44
+ (_Bool)usesFakeDerivatives;	// IMP=0x000000010008fe38
+ (void)setAllowsFakeDerivatives:(_Bool)arg1;	// IMP=0x000000010008fa3c
+ (id)fakeDerivativesDescription;	// IMP=0x000000010008f860
+ (_Bool)allowsFakeDerivatives;	// IMP=0x000000010008f854

@end

