//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CloudPhotoLibrary/CPLPlatformObject.h>

#import "CPLChangeSessionImplementation-Protocol.h"

@class CPLResetReason, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface CPLDirectChangeSession : CPLPlatformObject <CPLChangeSessionImplementation>
{
    NSObject<OS_dispatch_queue> *_lock;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_callbackQueue;	// 16 = 0x10
    CPLResetReason *_tentativeReason;	// 24 = 0x18
    _Bool _beganClientWork;	// 32 = 0x20
    _Bool _tearedDown;	// 33 = 0x21
}

+ (id)selfCrashResetReason;	// IMP=0x0000000100082844
- (void).cxx_destruct;	// IMP=0x0000000100082ae4
- (void)discardTentativeResetReason;	// IMP=0x0000000100082a90
- (void)registerTentativeResetReason;	// IMP=0x0000000100082930
- (_Bool)tearedDown;	// IMP=0x0000000100082794
- (void)dispatchCallback:(CDUnknownBlockType)arg1;	// IMP=0x0000000100082608
- (void)tearDownWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100082254
- (void)endClientWork;	// IMP=0x00000001000820b0
- (void)finalizeWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100081fe4
- (void)beginSessionWithKnownLibraryVersion:(id)arg1 context:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100081f00
- (_Bool)processSessionContext:(id)arg1 inStore:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100081dd0
- (void)beginClientWork;	// IMP=0x0000000100081c00
- (id)clientWorkDescription;	// IMP=0x0000000100081b3c
- (id)initWithAbstractObject:(id)arg1;	// IMP=0x0000000100081a74

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

