//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class HMAccessory, NSUUID;

@interface MSDMigrator : NSObject
{
    HMAccessory *_device;	// 8 = 0x8
    NSUUID *_ownerUUID;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100031c1c
@property(retain) NSUUID *ownerUUID; // @synthesize ownerUUID=_ownerUUID;
@property(retain) HMAccessory *device; // @synthesize device=_device;
- (id)setPrimaryUserIdentifier:(id)arg1;	// IMP=0x00000001000316b8
- (id)primaryUserWithHomeUsersForActiveAccount:(id)arg1 homeOwner:(id)arg2;	// IMP=0x0000000100031478
- (id)migrateDefaultAccountToPrimaryUser;	// IMP=0x0000000100031324
- (void)performMigrationIfNeeded:(CDUnknownBlockType)arg1;	// IMP=0x0000000100030fac
@property(readonly, nonatomic) _Bool isVersionCurrent;
- (void)setCurrentVersion:(unsigned long long)arg1;	// IMP=0x0000000100030e70
- (unsigned long long)currentVersion;	// IMP=0x0000000100030dd0

@end

