//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyDidReceiveDataReply : PBCodable <NSCopying>
{
    PDURLSessionProxyTaskMessage *_task;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003d5a8
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010003d520
- (unsigned long long)hash;	// IMP=0x000000010003d508
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010003d468
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010003d3ec
- (void)copyTo:(id)arg1;	// IMP=0x000000010003d3c4
- (void)writeTo:(id)arg1;	// IMP=0x000000010003d3a4
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010003d1bc
- (id)dictionaryRepresentation;	// IMP=0x000000010003d130
- (id)description;	// IMP=0x000000010003d07c
@property(readonly, nonatomic) _Bool hasTask;

@end

