//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyGetAuthHeadersReply : PBCodable <NSCopying>
{
    NSData *_headerData;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
    _Bool _continueLoad;	// 24 = 0x18
    struct {
        unsigned int continueLoad:1;
    } _has;	// 28 = 0x1c
}

- (void).cxx_destruct;	// IMP=0x0000000100030940
@property(nonatomic) _Bool continueLoad; // @synthesize continueLoad=_continueLoad;
@property(retain, nonatomic) NSData *headerData; // @synthesize headerData=_headerData;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100030838
- (unsigned long long)hash;	// IMP=0x00000001000307a8
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100030698
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000305bc
- (void)copyTo:(id)arg1;	// IMP=0x0000000100030524
- (void)writeTo:(id)arg1;	// IMP=0x0000000100030498
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000301bc
- (id)dictionaryRepresentation;	// IMP=0x00000001000300a8
- (id)description;	// IMP=0x000000010002fff4
@property(nonatomic) _Bool hasContinueLoad;
@property(readonly, nonatomic) _Bool hasHeaderData;
@property(readonly, nonatomic) _Bool hasTask;

@end

