/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, April 28, 2021 at 9:09:54 PM Mountain Standard Time
                       * Operating System: Version 14.5 (Build 18L204)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libcoreroutine.dylib/RTStore.h>

@interface RTSettledStateTransitionStore : RTStore
-(void)clearWithHandler:(/*^block*/id)arg1 ;
-(void)enumerateStoredSettledStateTransitionsWithOptions:(id)arg1 enumerationBlock:(/*^block*/id)arg2 ;
-(void)_purgeSettledStateTransitionsPredating:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)storeSettledStateTransitions:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)purgeSettledStateTransitionsPredating:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

