//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteMemoryEntity.h"

@interface AppPackage : SQLiteMemoryEntity
{
}

+ (id)_valueDictionaryWithSystemAppLookupItem:(id)arg1;	// IMP=0x0000000100064a14
+ (id)_valueDictionaryWithStoreAsset:(id)arg1;	// IMP=0x0000000100064610
+ (id)_legacy_valueDictionaryWithAsset:(id)arg1;	// IMP=0x000000010015466c
+ (id)legacy_packageForAsset:(id)arg1;	// IMP=0x00000001001545dc
- (id)initWithSystemAppLookupItem:(id)arg1;	// IMP=0x0000000100064568
- (id)initWithStoreAsset:(id)arg1;	// IMP=0x00000001000644c0

@end

