//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASDArcadeServiceProtocol-Protocol.h"

@protocol OS_dispatch_queue;

@interface ArcadeService : NSObject <ASDArcadeServiceProtocol>
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
}

+ (id)defaultService;	// IMP=0x00000001001fbe90
- (void).cxx_destruct;	// IMP=0x00000001001fcf94
- (id)_currentClient;	// IMP=0x00000001001fcf10
- (void)removeHardwareOfferMetricsforOfferIDs:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001fcca8
- (void)removeHardwareOfferIDs:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001fca40
- (void)removeAllHardwareOfferIDsWithReplyHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001001fc830
- (void)hardwareOfferCountWithReplyHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001001fc620
- (void)allHardwareOfferMetricsWithReplyHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001001fc388
- (void)allHardwareOffersIDsWithReplyHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001001fc138
- (void)addHardwareOfferIDs:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001fbefc
- (id)init;	// IMP=0x00000001001fbe08

@end

