//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "Task.h"

@class ACAccount, AMSURLRequestEncoder, NSMutableArray, NSMutableOrderedSet, NSOrderedSet, NSString;
@protocol RequestPresenter;

@interface LoadStoreQueueTask : Task
{
    NSString *_logKey;	// 8 = 0x8
    id <RequestPresenter> _presenter;	// 16 = 0x10
    long long _queueType;	// 24 = 0x18
    NSMutableArray *_rangesToLoad;	// 32 = 0x20
    AMSURLRequestEncoder *_requestEncoder;	// 40 = 0x28
    NSMutableOrderedSet *_storeItems;	// 48 = 0x30
    ACAccount *_account;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00000001002631bc
@property(readonly, copy) NSOrderedSet *storeItems; // @synthesize storeItems=_storeItems;
@property(readonly) ACAccount *account; // @synthesize account=_account;
- (id)_newURLRequestWithStartIdentifier:(id)arg1 endIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100262e40
- (_Bool)_loadDownloadsFromStart:(id)arg1 toEnd:(id)arg2;	// IMP=0x0000000100262b98
- (void)_handleResponse:(id)arg1;	// IMP=0x0000000100262a50
- (id)_bagKey;	// IMP=0x00000001002629d4
- (id)_account;	// IMP=0x0000000100262950
- (void)main;	// IMP=0x00000001002627b0
- (id)initWithQueueType:(long long)arg1 forAccount:(id)arg2 requestPresenter:(id)arg3 logKey:(id)arg4;	// IMP=0x00000001002626bc

@end

