//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "Task.h"

@class EvaluatorDownload;

@interface LowDataEvaluatorTask : Task
{
    EvaluatorDownload *_cellularDownload;	// 8 = 0x8
    long long _evaluatorResult;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001001257f8
@property(readonly) long long evaluatorResult; // @synthesize evaluatorResult=_evaluatorResult;
@property(retain) EvaluatorDownload *cellularDownload; // @synthesize cellularDownload=_cellularDownload;
- (void)main;	// IMP=0x00000001001252d4

@end

