//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MIStoreMetadata, NSData, NSDictionary, NSString, NSURL;

@interface PlaceholderBuilder : NSObject
{
    unsigned long long _signpostID;	// 8 = 0x8
    _Bool _arcade;	// 16 = 0x10
    _Bool _enforceATS;	// 17 = 0x11
    _Bool _hasMessagesExtension;	// 18 = 0x12
    _Bool _launchProhibited;	// 19 = 0x13
    NSData *_artworkData;	// 24 = 0x18
    NSURL *_artworkURL;	// 32 = 0x20
    NSString *_bundleID;	// 40 = 0x28
    NSString *_bundleName;	// 48 = 0x30
    NSString *_bundleVersion;	// 56 = 0x38
    NSString *_companionBundleID;	// 64 = 0x40
    NSDictionary *_entitlements;	// 72 = 0x48
    unsigned long long _installType;	// 80 = 0x50
    NSString *_logKey;	// 88 = 0x58
    NSURL *_messagesArtworkURL;	// 96 = 0x60
    long long _sourceType;	// 104 = 0x68
    MIStoreMetadata *_storeMetadata;	// 112 = 0x70
}

+ (id)_artworkPromiseForURL:(id)arg1 logKey:(id)arg2 enforceATS:(_Bool)arg3;	// IMP=0x00000001001979d4
- (void).cxx_destruct;	// IMP=0x0000000100199174
@property(retain) MIStoreMetadata *storeMetadata; // @synthesize storeMetadata=_storeMetadata;
@property long long sourceType; // @synthesize sourceType=_sourceType;
@property(retain) NSURL *messagesArtworkURL; // @synthesize messagesArtworkURL=_messagesArtworkURL;
@property(retain) NSString *logKey; // @synthesize logKey=_logKey;
@property _Bool launchProhibited; // @synthesize launchProhibited=_launchProhibited;
@property unsigned long long installType; // @synthesize installType=_installType;
@property _Bool hasMessagesExtension; // @synthesize hasMessagesExtension=_hasMessagesExtension;
@property(retain) NSDictionary *entitlements; // @synthesize entitlements=_entitlements;
@property _Bool enforceATS; // @synthesize enforceATS=_enforceATS;
@property(retain) NSString *companionBundleID; // @synthesize companionBundleID=_companionBundleID;
@property(retain) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(retain) NSString *bundleName; // @synthesize bundleName=_bundleName;
@property(retain) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(retain) NSURL *artworkURL; // @synthesize artworkURL=_artworkURL;
@property(retain) NSData *artworkData; // @synthesize artworkData=_artworkData;
@property _Bool arcade; // @synthesize arcade=_arcade;
- (id)_extensionPlaceholderWithParent:(id)arg1;	// IMP=0x0000000100198950
- (_Bool)_configurePlaceholder:(id)arg1 withError:(id *)arg2;	// IMP=0x000000010019824c
- (id)buildPlaceholderWithError:(id *)arg1;	// IMP=0x0000000100197900
- (id)buildPlaceholderForSystemAppWithError:(id *)arg1;	// IMP=0x00000001001978d8
- (id)buildPlaceholderForStoreAppWithError:(id *)arg1;	// IMP=0x00000001001975c0
- (id)init;	// IMP=0x0000000100197550

@end

