//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SQLiteConnection, SQLiteQueryDescriptor;

@interface SQLiteQuery : NSObject
{
    SQLiteConnection *_connection;	// 8 = 0x8
    SQLiteQueryDescriptor *_descriptor;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100163fc4
- (id)_newSelectSQLWithProperties:(id)arg1;	// IMP=0x0000000100163ddc
@property(readonly) SQLiteQueryDescriptor *queryDescriptor;
- (void)enumeratePersistentIDsAndProperties:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001001639b4
- (void)enumeratePersistentIDsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010016390c
- (void)enumerateMemoryEntitiesWithProperties:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001001636b0
- (void)enumerateMemoryEntitiesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010016361c
- (_Bool)deleteAllEntities;	// IMP=0x0000000100163450
- (_Bool)createTemporaryTableWithName:(id)arg1 properties:(id)arg2;	// IMP=0x00000001001630b8
@property(readonly) long long countOfEntities;
- (id)copySelectSQLWithProperties:(id)arg1;	// IMP=0x0000000100162e40
- (id)copyEntityIdentifiers;	// IMP=0x0000000100162d60
@property(readonly) SQLiteConnection *connection;
- (void)applyBinding:(id)arg1 atIndex:(inout int *)arg2;	// IMP=0x0000000100162cb0
- (id)initOnConnection:(id)arg1 descriptor:(id)arg2;	// IMP=0x0000000100162c00

@end

