//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "Task.h"

@class NSArray, NSPredicate;

@interface SystemAppLookupTask : Task
{
    NSPredicate *_predicate;	// 8 = 0x8
    NSArray *_lookupResults;	// 16 = 0x10
}

+ (id)lookupSystemApplicationsWithBundleIDs:(id)arg1;	// IMP=0x0000000100165278
+ (id)lookupSystemApplicationWithBundleID:(id)arg1;	// IMP=0x00000001001651f8
- (void).cxx_destruct;	// IMP=0x0000000100165768
@property(readonly, copy) NSArray *lookupResults; // @synthesize lookupResults=_lookupResults;
- (void)main;	// IMP=0x0000000100165378
- (id)initWithPredicate:(id)arg1;	// IMP=0x00000001001652f8

@end

