//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface UserNotification : NSObject
{
    CDUnknownBlockType _completionBlock;	// 8 = 0x8
    _Bool _isCanceled;	// 16 = 0x10
    NSDictionary *_notificationDictionary;	// 24 = 0x18
    unsigned long long _notificationOptions;	// 32 = 0x20
    struct __CFUserNotification *_userNotification;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001001696e0
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(readonly, nonatomic, getter=isCanceled) _Bool canceled; // @synthesize canceled=_isCanceled;
- (unsigned long long)waitForResponse;	// IMP=0x0000000100169690
@property(readonly, nonatomic) struct __CFUserNotification *userNotification;
- (void)updateWithDictionary:(id)arg1 options:(unsigned long long)arg2;	// IMP=0x0000000100169620
- (void)show;	// IMP=0x00000001001695e4
- (void)cancel;	// IMP=0x00000001001695a8
- (void)dealloc;	// IMP=0x0000000100169554
- (id)initWithDictionary:(id)arg1 options:(unsigned long long)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100169484
- (id)initWithDialog:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001001693d0

@end

