//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SystemDiagnostic.h"

__attribute__((visibility("hidden")))
@interface SystemDiagnosticiOS : SystemDiagnostic
{
    _Bool _tailspinOnly;	// 56 = 0x38
    _Bool _vibrateStart;	// 57 = 0x39
    _Bool _wasLockedAtLaunch;	// 58 = 0x3a
    int _idsCase;	// 60 = 0x3c
    long long _maxHistory;	// 64 = 0x40
    long long _openIssueFiler;	// 72 = 0x48
    long long _statusBar;	// 80 = 0x50
}

@property _Bool wasLockedAtLaunch; // @synthesize wasLockedAtLaunch=_wasLockedAtLaunch;
@property int idsCase; // @synthesize idsCase=_idsCase;
@property long long statusBar; // @synthesize statusBar=_statusBar;
@property long long openIssueFiler; // @synthesize openIssueFiler=_openIssueFiler;
@property long long maxHistory; // @synthesize maxHistory=_maxHistory;
@property _Bool vibrateStart; // @synthesize vibrateStart=_vibrateStart;
@property _Bool tailspinOnly; // @synthesize tailspinOnly=_tailspinOnly;
- (void)startIDSConnection;	// IMP=0x0000000100051b80
- (void)run;	// IMP=0x00000001000516cc
- (id)parseSizeToString:(unsigned long long)arg1;	// IMP=0x0000000100051668
- (id)searchForTransfer:(id)arg1;	// IMP=0x0000000100051308
- (void)getSettings;	// IMP=0x00000001000512c4
- (void)overrideSettings;	// IMP=0x0000000100051184
- (void)getUserSettings;	// IMP=0x0000000100050e00
- (void)configureDefaultSettings;	// IMP=0x0000000100050be4
- (void)launchSettings_async;	// IMP=0x0000000100050a5c
- (void)gatherDiagnostic;	// IMP=0x000000010005080c
- (void)triggerRemoteSysdiagnoses;	// IMP=0x00000001000507c0
- (void)triggerAirPodLogs:(_Bool)arg1;	// IMP=0x0000000100050748
- (void)triggerFromBridge;	// IMP=0x0000000100050744
- (_Bool)triggerCosysdiagnose;	// IMP=0x000000010005073c
- (void)prompt;	// IMP=0x0000000100050738
- (void)dropCosysdiagnoseError:(id)arg1;	// IMP=0x0000000100050728
- (void)sendPathToArchive;	// IMP=0x0000000100050614
- (void)sendDefaultsInstructions;	// IMP=0x0000000100050590
- (void)sendFailedInstructions;	// IMP=0x000000010005050c
- (void)sendUnableToCreateMsg;	// IMP=0x0000000100050488
- (void)createFileAndTransfer:(id)arg1 atLocation:(id)arg2;	// IMP=0x0000000100050388
- (_Bool)readCosysdiagnoseSetting;	// IMP=0x00000001000502d0
- (_Bool)makeOutputDirectory;	// IMP=0x000000010004fbb4
- (id)defaultBaseDirectory;	// IMP=0x000000010004fba0
- (id)init;	// IMP=0x000000010004fb08

@end

