//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VCPMADTaskProtocol-Protocol.h"

@class NSArray;

@interface VCPCompoundMADTask : NSObject <VCPMADTaskProtocol>
{
    struct atomic<bool> _started;	// 8 = 0x8
    struct atomic<bool> _canceled;	// 9 = 0x9
    NSArray *_tasks;	// 16 = 0x10
    CDUnknownBlockType _completionHandler;	// 24 = 0x18
    CDUnknownBlockType _cancelBlock;	// 32 = 0x20
}

+ (id)taskWithPhotoLibrary:(id)arg1 forVCPTaskIDs:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4 andCancelBlock:(CDUnknownBlockType)arg5;	// IMP=0x0000000100006624
- (void).cxx_destruct;	// IMP=0x000000010003ed00
- (int)run;	// IMP=0x000000010003eb4c
- (_Bool)run:(id *)arg1;	// IMP=0x000000010003e84c
- (_Bool)isCanceled;	// IMP=0x000000010003e828
- (void)cancel;	// IMP=0x000000010003e6e0
- (float)resourceRequirement;	// IMP=0x000000010003e6d8
- (void)dealloc;	// IMP=0x000000010003e4e0
- (id)initWithVCPMADTasks:(id)arg1 andCompletionHandler:(CDUnknownBlockType)arg2 andCancelBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010003e3d8

@end

