//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VCPMADTaskProtocol-Protocol.h"

@class HMIAnalysisService, IOSurface, NSData, NSDictionary;
@protocol OS_dispatch_queue;

@interface VCPHomeKitAnalysisServiceTask : NSObject <VCPMADTaskProtocol>
{
    _Bool _cancel;	// 8 = 0x8
    _Bool _run;	// 9 = 0x9
    NSData *_fragmentData;	// 16 = 0x10
    IOSurface *_fragmentSurface;	// 24 = 0x18
    NSDictionary *_properties;	// 32 = 0x20
    int _requestID;	// 40 = 0x28
    HMIAnalysisService *_analysisService;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_managementQueue;	// 56 = 0x38
    CDUnknownBlockType _progressHandler;	// 64 = 0x40
    CDUnknownBlockType _completionHandler;	// 72 = 0x48
}

+ (id)taskForFragmentSurface:(id)arg1 withProperties:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010000fd04
+ (id)taskForFragmentData:(id)arg1 withProperties:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010000fc10
+ (_Bool)isPerFrameAnalysisEnabled;	// IMP=0x000000010000f690
- (void).cxx_destruct;	// IMP=0x0000000100010a44
- (int)run;	// IMP=0x00000001000109f0
- (void)runFrameLevelAnalysis;	// IMP=0x0000000100010294
- (void)runFragmentLevelAnalysis;	// IMP=0x000000010000ff4c
- (void)cancel;	// IMP=0x000000010000fe00
- (float)resourceRequirement;	// IMP=0x000000010000fdf8
- (id)initWithFragmentSurface:(id)arg1 properties:(id)arg2 progressHandler:(CDUnknownBlockType)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010000fa4c
- (id)initWithFragmentData:(id)arg1 properties:(id)arg2 progressHandler:(CDUnknownBlockType)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010000f7d0
- (id)init;	// IMP=0x000000010000f7b8

@end

