//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class VCPTimer;
@protocol OS_dispatch_queue;

@interface VCPProgressReporter : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    VCPTimer *_timer;	// 16 = 0x10
    long long _processedJobCountOnLastUpdate;	// 24 = 0x18
    long long _processedJobCount;	// 32 = 0x20
    long long _totalJobCount;	// 40 = 0x28
}

+ (id)reporterWithIntervalSeconds:(unsigned long long)arg1 andTotalJobCount:(long long)arg2 andBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010000bb44
- (void).cxx_destruct;	// IMP=0x000000010000bde8
- (void)_reportProgressWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010000bc58
- (void)increaseProcessedJobCountByOne;	// IMP=0x000000010000bc48
- (void)dealloc;	// IMP=0x000000010000bbc8
- (id)initWithIntervalSeconds:(unsigned long long)arg1 andTotalJobCount:(long long)arg2 andBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010000b7b0
- (id)init;	// IMP=0x000000010000b798

@end

