//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface VCPWatchdog : NSObject
{
}

+ (id)sharedWatchdog;	// IMP=0x000000010000c088
- (void)disable;	// IMP=0x000000010000c188
- (void)pet;	// IMP=0x000000010000c17c
- (void)enable;	// IMP=0x000000010000c0f4
- (id)init;	// IMP=0x000000010000be18

@end

