//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UAAnalyticsEvent.h"

@interface UARemotePasteboardTypeInfoRequestedEvent : UAAnalyticsEvent
{
    unsigned long long _payloadSize;	// 8 = 0x8
    unsigned long long _payloadXferTime;	// 16 = 0x10
    long long _errorCode;	// 24 = 0x18
}

@property long long errorCode; // @synthesize errorCode=_errorCode;
@property unsigned long long payloadXferTime; // @synthesize payloadXferTime=_payloadXferTime;
@property unsigned long long payloadSize; // @synthesize payloadSize=_payloadSize;
- (id)eventPayload;	// IMP=0x000000010004474c
- (id)eventName;	// IMP=0x0000000100044740

@end

