//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CKInteractionProcessing-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface CKThirdPartyAppInteractionProcessor : NSObject <CKInteractionProcessing>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010000aa14
- (_Bool)processInteraction:(id)arg1 bundleId:(id)arg2;	// IMP=0x000000010000a9d0
- (id)supportedTypes;	// IMP=0x000000010000a9c8
- (id)bundleIdPredicate;	// IMP=0x000000010000a988
- (_Bool)supportsSiriDonations;	// IMP=0x000000010000a980
- (id)init;	// IMP=0x000000010000a8a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

