//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKDisplayBootUIRenderOverlay.h"

@class PUIProgressWindow;

@interface BKDisplayRenderOverlayAppleLogo : BKDisplayBootUIRenderOverlay
{
    PUIProgressWindow *_puiProgressWindow;	// 8 = 0x8
}

+ (id)overlayWithLevel:(float)arg1 display:(id)arg2;	// IMP=0x000000010004cbdc
- (void).cxx_destruct;	// IMP=0x000000010004cbc8
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x000000010004cb48
- (void)_cleanUpContentLayer;	// IMP=0x000000010004cb08
- (id)_prepareContentLayerForPresentation:(id)arg1;	// IMP=0x000000010004c9f0
- (id)initWithOverlayDescriptor:(id)arg1 level:(float)arg2;	// IMP=0x000000010004c994

@end

