//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableOrderedSet, NSString;

@interface BKNamespaceNode : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSObject *_object;	// 16 = 0x10
    NSMutableOrderedSet *_subnodes;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010005ccd8
@property(retain, nonatomic) NSMutableOrderedSet *subnodes; // @synthesize subnodes=_subnodes;
@property(retain, nonatomic) NSObject *object; // @synthesize object=_object;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)_dumpNodeTree:(id)arg1 level:(long long)arg2;	// IMP=0x000000010005ca4c
- (id)_enumerateKeyPathNodesByComponent:(id)arg1 options:(long long)arg2 ifFound:(CDUnknownBlockType)arg3 ifMissing:(CDUnknownBlockType)arg4;	// IMP=0x000000010005c6bc
- (void)_enumerateNodesWithOptions:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010005c554
- (void)dumpNodeTree;	// IMP=0x000000010005c540
- (id)enumerateKeyPathNodes:(id)arg1 options:(long long)arg2 ifFound:(CDUnknownBlockType)arg3 ifMissing:(CDUnknownBlockType)arg4;	// IMP=0x000000010005c480
- (void)enumerateNodesWithOptions:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010005c474
- (id)setObject:(id)arg1 atKeyPath:(id)arg2;	// IMP=0x000000010005c3f0
- (id)objectAtKeyPath:(id)arg1;	// IMP=0x000000010005c39c
- (id)nodeAtKeyPath:(id)arg1;	// IMP=0x000000010005c384
- (void)removeNodeAtKeyPath:(id)arg1;	// IMP=0x000000010005c244
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010005c120
- (unsigned long long)hash;	// IMP=0x000000010005c110
- (id)description;	// IMP=0x000000010005c100
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x000000010005bfc0
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x000000010005bf6c
- (id)succinctDescriptionBuilder;	// IMP=0x000000010005bf54
- (id)succinctDescription;	// IMP=0x000000010005bf00
- (id)init;	// IMP=0x000000010005be9c

@end

