//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol AMSDCloudDataManagerDataSource;

@protocol AMSDCloudDataManagerDataSourceDelegate
- (void)cloudDataManagerDataSource:(id <AMSDCloudDataManagerDataSource>)arg1 didChangeWithType:(unsigned long long)arg2;
@end

