//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface PLKeepDaemonAliveAssertionServer : NSObject
{
    NSObject<OS_dispatch_queue> *_connectionQueue;	// 8 = 0x8
}

+ (void)_enablePhotoStreams;	// IMP=0x000000010000ea90
+ (void)_disablePhotoStreams;	// IMP=0x000000010000ea18
+ (void)start;	// IMP=0x000000010000e9c0
- (void).cxx_destruct;	// IMP=0x000000010000e438
- (void)_registerNewConnection:(id)arg1;	// IMP=0x000000010000e2b4
- (void)_startServer;	// IMP=0x000000010000e224
- (id)init;	// IMP=0x000000010000e180

@end

