//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_xpc_object;

@interface BTLEXpcConnection : NSObject
{
    NSObject<OS_xpc_object> *_connection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010000d484
@property(retain, nonatomic) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
- (void)peerIsNotUsingBuiltinService:(id)arg1;	// IMP=0x000000010000d374
- (void)peerIsUsingBuiltinService:(id)arg1;	// IMP=0x000000010000d278
- (void)authenticationDidFail:(id)arg1;	// IMP=0x000000010000d17c
- (void)authenticationDidSucceed:(id)arg1;	// IMP=0x000000010000d000
- (void)sendMsg:(id)arg1 args:(id)arg2;	// IMP=0x000000010000ced8
- (void)handleLeaStoreBondingInfoResponseMsg:(id)arg1;	// IMP=0x000000010000cdd4
- (void)handleLeaStoreBondingInfoRequestMsg:(id)arg1;	// IMP=0x000000010000ca2c
- (void)handleLeaEasyPairResponseMsg:(id)arg1;	// IMP=0x000000010000c928
- (void)handleLeaEasyPairRequestMsg:(id)arg1;	// IMP=0x000000010000c740
- (void)handleUARPDeviceConnectedMsg:(id)arg1;	// IMP=0x000000010000c6dc
- (void)handleDOAPDeviceConnectedMsg:(id)arg1;	// IMP=0x000000010000c6d8
- (void)handlePreWarmMFiAccessoryAuthMsg:(id)arg1;	// IMP=0x000000010000c640
- (void)handleMFiAccessoryAuthMsg:(id)arg1;	// IMP=0x000000010000c590
- (void)handleNotifyPrimaryBudSideMsg:(id)arg1;	// IMP=0x000000010000c48c
- (void)handleStoreClassicDeviceSettingsMsg:(id)arg1;	// IMP=0x000000010000bf64
- (void)handleStoreClassicLinkKeyResponseMsg:(id)arg1;	// IMP=0x000000010000be60
- (void)handleStoreClassicLinkKeyRequestExtendedMsg:(id)arg1;	// IMP=0x000000010000bc04
- (void)handleStoreClassicLinkKeyRequestMsg:(id)arg1;	// IMP=0x000000010000ba28
- (void)handleClassicPairStateResponseMsg:(id)arg1;	// IMP=0x000000010000b924
- (void)handleClassicPairStateRequestMsg:(id)arg1;	// IMP=0x000000010000b86c
- (void)handleVersionInfoResponseMsg:(id)arg1;	// IMP=0x000000010000b720
- (void)handleVersionInfoRequestMsg:(id)arg1;	// IMP=0x000000010000b61c
- (void)handleClassicDeviceUnexpectedDisconnectionMsg:(id)arg1;	// IMP=0x000000010000b564
- (void)handleDisconnectClassicDeviceMsg:(id)arg1;	// IMP=0x000000010000b4ac
- (void)handleConnectClassicDeviceMsg:(id)arg1;	// IMP=0x000000010000b3a8
- (void)handleNotifyPiconetClockMsg:(id)arg1;	// IMP=0x000000010000b214
- (void)handlePersistServerServicesMsg:(id)arg1;	// IMP=0x000000010000b174
- (void)handleConnectAlwaysMsg:(id)arg1;	// IMP=0x000000010000aff4
- (void)handleConnectOnceMsg:(id)arg1;	// IMP=0x000000010000af44
- (void)handleMsg:(id)arg1;	// IMP=0x000000010000ae4c
- (void)handleDisconnection;	// IMP=0x000000010000ad78
- (void)handleEvent:(id)arg1;	// IMP=0x000000010000ac94
- (id)initWithConnection:(id)arg1;	// IMP=0x000000010000aa3c

@end

