//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDPayloadMetadata.h"

@class NSString;

@interface DMDDeclarationPayloadMetadata : DMDPayloadMetadata
{
}

+ (id)fetchRequestForDeclarationsPendingDeleteFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x000000010003518c
+ (id)fetchRequestForFailedDeclarationsFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x0000000100035000
+ (id)fetchRequestForActiveDeclarationFromOrganizationWithIdentifier:(id)arg1 withIdentifier:(id)arg2 serverHash:(id)arg3;	// IMP=0x0000000100034e08
+ (id)fetchRequestForActiveDeclarationsFromOrganizationWithIdentifier:(id)arg1 withIdentifiers:(id)arg2;	// IMP=0x0000000100034c80
+ (id)fetchRequestForActiveDeclarationsFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x0000000100034b34
+ (id)fetchRequestForDeclarationsFromOrganizationWithIdentifier:(id)arg1 withIdentifiers:(id)arg2;	// IMP=0x0000000100034a84
+ (id)fetchRequestForDeclarationsFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x0000000100034a74
+ (id)fetchRequestForDeclarationsFromOrganizationWithIdentifier:(id)arg1 matchingPredicate:(id)arg2;	// IMP=0x0000000100034934
+ (id)declarationsWithDictionaries:(id)arg1 organizationIdentifier:(id)arg2 context:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100034618
- (void)setStateDictionary:(id)arg1;	// IMP=0x000000010003456c
- (id)descriptiveProperties;	// IMP=0x0000000100034480
- (void)applyPayloadDictionary:(id)arg1;	// IMP=0x0000000100034420
@property(readonly, copy, nonatomic) NSString *uniqueIdentifier;

// Remaining properties
@property(nonatomic) _Bool failed; // @dynamic failed;
@property(copy, nonatomic) NSString *serverHash; // @dynamic serverHash;

@end

