//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDFetchProvisioningProfilesOperation : DMDTaskOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x00000001000482c4
+ (id)whitelistedClassesForRequest;	// IMP=0x00000001000481fc
- (void)runWithRequest:(id)arg1;	// IMP=0x00000001000482d0

@end

