//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "LSApplicationWorkspaceObserverProtocol-Protocol.h"

@class BKSApplicationStateMonitor, NSString;
@protocol LSApplicationWorkspaceObserverProtocol;

@interface GKApplicationStateMonitor : NSObject <LSApplicationWorkspaceObserverProtocol>
{
    id <LSApplicationWorkspaceObserverProtocol> _delegate;	// 8 = 0x8
    BKSApplicationStateMonitor *_applicationStateMonitor;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010009bb00
@property(retain, nonatomic) BKSApplicationStateMonitor *applicationStateMonitor; // @synthesize applicationStateMonitor=_applicationStateMonitor;
@property(nonatomic) __weak id <LSApplicationWorkspaceObserverProtocol> delegate; // @synthesize delegate=_delegate;
- (void)applicationsWillUninstall:(id)arg1;	// IMP=0x000000010009b944
- (void)applicationsDidUninstall:(id)arg1;	// IMP=0x000000010009b7ac
- (void)startObservingApplicationWorkspaceChanges;	// IMP=0x000000010009b63c
- (void)startObservingStateChangesForBundleID:(id)arg1;	// IMP=0x000000010009b5ec
- (_Bool)observingStateChangesForBundleID:(id)arg1;	// IMP=0x000000010009b5b4
@property(copy, nonatomic) CDUnknownBlockType handler;
- (void)dealloc;	// IMP=0x000000010009b518
- (id)init;	// IMP=0x000000010009b4ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

