//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKFriendPlayerInternal.h"

@class NSArray, NSNumber, NSString;

@interface GKLocalPlayerInternal : GKFriendPlayerInternal
{
    NSString *_accountName;	// 248 = 0xf8
    NSArray *_emailAddresses;	// 256 = 0x100
    NSString *_facebookUserID;	// 264 = 0x108
    NSNumber *_iCloudUserID;	// 272 = 0x110
    unsigned short _numberOfRequests;	// 280 = 0x118
    unsigned short _numberOfTurns;	// 282 = 0x11a
    unsigned short _numberOfChallenges;	// 284 = 0x11c
    unsigned long long _loginStatus;	// 288 = 0x120
}

+ (id)secureCodedPropertyKeys;	// IMP=0x000000010016909c
+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100169094
+ (id)propertiesToFetch;	// IMP=0x000000010017e234
+ (id)archivedProfileForEnvironment:(long long)arg1;	// IMP=0x000000010019b5ec
+ (void)archiveProfile:(id)arg1 environment:(long long)arg2;	// IMP=0x000000010019b424
+ (id)_profileArchiveURLForEnvironment:(long long)arg1;	// IMP=0x000000010019b38c
- (void).cxx_destruct;	// IMP=0x0000000100169a08
@property unsigned long long loginStatus; // @synthesize loginStatus=_loginStatus;
- (void)setNumberOfChallenges:(unsigned short)arg1;	// IMP=0x00000001001699d8
- (unsigned short)numberOfChallenges;	// IMP=0x00000001001699c8
- (void)setNumberOfTurns:(unsigned short)arg1;	// IMP=0x00000001001699b8
- (unsigned short)numberOfTurns;	// IMP=0x00000001001699a8
- (void)setNumberOfRequests:(unsigned short)arg1;	// IMP=0x0000000100169998
- (unsigned short)numberOfRequests;	// IMP=0x0000000100169988
- (id)iCloudUserID;	// IMP=0x0000000100169978
- (void)setFacebookUserID:(id)arg1;	// IMP=0x0000000100169964
- (id)facebookUserID;	// IMP=0x0000000100169954
- (void)setEmailAddresses:(id)arg1;	// IMP=0x0000000100169940
- (id)emailAddresses;	// IMP=0x0000000100169930
- (void)setAccountName:(id)arg1;	// IMP=0x000000010016991c
- (id)accountName;	// IMP=0x000000010016990c
- (int)defaultFamiliarity;	// IMP=0x0000000100169904
- (void)setICloudUserID:(id)arg1;	// IMP=0x0000000100169890
- (_Bool)isFriend;	// IMP=0x0000000100169888
- (_Bool)isLocalPlayer;	// IMP=0x0000000100169880
- (void)setPhotoPending:(_Bool)arg1;	// IMP=0x0000000100169858
- (_Bool)isPhotoPending;	// IMP=0x0000000100169840
- (void)setFindable:(_Bool)arg1;	// IMP=0x0000000100169818
- (_Bool)isFindable;	// IMP=0x0000000100169800
- (void)setUnderage:(_Bool)arg1;	// IMP=0x00000001001697d8
- (_Bool)isUnderage;	// IMP=0x000000010016975c
- (void)setGlobalFriendListAccess:(long long)arg1;	// IMP=0x000000010016974c
- (long long)globalFriendListAccess;	// IMP=0x000000010016973c
- (void)setDefaultPrivacyVisibility:(_Bool)arg1;	// IMP=0x0000000100169714
- (_Bool)isDefaultPrivacyVisibility;	// IMP=0x00000001001696fc
- (void)setDefaultNickname:(_Bool)arg1;	// IMP=0x00000001001696d4
- (_Bool)isDefaultNickname;	// IMP=0x00000001001696bc
- (void)setPurpleBuddyAccount:(_Bool)arg1;	// IMP=0x0000000100169694
- (_Bool)isPurpleBuddyAccount;	// IMP=0x000000010016967c
- (id)minimalInternal;	// IMP=0x0000000100169398
- (void)updateWithProperties:(id)arg1;	// IMP=0x000000010017e5e4
- (void)updateWithCacheObject:(id)arg1;	// IMP=0x000000010017dd74

@end

