//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKInternalRepresentation.h"

@class GKGameRecordInternal, GKPlayerInternal, NSDate;

@interface GKRecentMatchInternal : GKInternalRepresentation
{
    GKPlayerInternal *_player;	// 8 = 0x8
    GKGameRecordInternal *_game;	// 16 = 0x10
    NSDate *_date;	// 24 = 0x18
}

+ (id)secureCodedPropertyKeys;	// IMP=0x0000000100164098
- (void).cxx_destruct;	// IMP=0x00000001001644a0
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) GKGameRecordInternal *game; // @synthesize game=_game;
@property(retain, nonatomic) GKPlayerInternal *player; // @synthesize player=_player;
- (unsigned long long)hash;	// IMP=0x0000000100164378
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001001641ac

@end

