//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@interface NIConfiguration : NSObject <NSCopying, NSSecureCoding>
{
    unsigned long long _suspensionPolicy;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001001636c0
+ (id)new;	// IMP=0x000000010016353c
@property unsigned long long suspensionPolicy; // @synthesize suspensionPolicy=_suspensionPolicy;
- (_Bool)isEqualToConfiguration:(id)arg1;	// IMP=0x0000000100163858
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100163738
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100163708
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001636c8
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00000001001635a4
- (id)initInternal;	// IMP=0x0000000100163564
- (id)init;	// IMP=0x00000001001634f0

@end

