//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NIConfiguration.h"

@class NIDiscoveryToken;

@interface NINearbyPeerConfiguration : NIConfiguration
{
    NIDiscoveryToken *_peerDiscoveryToken;	// 16 = 0x10
}

+ (id)new;	// IMP=0x0000000100163cac
+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100163a94
- (void).cxx_destruct;	// IMP=0x0000000100163fcc
@property(copy, nonatomic) NIDiscoveryToken *peerDiscoveryToken; // @synthesize peerDiscoveryToken=_peerDiscoveryToken;
- (id)descriptionInternal;	// IMP=0x0000000100163ecc
- (id)description;	// IMP=0x0000000100163e00
- (unsigned long long)hash;	// IMP=0x0000000100163dd4
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100163cd4
- (id)init;	// IMP=0x0000000100163c60
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100163b74
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100163ae0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100163a9c
- (id)initWithPeerToken:(id)arg1;	// IMP=0x0000000100163970

@end

