//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PRUWBServiceProviding-Protocol.h"

@class NSString;

@interface PRUWBManagerAgent : NSObject <PRUWBServiceProviding>
{
    shared_ptr_55175bc8 _clientReference;	// 8 = 0x8
}

- (id).cxx_construct;	// IMP=0x0000000100017dcc
- (void).cxx_destruct;	// IMP=0x0000000100017dc4
- (_Bool)sendHangupSignalForTicket:(unsigned long long)arg1;	// IMP=0x0000000100017cb0
- (_Bool)sendTrackingAssistanceData;	// IMP=0x0000000100017bf0
- (void)requestAsyncServiceStatusUpdate;	// IMP=0x0000000100017b14
- (_Bool)stopWithTicket:(unsigned long long)arg1;	// IMP=0x0000000100017a88
- (_Bool)startWithTicket:(unsigned long long)arg1 options:(struct RoseStartRangingOptions)arg2;	// IMP=0x00000001000179ec
- (_Bool)unregisterForService:(unsigned long long)arg1;	// IMP=0x00000001000178f8
- (_Bool)registerForService:(const struct RoseServiceRequest *)arg1 outTicket:(unsigned long long *)arg2;	// IMP=0x00000001000177b8
- (void)disconnect;	// IMP=0x00000001000176c4
- (unsigned long long)connect;	// IMP=0x0000000100017520
- (shared_ptr_3baa22f1)configurationManager;	// IMP=0x00000001000174dc
- (struct PRUWBDeviceCapabilities)deviceCapabilities;	// IMP=0x0000000100017368
- (id)getQueue;	// IMP=0x0000000100017350
- (id)initWithClientReference:(shared_ptr_55175bc8)arg1;	// IMP=0x00000001000172ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

