//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "APSConnectionDelegate-Protocol.h"
#import "WLKNotificationCenterDelegate-Protocol.h"

@class AMSMetrics, AMSPushHandler, APSConnection, NSArray, NSMutableArray, NSString, WLDMercuryPushHandler, WLDUTSPushHandler, WLKNotificationCenter;

__attribute__((visibility("hidden")))
@interface WLDPushNotificationController : NSObject <APSConnectionDelegate, WLKNotificationCenterDelegate>
{
    APSConnection *_connection;	// 8 = 0x8
    NSString *_environment;	// 16 = 0x10
    NSArray *_validTopics;	// 24 = 0x18
    NSMutableArray *_pendingOpportunisticTopics;	// 32 = 0x20
    AMSMetrics *_metricsController;	// 40 = 0x28
    WLKNotificationCenter *_notifCenter;	// 48 = 0x30
    WLDUTSPushHandler *_utsPushHandler;	// 56 = 0x38
    AMSPushHandler *_amsPushHandler;	// 64 = 0x40
    WLDMercuryPushHandler *_mercuryPushHandler;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x000000010001b41c
@property(readonly, nonatomic) AMSMetrics *metricsController; // @synthesize metricsController=_metricsController;
- (id)_portNameForEnvironmentName:(id)arg1;	// IMP=0x000000010001b368
- (void)_loadURLBagWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001aeb4
- (void)_postNotificationWithPayload:(id)arg1;	// IMP=0x00000001000198c4
- (void)_reportMercuryMetrics:(id)arg1;	// IMP=0x00000001000194e4
- (void)_reportBulletinMetrics:(id)arg1;	// IMP=0x00000001000190c0
- (void)_augmentCustomEventInfo:(id)arg1;	// IMP=0x0000000100018cb0
- (void)_registerOpportunisticTopics;	// IMP=0x0000000100018b3c
- (void)handleAction:(id)arg1;	// IMP=0x0000000100018778
- (void)connection:(id)arg1 didReceiveMessageForTopic:(id)arg2 userInfo:(id)arg3;	// IMP=0x0000000100017ba4
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;	// IMP=0x0000000100017a4c
- (void)registerOpportunisticTopics;	// IMP=0x00000001000178d8
- (void)dealloc;	// IMP=0x0000000100017884
- (id)init;	// IMP=0x00000001000172d8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

