//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface UARPManifestEntry : NSObject
{
    _Bool _trusted;	// 8 = 0x8
    _Bool _productionMode;	// 9 = 0x9
    _Bool _securityMode;	// 10 = 0xa
    NSString *_name;	// 16 = 0x10
    NSData *_digest;	// 24 = 0x18
}

@property(readonly) _Bool securityMode; // @synthesize securityMode=_securityMode;
@property(readonly) _Bool productionMode; // @synthesize productionMode=_productionMode;
@property(readonly) _Bool trusted; // @synthesize trusted=_trusted;
@property(readonly) NSData *digest; // @synthesize digest=_digest;
@property(readonly) NSString *name; // @synthesize name=_name;
- (id)descriptionWithTabDepth:(unsigned long long)arg1;	// IMP=0x000000010002badc
- (id)description;	// IMP=0x000000010002bacc
@property(readonly) NSDictionary *personalizationDictionary;
- (id)initWithName:(id)arg1 digest:(id)arg2 trusted:(_Bool)arg3 productionMode:(_Bool)arg4 securityMode:(_Bool)arg5;	// IMP=0x000000010002b91c

@end

