//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Security/SFAnalytics.h>

__attribute__((visibility("hidden")))
@interface CKKSAnalytics : SFAnalytics
{
}

+ (id)logger;	// IMP=0x000000010012dc98
+ (id)databasePath;	// IMP=0x000000010012dc48
- (id)datePropertyForKey:(id)arg1 zoneName:(id)arg2;	// IMP=0x000000010012dbcc
- (void)setDateProperty:(id)arg1 forKey:(id)arg2 zoneName:(id)arg3;	// IMP=0x000000010012db2c
- (id)dateOfLastSuccessForEvent:(id)arg1 zoneName:(id)arg2;	// IMP=0x000000010012dab0
- (void)noteEvent:(id)arg1 zoneName:(id)arg2;	// IMP=0x000000010012da48
- (void)noteEvent:(id)arg1;	// IMP=0x000000010012da3c
- (void)logUnrecoverableError:(id)arg1 forEvent:(id)arg2 withAttributes:(id)arg3;	// IMP=0x000000010012d778
- (void)logUnrecoverableError:(id)arg1 forEvent:(id)arg2 zoneName:(id)arg3 withAttributes:(id)arg4;	// IMP=0x000000010012d4a4
- (void)logRecoverableError:(id)arg1 forEvent:(id)arg2 withAttributes:(id)arg3;	// IMP=0x000000010012d1ec
- (void)logRecoverableError:(id)arg1 forEvent:(id)arg2 zoneName:(id)arg3 withAttributes:(id)arg4;	// IMP=0x000000010012cf10
- (id)createErrorAttributes:(id)arg1 depth:(unsigned long long)arg2 attributes:(id)arg3;	// IMP=0x000000010012cca4
- (id)errorChain:(id)arg1 depth:(unsigned long long)arg2;	// IMP=0x000000010012ca78
- (void)addCKPartialError:(id)arg1 error:(id)arg2 depth:(unsigned long long)arg3;	// IMP=0x000000010012c740
- (_Bool)isCKPartialError:(id)arg1;	// IMP=0x000000010012c6ac
- (void)logSuccessForEvent:(id)arg1 zoneName:(id)arg2;	// IMP=0x000000010012c594

@end

