//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SECC2MPServerInfo : PBCodable <NSCopying>
{
    NSString *_partition;	// 8 = 0x8
    NSString *_serviceBuild;	// 16 = 0x10
    NSString *_serviceInstance;	// 24 = 0x18
    NSString *_serviceName;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010018aa6c
@property(retain, nonatomic) NSString *serviceInstance; // @synthesize serviceInstance=_serviceInstance;
@property(retain, nonatomic) NSString *serviceBuild; // @synthesize serviceBuild=_serviceBuild;
@property(retain, nonatomic) NSString *partition; // @synthesize partition=_partition;
@property(retain, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010018a930
- (unsigned long long)hash;	// IMP=0x000000010018a8a4
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010018a778
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010018a678
- (void)copyTo:(id)arg1;	// IMP=0x000000010018a5cc
- (void)writeTo:(id)arg1;	// IMP=0x000000010018a530
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010018a528
- (id)dictionaryRepresentation;	// IMP=0x000000010018a44c
- (id)description;	// IMP=0x000000010018a398
@property(readonly, nonatomic) _Bool hasServiceInstance;
@property(readonly, nonatomic) _Bool hasServiceBuild;
@property(readonly, nonatomic) _Bool hasPartition;
@property(readonly, nonatomic) _Bool hasServiceName;

@end

