//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface SecXPCHelper : NSObject
{
}

+ (id)encodedDataFromError:(id)arg1;	// IMP=0x000000010001ed30
+ (id)errorFromEncodedData:(id)arg1;	// IMP=0x000000010001ec90
+ (id)cleanseErrorForXPC:(id)arg1;	// IMP=0x000000010001eb88
+ (id)cleanObjectForXPC:(id)arg1;	// IMP=0x000000010001e4a4
+ (id)cleanDictionaryForXPC:(id)arg1;	// IMP=0x000000010001e2fc
+ (id)safeErrorClasses;	// IMP=0x000000010001e2bc
+ (id)safeErrorCollectionClasses;	// IMP=0x000000010001e27c
+ (id)safeCKErrorPrimitiveClasses;	// IMP=0x000000010001e23c
+ (id)safeErrorPrimitiveClasses;	// IMP=0x000000010001e1fc

@end

