//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SHLCloudContainerTransformer, SHLCloudLibraryCache, SHLCloudModifyZoneTransformer;

__attribute__((visibility("hidden")))
@interface SHLCloudTaskScheduler : NSObject
{
    SHLCloudContainerTransformer *_containerTransformer;	// 8 = 0x8
    SHLCloudModifyZoneTransformer *_zoneTransformer;	// 16 = 0x10
    SHLCloudLibraryCache *_cache;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010001f1b4
@property(retain, nonatomic) SHLCloudLibraryCache *cache; // @synthesize cache=_cache;
@property(retain, nonatomic) SHLCloudModifyZoneTransformer *zoneTransformer; // @synthesize zoneTransformer=_zoneTransformer;
@property(retain, nonatomic) SHLCloudContainerTransformer *containerTransformer; // @synthesize containerTransformer=_containerTransformer;
- (id)initWithScope:(long long)arg1;	// IMP=0x000000010001efd8

@end

