//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SHLLibraryCache-Protocol.h"
#import "SHLLocalStateTransactionable-Protocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SHLCloudLibraryCache : NSObject <SHLLibraryCache, SHLLocalStateTransactionable>
{
    NSString *_containerID;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100023c88
@property(retain, nonatomic) NSString *containerID; // @synthesize containerID=_containerID;
- (_Bool)commitTransactionWithError:(id *)arg1;	// IMP=0x0000000100023b40
- (_Bool)undoTransactionWithError:(id *)arg1;	// IMP=0x0000000100023aac
- (_Bool)startTransactionWithError:(id *)arg1;	// IMP=0x0000000100023948
- (id)failedTaskPathForIdentifier:(id)arg1;	// IMP=0x00000001000238c8
- (id)inflightTaskPathForIdentifier:(id)arg1;	// IMP=0x0000000100023848
- (id)zonePathForIdentifier:(id)arg1;	// IMP=0x00000001000237c8
- (id)failedFolderPath;	// IMP=0x000000010002376c
- (id)inflightFolderPath;	// IMP=0x0000000100023710
- (id)zonesFolderPath;	// IMP=0x00000001000236b4
- (id)privateDatabaseTransactionPath;	// IMP=0x0000000100023658
- (id)privateDatabaseFolderPath;	// IMP=0x00000001000235fc
- (id)currentDatabaseFolderPath;	// IMP=0x00000001000234fc
- (id)cachesDirectory;	// IMP=0x000000010002344c
- (_Bool)doesCachesDirectoryExist;	// IMP=0x00000001000233ac
- (_Bool)createPrivateDatabaseFolderPath;	// IMP=0x0000000100023308
- (_Bool)doesPrivateDatabaseFolderPathExist;	// IMP=0x0000000100023268
- (_Bool)createTaskFolderPaths;	// IMP=0x000000010002310c
- (_Bool)doesTaskFolderPathsExist;	// IMP=0x0000000100022fe8
- (_Bool)createZoneFolderPath;	// IMP=0x0000000100022f44
- (_Bool)doesZoneFolderPathExist;	// IMP=0x0000000100022ea4
- (_Bool)subscriptionExistsForZoneIdentifier:(id)arg1;	// IMP=0x0000000100022df8
- (_Bool)removeSubscriptionForZoneIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100022d48
- (_Bool)storeSubscription:(id)arg1 forZoneIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100022bec
- (id)zoneTokenForZoneIdentifier:(id)arg1;	// IMP=0x0000000100022a88
- (id)databaseToken;	// IMP=0x0000000100022914
- (_Bool)removeTokenAtPath:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100022880
- (_Bool)removeTokenForZoneIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100022818
- (_Bool)removeDatabaseTokenWithError:(id *)arg1;	// IMP=0x00000001000227b0
- (_Bool)writeToken:(id)arg1 toPath:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000226bc
- (_Bool)storeZoneToken:(id)arg1 forZoneIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000225e4
- (_Bool)storeDatabaseToken:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100022530
- (_Bool)zoneExistsForIdentifier:(id)arg1;	// IMP=0x0000000100022470
- (_Bool)removeZoneIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000223a4
- (_Bool)storeZoneIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000222c0
- (id)taskForFilePath:(id)arg1;	// IMP=0x0000000100022138
- (id)tasksForFolderPath:(id)arg1 ofType:(long long)arg2;	// IMP=0x0000000100021e0c
- (id)taskOfType:(long long)arg1 identifier:(id)arg2;	// IMP=0x0000000100021d10
- (id)tasksOfType:(long long)arg1;	// IMP=0x0000000100021bf8
- (void)removeAllTasksOfType:(long long)arg1;	// IMP=0x0000000100021a98
- (_Bool)removeTaskOfType:(long long)arg1 forIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100021974
- (_Bool)storeTask:(id)arg1 ofType:(long long)arg2 error:(id *)arg3;	// IMP=0x0000000100021828
- (_Bool)resetWithError:(id *)arg1;	// IMP=0x0000000100021784
- (id)initWithContainerIdentifier:(id)arg1;	// IMP=0x000000010002170c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

