//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface SHLError : NSObject
{
}

+ (id)localizedRecoverySuggestionForSyncError:(long long)arg1;	// IMP=0x0000000100019ca8
+ (id)localizedFailureReasonForSyncError:(long long)arg1;	// IMP=0x0000000100019c30
+ (id)localizedDescriptionForSyncError:(long long)arg1;	// IMP=0x0000000100019bb8
+ (long long)errorCodeForError:(id)arg1;	// IMP=0x0000000100019b2c
+ (id)userInfoForErrorCode:(long long)arg1 withUnderlyingError:(id)arg2;	// IMP=0x00000001000199b0
+ (id)errorCode:(long long)arg1 underlyingError:(id)arg2;	// IMP=0x0000000100019944
+ (_Bool)canRetryForPartialError:(id)arg1;	// IMP=0x0000000100019818
+ (_Bool)canRetryForError:(id)arg1;	// IMP=0x00000001000196ec
+ (double)retrySecondsForError:(id)arg1;	// IMP=0x0000000100019420
+ (id)errorWithUnderlyingError:(id)arg1;	// IMP=0x00000001000193a0
+ (id)errorWithCode:(long long)arg1 underlyingError:(id)arg2;	// IMP=0x000000010001938c
+ (id)errorWithCode:(long long)arg1;	// IMP=0x0000000100019374

@end

