//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IXDataPromiseSeed.h"

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@interface IXOpaqueDataPromiseSeed : IXDataPromiseSeed <NSSecureCoding, NSCopying>
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010000c308
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010000c310
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010000c2d4
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010000c2a0

@end

