//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleAccount/AAFamilyDetailsRequest.h>

@class ACAccount;

@interface FAFamilyDetailsRequest : AAFamilyDetailsRequest
{
    ACAccount *_account;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100009d88
- (id)urlRequest;	// IMP=0x0000000100009cb8
- (id)initWithAccount:(id)arg1;	// IMP=0x0000000100009c34

@end

