//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SKProductSubscriptionPeriod : NSObject
{
    id _internal;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010004ae54
- (id)copyXPCEncoding;	// IMP=0x000000010004adf4
- (id)initWithXPCEncoding:(id)arg1;	// IMP=0x000000010004ad4c
- (id)initWithISO8601String:(id)arg1;	// IMP=0x000000010004ab18
- (id)init;	// IMP=0x000000010004aab4
- (void)_setUnit:(unsigned long long)arg1;	// IMP=0x000000010004aaa8
- (void)_setNumberOfUnits:(unsigned long long)arg1;	// IMP=0x000000010004aa9c
@property(readonly, nonatomic) unsigned long long unit;
@property(readonly, nonatomic) unsigned long long numberOfUnits;

@end

