//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DownloadDataConsumer.h"

#import "SZExtractorDelegate-Protocol.h"

@class NSDictionary, NSString, SZExtractor;

@interface StreamingZipDownloadDataConsumer : DownloadDataConsumer <SZExtractorDelegate>
{
    SZExtractor *_extractor;	// 8 = 0x8
    _Bool _hasConsumedData;	// 16 = 0x10
    NSDictionary *_options;	// 24 = 0x18
    NSString *_path;	// 32 = 0x20
    double _percentComplete;	// 40 = 0x28
    unsigned long long _resumptionOffset;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100092310
- (unsigned long long)resumptionOffset;	// IMP=0x0000000100092300
- (double)percentComplete;	// IMP=0x00000001000922f0
- (_Bool)hasConsumedData;	// IMP=0x00000001000922e0
- (id)_stringWithFileSystemRepresentation:(const char *)arg1 length:(unsigned long long)arg2;	// IMP=0x000000010009226c
- (id)_stringWithFileSystemRepresentation:(const char *)arg1;	// IMP=0x0000000100092230
- (unsigned long long)_diskUsageForPath:(id)arg1;	// IMP=0x00000001000912c8
- (void)_initializeExtractorWithPath:(id)arg1 options:(id)arg2;	// IMP=0x0000000100091188
- (void)setExtractionProgress:(double)arg1;	// IMP=0x0000000100091178
- (void)truncate;	// IMP=0x00000001000910d8
- (void)suspend;	// IMP=0x0000000100091024
- (void)reset;	// IMP=0x0000000100090fb4
- (_Bool)finish:(id *)arg1;	// IMP=0x0000000100090da0
- (unsigned long long)diskUsage;	// IMP=0x0000000100090d50
- (_Bool)consumeData:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100090b1c
- (id)initWithPath:(id)arg1 options:(id)arg2;	// IMP=0x00000001000909f8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

