//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IAPDataLogger : NSObject
{
}

+ (void)PowerlogEASession:(id)arg1 forAccessory:(id)arg2 forProtocolID:(unsigned char)arg3 forPortType:(unsigned char)arg4 isSessionOpen:(_Bool)arg5;	// IMP=0x000000010001fc1c
+ (void)PowerlogAccDetach:(id)arg1 AndConnectionTime:(unsigned long long)arg2;	// IMP=0x000000010001f998
+ (void)PowerlogAccAttach:(id)arg1;	// IMP=0x000000010001f768
+ (void)AggAccDetach:(id)arg1 WithManufacturer:(id)arg2 AndConnectionTime:(unsigned long long)arg3;	// IMP=0x000000010001f6a0
+ (void)AggAccAttach:(id)arg1 WithManufacturer:(id)arg2;	// IMP=0x000000010001f618
+ (unsigned long long)sanitizeData:(unsigned long long)arg1;	// IMP=0x000000010001f5f0
+ (id)sanitizeString:(id)arg1;	// IMP=0x000000010001f4c8

@end

