//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IAPApplicationStateMonitor, NSArray, NSDate, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface MediaPlayerHelper : NSObject
{
    NSMutableDictionary *_nowPlayingInfo;	// 8 = 0x8
    struct _opaque_pthread_mutex_t {
        long long __sig;
        char __opaque[56];
    } _nowPlayingInfoLock;	// 16 = 0x10
    NSString *_nowPlayingAppIdentifier;	// 80 = 0x50
    NSString *_nowPlayingAppName;	// 88 = 0x58
    unsigned char _nowPlayingAppChanged;	// 96 = 0x60
    unsigned char _nowPlayingAppIsIPod;	// 97 = 0x61
    unsigned char _nowPlayingAppIsIPodRadio;	// 98 = 0x62
    unsigned char _nowPlayingAppIsIPodIsValid;	// 99 = 0x63
    unsigned char _nowPlayingAppIsPlaying;	// 100 = 0x64
    NSObject<OS_dispatch_queue> *nowPlayingHandlerQueue;	// 104 = 0x68
    int repeatModeCache;	// 112 = 0x70
    int shuffleModeCache;	// 116 = 0x74
    int expectedRepeatMode;	// 120 = 0x78
    int expectedShuffleMode;	// 124 = 0x7c
    unsigned int expectedRepeatModeTimestamp;	// 128 = 0x80
    unsigned int expectedShuffleModeTimestamp;	// 132 = 0x84
    NSDate *_nowPlayingAppIsPlayingTimestamp;	// 136 = 0x88
    NSArray *pbqItems;	// 144 = 0x90
    unsigned int _fakeStreamTrackIndex;	// 152 = 0x98
    unsigned int _fakeStreamTrackCount;	// 156 = 0x9c
    _Bool _fakeStreamTrackIndexSet;	// 160 = 0xa0
    unsigned int _fakeStreamTrackIndexSetTimestamp;	// 164 = 0xa4
    _Bool _fakeStreamTrackIndexNeedChange;	// 168 = 0xa8
    unsigned int _lastTimeNowPlayingPBRateChangeToPauseOrStop;	// 172 = 0xac
    _Bool _explicitControlOccurred;	// 176 = 0xb0
    _Bool _lastWasStreamPlayback;	// 177 = 0xb1
    struct __CFArray *_currentSupportedCommands;	// 184 = 0xb8
    _Bool _nowPlayingInfoEverReceived;	// 192 = 0xc0
    IAPApplicationStateMonitor *_appStateMonitor;	// 200 = 0xc8
    int _cachedPlaybackStateResult;	// 208 = 0xd0
    _Bool podcastAppSelected;	// 212 = 0xd4
    _Bool iBooksAppSelected;	// 213 = 0xd5
    _Bool iTunesUAppSelected;	// 214 = 0xd6
}

+ (id)sharedSystemMusicPlayerQueue;	// IMP=0x000000010003f0dc
+ (id)sharedSystemMusicPlayer;	// IMP=0x000000010003f008
@property(readonly, nonatomic) _Bool fakeStreamTrackIndexSet; // @synthesize fakeStreamTrackIndexSet=_fakeStreamTrackIndexSet;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *nowPlayingHandlerQueue; // @synthesize nowPlayingHandlerQueue;
@property(nonatomic) _Bool iTunesUAppSelected; // @synthesize iTunesUAppSelected;
@property(nonatomic) _Bool iBooksAppSelected; // @synthesize iBooksAppSelected;
@property(nonatomic) _Bool podcastAppSelected; // @synthesize podcastAppSelected;
@property(nonatomic) int shuffleModeCache; // @synthesize shuffleModeCache;
@property(nonatomic) int repeatModeCache; // @synthesize repeatModeCache;
- (_Bool)_isCommandSupported:(unsigned int)arg1;	// IMP=0x0000000100043edc
- (void *)_findCommandRefForCommand:(unsigned int)arg1;	// IMP=0x0000000100043dbc
- (_Bool)_isSetElapsedTimeAvailable;	// IMP=0x0000000100043d9c
- (void)_supportedCommandsDidChangeNotification;	// IMP=0x0000000100043d00
- (void)_supportedCommandsDidChange:(struct __CFArray *)arg1;	// IMP=0x0000000100043c74
- (void)_checkShuffleRepeatModeChange;	// IMP=0x00000001000439d8
- (void)notifyExplicitControlOccurred;	// IMP=0x00000001000439cc
- (void)_itemPlaybackDidEnd:(id)arg1;	// IMP=0x0000000100043788
- (void)_mediaLibraryChanged:(id)arg1;	// IMP=0x00000001000436d8
- (void)_nowPlayingAppChanged:(id)arg1;	// IMP=0x0000000100043530
- (void)_playbackQueueDidChangeNotification:(id)arg1;	// IMP=0x000000010004348c
- (void)_nowPlayingAppIsPlayingChanged:(id)arg1;	// IMP=0x000000010004339c
- (void)_nowPlayingInfoChanged:(id)arg1;	// IMP=0x0000000100042fd8
- (void)_canShowCloudTracksDidChangeNotification:(id)arg1;	// IMP=0x0000000100042f30
- (void)_setNowPlayingApp:(id)arg1;	// IMP=0x0000000100042eb0
- (void)_handleNowPlayingAppDidChange:(id)arg1;	// IMP=0x0000000100042bf0
- (void)_handlePlaybackQueueDidChange;	// IMP=0x0000000100042a40
- (void)_handleNowPlayingAppIsPlayingDidChange:(unsigned char)arg1;	// IMP=0x00000001000427ec
- (void)_handleNowPlayingInfo:(struct __CFDictionary *)arg1;	// IMP=0x00000001000413cc
- (void)_printNowPlayingInfo:(id)arg1 forName:(id)arg2;	// IMP=0x000000010004133c
- (id)_nowPlayingInfoDesc:(id)arg1;	// IMP=0x0000000100040f98
- (id)getPBQItemsFromQueueQuery;	// IMP=0x0000000100040f80
- (void)initPBQItemsFromQueueQuery;	// IMP=0x0000000100040ee8
- (_Bool)currentNowPlayingInfoTrackCountExists;	// IMP=0x0000000100040e74
- (_Bool)currentNowPlayingInfoArtworkExists;	// IMP=0x0000000100040df0
- (id)currentNowPlayingInfoArtwork;	// IMP=0x0000000100040d74
- (void)setExpectedRepeatMode:(int)arg1;	// IMP=0x0000000100040cc8
- (void)setExpectedShuffleMode:(int)arg1;	// IMP=0x0000000100040c1c
- (int)currentRepeatMode;	// IMP=0x0000000100040b08
- (int)currentShuffleMode;	// IMP=0x0000000100040a34
- (_Bool)isLoadingRadioStation;	// IMP=0x000000010004099c
- (unsigned int)currentNowPlayingInfoAlbumTrackCount;	// IMP=0x0000000100040984
- (unsigned int)currentNowPlayingInfoAlbumTrack;	// IMP=0x000000010004096c
- (unsigned int)currentNowPlayingInfoDiscCount;	// IMP=0x0000000100040954
- (unsigned int)currentNowPlayingInfoDisc;	// IMP=0x000000010004093c
- (unsigned int)currentNowPlayingInfoChapterCount;	// IMP=0x0000000100040924
- (unsigned int)currentNowPlayingInfoChapter;	// IMP=0x000000010004090c
- (unsigned int)currentNowPlayingInfoTrackCount;	// IMP=0x00000001000407a4
- (unsigned int)_currentNowPlayingInfoTrack:(_Bool)arg1;	// IMP=0x00000001000405e0
- (unsigned int)currentNowPlayingInfoTrack;	// IMP=0x00000001000405d0
- (id)nowPlayingInfoTitleForAudiobookIndex:(unsigned int)arg1;	// IMP=0x0000000100040510
- (id)currentNowPlayingInfoString:(id)arg1;	// IMP=0x0000000100040490
- (unsigned int)currentNowPlayingInfoNumber:(id)arg1;	// IMP=0x0000000100040410
- (unsigned long long)currentNowPlayingInfoPID;	// IMP=0x000000010004038c
- (double)currentNowPlayingInfoDuration;	// IMP=0x00000001000402fc
- (double)currentPlaybackTime;	// IMP=0x00000001000400f4
- (double)nowPlayingAppPlaybackSpeed;	// IMP=0x0000000100040064
- (double)nowPlayingAppPlaybackRate;	// IMP=0x000000010003ffb4
- (int)nowPlayingAppPlaybackState;	// IMP=0x000000010003fd30
- (id)nowPlayingAppName;	// IMP=0x000000010003fd00
- (unsigned char)nowPlayingAppIsiTunesUApp;	// IMP=0x000000010003fcc8
- (unsigned char)nowPlayingAppIsiBooksApp;	// IMP=0x000000010003fc90
- (unsigned char)nowPlayingAppIsPodcastApp;	// IMP=0x000000010003fc58
- (unsigned char)nowPlayingAppIsVideosApp;	// IMP=0x000000010003fc1c
- (unsigned char)nowPlayingAppIsiTunesRadio;	// IMP=0x000000010003fbe4
- (unsigned char)nowPlayingAppIsIPodApp;	// IMP=0x000000010003fb18
- (unsigned char)nowPlayingAppIsValid;	// IMP=0x000000010003fadc
- (void)_shuffleModeChanged:(id)arg1;	// IMP=0x000000010003fa5c
- (void)_repeatModeChanged:(id)arg1;	// IMP=0x000000010003f9dc
- (void)_nowPlayingItemChanged:(id)arg1;	// IMP=0x000000010003f79c
- (int)prepareForPlaybackWithQuery:(id)arg1 andFirstItem:(id)arg2;	// IMP=0x000000010003f1ac
- (void)postFakeShuffleModeChanged;	// IMP=0x000000010003f144
- (void)dealloc;	// IMP=0x000000010003eda8
- (id)init;	// IMP=0x000000010003e6f0
- (void)_stopMusicPlayerNotifications:(id)arg1;	// IMP=0x000000010003e684
- (void)_startMusicPlayerNotifications:(id)arg1;	// IMP=0x000000010003e588
- (void)_waitForNowPlayingInfoReceived;	// IMP=0x000000010003e49c
@property(readonly, nonatomic) _Bool fakeStreamTrackIndexTimeExpired;
- (void)_calcNewFakeStreamIndexCount;	// IMP=0x000000010003e358
- (void)_setFakeStreamTrackIndex:(unsigned int)arg1 fromPlay:(_Bool)arg2;	// IMP=0x000000010003e094
- (void)_setFakeStreamTrackIndexForSetCurIndex:(unsigned int)arg1;	// IMP=0x000000010003dd28
- (void)_resetFakeStreamTrackCount;	// IMP=0x000000010003dce8

@end

