//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ICEnvironmentMonitorObserver-Protocol.h"

@class ICMusicLibraryArtistAffinityAnalyzer, NSNumber, NSString;
@protocol NSCopying, OS_dispatch_queue;

@interface ICMusicLibraryRecommendationController : NSObject <ICEnvironmentMonitorObserver>
{
    ICMusicLibraryArtistAffinityAnalyzer *_affinityAnalyzer;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_accessQueue;	// 16 = 0x10
    _Bool _userHasOptedIn;	// 24 = 0x18
    _Bool _userHasEverToggledOptInSwitch;	// 25 = 0x19
    id <NSCopying> _subscriptionObservationToken;	// 32 = 0x20
    _Bool _isSystemService;	// 40 = 0x28
    _Bool _failedToPerformAnalysis;	// 41 = 0x29
    NSNumber *_lastSeenDSID;	// 48 = 0x30
    double _lastTimePeriodicXPCFired;	// 56 = 0x38
    double _refreshIntervalFromBag;	// 64 = 0x40
}

+ (id)sharedLibraryRecommendationController;	// IMP=0x00000001000908ec
- (void).cxx_destruct;	// IMP=0x000000010008b4cc
- (id)_createLocalNotificationDictionaryForRecommendationResult:(id)arg1 storePlatformMetadata:(id)arg2 recommendationID:(id)arg3 identifier:(id)arg4;	// IMP=0x000000010008a7e8
- (void)_updateOptInIfNecessary;	// IMP=0x000000010008a718
- (void)_optInMessageForPriorityMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010008a614
- (id)_optInMessageContentForPriorityMessageContent:(id)arg1;	// IMP=0x000000010008a45c
- (void)_createApplicationMessagesForResult:(id)arg1 artistNewContentResponse:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010008a1fc
- (void)_cleanupExpiredApplicationMessages;	// IMP=0x000000010008a12c
- (id)_retrievePreviousRecommendationMatchesFromCache;	// IMP=0x000000010008a038
- (id)_cacheDirectoryPath;	// IMP=0x0000000100089fb4
- (id)_getNetworkConstraints;	// IMP=0x0000000100089f5c
- (id)_storeRequestContext;	// IMP=0x0000000100089f2c
- (id)_wrapAndCacheResponseModelWithCompiledMLModel:(id)arg1;	// IMP=0x0000000100089854
- (_Bool)_setupCacheDirectoryStructureWithPath:(id)arg1;	// IMP=0x000000010008969c
- (void)_clearMLModelCache;	// IMP=0x00000001000894c0
- (void)_fetchRecommendationsSetAndModelWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000893c8
- (void)_computeLibraryRecommendationWithResponse:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100089230
- (void)_handleRecommendationsResponseModel:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010008904c
- (void)_performRecommendationsRequest;	// IMP=0x0000000100088f04
- (void)_performRecommendationsUpdate;	// IMP=0x0000000100088c84
- (void)_cacheMatchedRecommendations:(id)arg1;	// IMP=0x0000000100088c04
- (void)_clearRecommendationsData;	// IMP=0x000000010008893c
- (void)_handleNewArtistContentResponseNotification:(id)arg1;	// IMP=0x00000001000886f4
- (void)environmentMonitorDidChangeNetworkType:(id)arg1;	// IMP=0x00000001000885f8
- (void)handleAccountStateChange:(id)arg1;	// IMP=0x0000000100088514
- (void)scheduleRecommendationsRefreshTimer;	// IMP=0x000000010008833c
- (void)stopSystemService;	// IMP=0x000000010008819c
- (void)startSystemService;	// IMP=0x0000000100087ff0
- (void)dealloc;	// IMP=0x0000000100087f54
- (id)init;	// IMP=0x0000000100087db8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

