//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CloudLibraryOperation.h"

@interface SagaCloudAddOperation : CloudLibraryOperation
{
}

- (void)main;	// IMP=0x00000001000ba420
- (_Bool)isPersistent;	// IMP=0x00000001000ba418
- (unsigned int)currentDatabaseRevision;	// IMP=0x00000001000ba3c8
- (void)removePendingAddedItemsForPermanentlyFailedOperation;	// IMP=0x00000001000ba3c4
- (void)processAddedItems:(id)arg1;	// IMP=0x00000001000ba3c0
- (void)logCloudAddRequestDescription;	// IMP=0x00000001000ba3bc
- (id)cloudAddRequestWithDatabaseID:(unsigned int)arg1;	// IMP=0x00000001000ba3b4

@end

